### ISSUE TITLE
helper Text in Home Dashboard

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#10]
When new Litmus users log in, it'd be nice to welcome them in the Home dashboard. Eventually this can link to help, chat, docs, etc, etc.

Here's some sample text welcoming a user to Litmus:

====

Welcome to raintank Litmus!
 
Litmus allows you to monitor the network quality of anything from anywhere.
 
Whether you have a simple blog or a globally distributed application, Litmus can help you analyze its performance and availability from around the world.
 
Litmus is currently in restricted alpha. Your feedback is much appreciated and helps make it better.

**Comment by nopzor1200** [comment]
Possibly solvable in the same way as grafana#1684

**Comment by mattttt** [comment]
There's a couple different ways we can go here. We can appropriate the Grafana home dashboard (or part of it), but then core grafana users will have a strange experience when adding litmus. In that particular scenario, I'm unsure if we could add something to their pre-existing home dashboard. 

A second scenario would be to add a Raintank Summary dashboard, which could include summary Litmus statistics like # of Up/Warning/Down endpoints, # of Online/Offline Collectors, and active tasks/warning/MOTD. 

Will sketch up some ideas, but it could provide a nice "Home" for Litmus concepts.

**Comment by mattttt** [comment]
Litmus Home Dashboard started in Pull Request #37. Needs to be made smart (to see if people have added endpoints/etc), and also linked to the proper pages.

**Comment by nopzor1200** [comment]
Initial version of this is live in tinyalpha; looks like a great start

**Comment by nopzor1200** [comment]
Will likely have to go with HTML panels instead of dashlist panels to link to raintank Dashboards (for now).

**Comment by nopzor1200** [comment]
trents working up a quick first pass of this. happen to have that mockup you did anywhere?

**Comment by nopzor1200** [comment]
related to raintank/grafana#47

**Comment by mattttt** [comment]
It'll be in the Capacity Google Drive/Raintank/UX/v1/Litmus-HomeDashboard.graffle

**Comment by bulletfactory** [comment]
Created HTML panel based on the content outlined. Saved dashboard as Home Copy, in portal.raintank.io - links added based on the staging server dashboards created.

**Comment by nopzor1200** [comment]
Looks like a great first stab. @woodsaj please deploy this!

**Comment by woodsaj** [comment]
@nopzor1200  happy for this to be closed now?

**Comment by nopzor1200** [comment]
Yeah, thanks @woodsaj
