### ISSUE TITLE
Endpoint Check: Auto-Update on Enable/Disable

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#100]
On the Endpoint Config tab, when the Endpoint Check is enabled/disabled, automatically update the state of the check on the backend and provide an in-app message to the user (in the upper right) stating "$Checktype Enabled Successfully" and "$Checktype Disabled Successfully".

I'd also like to better understand how errors are handled, when a timeout may occur, and how we communicate that to the user.

**Comment by bulletfactory** [comment]
successfully got monitor to update on checkbox click.

**Comment by mattttt** [comment]
Now we just need to update the success message (currently says, "Monitor Updated")

**Comment by woodsaj** [comment]
There is currently no way to suppress the current "monitor updated" message as this is produced by the backendSrv service.  Will need to talk to Torkel about the best way to handle this.

But i have commited a change that shows an additional message.

**Comment by mattttt** [comment]
Merged in Pull Request: https://github.com/raintank/grafana/pull/102

Still need to be able to change that text though.

**Comment by woodsaj** [comment]
@mattttt how does this look now?
http://128.199.88.198/ (this is running master)

**Comment by mattttt** [comment]
Beautious. Closing.
