### ISSUE TITLE
helper Text in New Endpoint

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#11]
When new Litmus users do not have any Endpoints added, it would be nice to give them some basic instructions on adding an Endpoint.

Here's some sample text that can be displayed if they don't have any Endpoints:

====

It looks like you don’t have any Endpoints yet.
 
Add an Endpoint to get started with raintank Litmus. An Endpoint can be anything you want to monitor.
 
When you add a domain name of your Endpoint, we will automatically detect what we can monitor (eg. PING, HTTP, HTTPS) and suggest a configuration that can be customized.

**Comment by mattttt** [comment]
Addressed in pull request #27.

**Comment by woodsaj** [comment]
merged.
