### ISSUE TITLE
adding health check & alert (==notification) details in check configuration, saving to db

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#110]
i'm now at a point where i'm finishing the alert scheduler and executor, i pushed my current code to https://github.com/Dieterbe/grafana/tree/litmus-alerting-v2 for reference.

specifically https://github.com/Dieterbe/grafana/blob/litmus-alerting-v2/pkg/alerting/schedule.go shows how we query the db with a `GetMonitorsQuery` and get a `MonitorDTO` back which has a new `HealthSettings` property which contains the "number of collectors" threshold and "how many points in a row" (steps). Currently i have no data in the database to play with these parameters.. and have to make some dummy assignments, see https://github.com/Dieterbe/grafana/blob/litmus-alerting-v2/pkg/alerting/schedule.go#L52-53 it would be great if we could actually manage the alerting settings so i can start testing the logic and such before i leave on vacation.

@mattttt how far are you with implementing the UX to manage/save these settings? any ETA?
@woodsaj would you mind helping out with the code that saves the config to the monitor.health_settings column? (in json) (we'll probably have to add two fields: email address destination for notifications, and notifications enable/disable)

thanks!

**Comment by mattttt** [comment]
Tracking front-end on Issue 122

**Comment by nopzor1200** [comment]
we think this is good to close, plz reopen if you think otherwise
