### ISSUE TITLE
bad "fill out this field" message for dns.be endpoint

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#118]
fresh devstack, running master.
I go to "new endpoint", fill in 'dns.be', hit autodiscover and click the "add endpoint" button.
2 problems:
* it claims I have to "please fill out this field". it's autodiscover, i shouldn't have to do anything.
* the notification bubble is incorrectly positioned.

nothing in javascript console.
what I did notice is 
```
2015/05/18 16:33:37 [T] auto-login cookie cleared: admin
PingHost:  dns.be
HTTPHost:  dns.be
failed to discover HTTP HTTP redirects to HTTPS
```

it looks like maybe some of the https fields didn't fill in correctly?

![thefuck](https://cloud.githubusercontent.com/assets/20774/7685449/640042dc-fd5c-11e4-8fca-82e0e005b0c5.png)
![context](https://cloud.githubusercontent.com/assets/20774/7685450/64215ddc-fd5c-11e4-8b7e-fb1cdab6f964.png)

**Comment by Dieterbe** [comment]
firefox on linux , btw

**Comment by mattttt** [comment]
Unable to replicate this on Firefox 31.0 on Ubuntu 14.04 LTS Desktop. 

Grabbing an updated imagine from Ubuntu to see if I can replicate. 

@Dieterbe Can you try again and see if it's still happening on the latest master?

**Comment by nopzor1200** [comment]
closing for now. @dieterbe if you can replicate plz reopen!

**Comment by Dieterbe** [comment]
cool works fine now (could only test on app. not dev stack but that's ok)
