### ISSUE TITLE
Improved Endpoint summary page

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#119]
(placeholder)

**Comment by nopzor1200** [comment]
- build out what we show on the checks
- have detail for specific collector status
- possibly detail for events

**Comment by bulletfactory** [comment]
* Change text from "9 hours ago" to "for 9 hours", "1 day ago" to "for 1 day", etc etc

**Comment by bulletfactory** [comment]
Agreed low hanging fruit for this:

* Accordian with detailed collector information per endpoint.check

**Comment by mattttt** [comment]
Fixed in mattttt_endpoint_list_13
