### ISSUE TITLE
New Endpoint

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#12]
Some of this will change with Matts new modals, but here are some small tweaks:

1) Change the text on the button from "New Endpoints" to "New Endpoint"

2) When adding a new Endpoint, change the description from "Site name" to "Domain name"

3) When adding a new Endpoint, don't show the "Summary" tab or the button to the Dashboard; neither are valid until the Endpoint is created.

**Comment by mattttt** [comment]
#1 address in mattttt-patch-tinylapha-2

**Comment by mattttt** [comment]
Addition of New Endpoint modal addresses #2 and #3 in Pull Request #37
