### ISSUE TITLE
Improve Collector summary page

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#120]
(placeholder)

**Comment by nopzor1200** [comment]
- expose events for collectors

**Comment by mattttt** [comment]
@woodsaj I'll be working on a front-end for this, but we do want to be able to get the [x] most recent events on this page.

**Comment by mattttt** [comment]
@woodsaj I forgot in one of the conversations with Raj, we wanted to try and use the iframe. Let me do that first and only think about making changes to the Litmus side if necessary.

**Comment by mattttt** [comment]
This is looking good for 0.13.

![collector-summary-loading](https://cloud.githubusercontent.com/assets/2886187/7759865/6a0c029a-ffe3-11e4-81b4-ff80f78c063e.gif)

Things to do
- Make iframe responsive (read a couple articles addressing it, dont know how to do it yet)
- Link to Event Dashboard somewhere (either within the iframe panel, or above it)

**Comment by woodsaj** [comment]
It is not possible to directly include the the events panel.  But we can replicate it easily enough. Committed into the collector_summary_events branch a basic approach. It shows the events for the collector from the last hour, limited to the last 10 events.

**Comment by mattttt** [comment]
What do you mean that it's not possible to include it? That gif is a functional pulling live data. 

That said, how is authentication handled? Obviously we wouldn't want to make that panel public for everyone.

**Comment by woodsaj** [comment]
i have no idea what you mean by pulling via an iframe. How are you able to pull just an iframe from the page? do you have this in a branch some where that has this code?

**Comment by mattttt** [comment]
@woodsaj Yep, it's in mattttt_endpoint_list_13

Got the embed code via the Share link on the dashboard:

![iframe](https://cloud.githubusercontent.com/assets/2886187/7772599/3999afec-006d-11e5-8a35-28e89d9c9a5f.gif)

**Comment by woodsaj** [comment]
ok. yeah that would work.  Authentication is necessary to view the embedded dashboard, so should just work seamlessly.

**Comment by mattttt** [comment]
@woodsaj: @nopzor1200 was going to get the Collector dashboard configured so I can update the iframe link, but I believe he had to split before getting that working. 

If we cant get that working before the upgrade tonight, then go ahead and comment out:
https://github.com/raintank/grafana/blob/mattttt_endpoint_list_13/public/plugins/raintank/features/partials/collectors_summary.html#L85

**Comment by mattttt** [comment]
With the addition of eventtest dashboard, we can re-implement this. Looking great.

**Comment by mattttt** [comment]
Added the All button to Endpoints using the regex values:

![screenshot 2015-06-05 14 15 38](https://cloud.githubusercontent.com/assets/2886187/8012197/683d89ba-0b8d-11e5-94f3-d387403f1a1e.png)

**Comment by woodsaj** [comment]
the iframe references a dashboard called. rt-collector-events.json  but this is not in master.

**Comment by nopzor1200** [comment]
Add event panel

**Comment by mattttt** [comment]
Picked up in Issue: https://github.com/raintank/grafana/issues/213

Closing this one .
