### ISSUE TITLE
Multiselect with Tags for dashboard templating

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#121]
(placeholder)

**Comment by torkelo** [comment]
with real queries. testable in rainktank-variable-dropdown branch 

![raintank_tags](https://cloud.githubusercontent.com/assets/10999/7957274/4b2138a2-09e6-11e5-9935-a30a4f9eee86.gif)

**Comment by nopzor1200** [comment]
In your example above are the tags (eg. America, Europe, Scandanavia) are coming from the series namespace itself, right? (would not be the case for Litmus, just want to make sure I understand)

**Comment by torkelo** [comment]
no they are coming from the raintank db collector tags table. 

It is via a graphite query that looks like "raintank_db.tags.collectors.*"  , this query is intercepted by the raintank-grafana backend and not issues to graphite but instead a the SQL database is queried.

**Comment by torkelo** [comment]
now "raintank_db.tags.endpoints.*" and "raintank.db.tags.endpoints.$tag.*"  should work also. 

The biggest challange remaining is how to handle when tags change over time. For example a tag is added to collector or removed and update the current variable values when dashboard loads.

**Comment by nopzor1200** [comment]
This is working for current purposes, will open sep issues for more stuff
