### ISSUE TITLE
Endpoint List: Include Current Check Health

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#123]

**Comment by mattttt** [comment]
Something like this?

![endpointlist-check](https://cloud.githubusercontent.com/assets/2886187/7691457/871c3fec-fd88-11e4-8e81-e0c379dc8f42.png)

**Comment by mattttt** [comment]
Early prototype of this working in mattttt_endpoint_list_13. 

@woodsaj Can you wire this up to angular tonight (controller related), and I'll finish this up tomorrow?

**Comment by mattttt** [comment]
Thanks @woodsaj

**Comment by mattttt** [comment]
Made a font size tweak, but otherwise looks good. Eventually going to link the health hearts to a dashboard (we believe), but going to leave them as informational atm.

**Comment by nopzor1200** [comment]
:clap big improvement over the numbers I think
