### ISSUE TITLE
move away from socket.io?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#124]
as per @woodsaj 
see #90 and #114

**Comment by Dieterbe** [comment]
i wonder if zeromq matches our needs

**Comment by Dieterbe** [comment]
what are our requirements? auto-reconnect? buffer data until (re)connected? automatic message en/de coding?

**Comment by woodsaj** [comment]
We need to stick with websockets as we want to ensure that the collector can run in as many environments as possible. This includes companies internal networks. As websockets are a layer on top of http they provide the best option as they will continue to work behind proxy servers and firewalls.

Auto-reconnect, buffering and encoding/decoding are important and are the features that soccket.io provided.  our use case is not complex, we just need to send and recieve messages between the collectors and the grafana backend.  We dont need any of the more advanced features of socket.io like broadcast messages and rooms.

the auto-reconnect and buffering features are required by the client only (collectors).  the nodejs `ws` package looks pretty reliable and should meet our needs. But we will need to write the auto-reconnect and buffering features into the app ourselves.

**Comment by nopzor1200** [comment]
if we rewrite the collectors in go, we need to move away from socketio. 

awoods _is_ seeing some weird issues in prod because of this - getting fake errors

**Comment by nopzor1200** [comment]
is having to move away from socketio a relatively big complication of rewriting the collectors in go? are there well known suitable alternatives?

**Comment by Dieterbe** [comment]
http://www.grpc.io/ this is getting buzz. a bunch of people were talking about it at gophercon
