### ISSUE TITLE
Alerting Email Design

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#125]
Structure, design and HTML/CSS for Alert Emails (and text-only)

**Comment by Dieterbe** [comment]
this may help https://github.com/mailgun/transactional-email-templates

**Comment by Dieterbe** [comment]
also we should make sure that the emails we send out have a proper html version as well as a plaintext version

**Comment by mattttt** [comment]
Also:

https://github.com/sendwithus/templates
https://www.sendwithus.com/resources/templates/about

**Comment by Dieterbe** [comment]
is anything still actionable for this ticket? what needs to happen here? @mattttt

**Comment by mattttt** [comment]
This was built and implemented in July. Stale ticket, just needs to be closed. We went with Zurb, fwiw.

Thanks!
