### ISSUE TITLE
alerting branch doesn't read telemetry configuration yet

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#127]
thought this would do it:
```
[telemetry]
statsd_enabled = true
statsd_addr = statsdaemon:8125
```
but was still getting `[setting.go:267 loadSpecifedConfigFile()] [E] Unknown config section telemetry defined in /etc/grafana/custom.ini)`

didn't spend too much time on this yet, might be obvious.

**Comment by woodsaj** [comment]
the telemetry section needed to be defined in defaults.ini

this has been fixed.

**Comment by Dieterbe** [comment]
ah that explains, thanks
