### ISSUE TITLE
weird nullpoint behavior moves points

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#129]
raintank grafana master, in dev stack.
just switching the nullpoint mode moves the points around.
null and null as zero look the same.
this is ping status with points instead of bars.

![null-connected](https://cloud.githubusercontent.com/assets/20774/7738422/1dcdbde0-ff22-11e4-80a3-b66cdca62dd0.png)
![null-null](https://cloud.githubusercontent.com/assets/20774/7738423/1dd4f6c8-ff22-11e4-925a-5964737d9be5.png)

actually as i hover, the timestamps stay the same but are no longer correct
like below, you can see the "hover timestamp" is actually past the tick on the x-axis, even though it has a lower time value?
![bad](https://cloud.githubusercontent.com/assets/20774/7738498/354c04a8-ff23-11e4-9840-d2cbd60aeb9f.png)

**Comment by nopzor1200** [comment]
anthony "thinks" this has been fixed. notating thinking here for if we reopen it :)
