### ISSUE TITLE
Dashboards incorrectly prompt to Save

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#13]
Currently whenever you edit the template variables in raintank Dashboards, and then try to navigate away from the Dashboard, you get the "Dashboard has changed" warning modal, even though there has been no changes to the Dashboard.

This likely needs to be a Grafana fix.

**Comment by nopzor1200** [comment]
@torkelo thinks that is an issue with the multi-variable template select functionality that we're using in raintank-grafana

This issue will be fixed before/when this functionality is merged back into mainline grafana

In the meantime, we will disable the warning for dashboards that are not editable (which the default raintank dashboards will be).

This will still be a problem for Litmus users who clone a raintank Dashboard with the intention to edit and customize it, but hopefully we can fix this permanently soon.

**Comment by nopzor1200** [comment]
I believe there's a change ready this warning for non editable dashboards?

**Comment by torkelo** [comment]
yea, the Editable false dashboards feature is done and in grafana master. Have also done a lot of polish and optimizations to panel repeat and row repeats (as well as fixes so repeated panels and rows are not included when checking for changes), the panel repeat features not yet merged to master but are in panel_repeat branch. Will work on the variable selection dropdown tomorrow (to enable search, and polish it)

**Comment by nopzor1200** [comment]
Awesome. 

So sounds like a permanent fix soon, but at the very least the warning won't show up for non editable Dashboards?

**Comment by torkelo** [comment]
Yes,  if raintank dashboards are mardröm editable  false then no unsaved warning check is done (as well as a lor of ui options and actions disabled or hidden)

**Comment by nopzor1200** [comment]
No longer warning when they are non editable (for raintank dashboards)
But still warning in a Saved (editable) dashboard (when the values in the multiselect dropdown are tweaked)

**Comment by torkelo** [comment]
@nopzor1200 should be fixed when the panel_repeat branch is merged into master and then into raintank master

**Comment by torkelo** [comment]
should be fixed in upstream master as of beginning of last week

**Comment by nopzor1200** [comment]
Looks all good now on staging. Thanks!

**Comment by Dieterbe** [comment]
neat!
