### ISSUE TITLE
0.13 Release blockers on Endpoint Edit/Config

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#136]
##### Radio Buttons
1. Fix default selected state on radio buttons. There is no current way to know which state they've selected (dynamic or static - which is a new concept).

Example: 
![raintank](https://cloud.githubusercontent.com/assets/2886187/7802184/a98d0888-02fe-11e5-8e8c-4fc0212810cd.png)

##### Enabled/Disable Checks

1. Change "[x] Enabled" check box to update on Form Submit rather than "On check/uncheck"

##### Collector Select Dropdown
1. Currently, to update the select box, you need to click away to submit. With the addition of an Update and Cancel button, clicking off the dropdown will act as  "Cancel". This may be debatable behavior, given how grafana does it, but I'd like to try it this way and see how it feels - then make a decision. 

Example:
![screenshot_2015-05-25_16_45_32](https://cloud.githubusercontent.com/assets/2886187/7802128/af44cadc-02fd-11e5-8dc3-9f1e6038b781.png)

2. Need a preview of the collectors being selected by the tags in the tag dropdown:

Example:
![raintank](https://cloud.githubusercontent.com/assets/2886187/7802265/34e21e36-0300-11e5-84f0-16a2f11962e7.png)

##### Wiring up individual form elements for each check. 

1. Every form label needs to be properly wired. I couldnt figure it out.

2. Need some logic in the partials to determine if the form calling it is endpoint_new or endpoint_edit. If on the New Endpoint screen, these update buttons will be suppressed. 

Example: 
![raintank](https://cloud.githubusercontent.com/assets/2886187/7802218/48a07478-02ff-11e5-9068-5dc8a1d8c3f5.png)

1. Compression of host, path and port into a single "Hostname" field for display, and parsing for edit. 

Example:
![raintank](https://cloud.githubusercontent.com/assets/2886187/7802155/257ab964-02fe-11e5-85ef-8aceab13843b.png)

Bonus points:

##### Collector Select Select Labels
1. Addition of logic to support showing "[first two tags, collectors] and [total minus 2] more" in the Collector select dropdown:

Example: 
![screenshot 2015-05-25 16 44 40](https://cloud.githubusercontent.com/assets/2886187/7802105/5fd22e72-02fd-11e5-9357-5a1bd1730d01.png)

**Comment by mattttt** [comment]
Issue handled previously in: https://github.com/raintank/grafana/issues/84

**Comment by woodsaj** [comment]
all of these have been addressed except for consolidating host,port,path into a single form element.

I dont like this at all, as it it allows the user to specify the protocol (http,https) which would be ignored. Additionally, all form elements are bound to attributes in the check data objects.  Having to bind to a intermediary object (url) and then re-mapping this out to the proper 3 attributes (host, port, path) when the check is saved leads to really hacky code.

If we want to show URL in the UI, then we should just store it as URL.  however this doesnt really work with two separate http and https check options.  We would need to drop down to a single http check that supports ssl. But then this would mean users could only monitor http or https and not both.

**Comment by mattttt** [comment]
All bugs have been squashed here. I'm good to merge with Master and go!

**Comment by woodsaj** [comment]
merged to master yesterday.
