### ISSUE TITLE
Unsaved Changes notice on Endpoint Config

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#137]
Similar to you leaving a dashboard without having saved your changes, I'd like to have Endpoint Config (and eventually collector config) notify you in a modal that there are unsaved changes, similar to the way grafana does when you exit an unsaved dashboard:

![screenshot 2015-05-28 23 11 38](https://cloud.githubusercontent.com/assets/2886187/7875741/ef2ac974-058e-11e5-9406-45a1e6e5ee29.png)

**Comment by mattttt** [comment]
@torkelo

**Comment by torkelo** [comment]
This dialog opens when clicking "Add Endpoint"  (as when I try create a new endpoint)

**Comment by torkelo** [comment]
@woodsaj trying to troubleshoot this looking through endpointConfCtrl.js (pretty messy code, LOTS of jshint violations, how does this pass builds?)

We really need CI build for the raintank code :)

**Comment by torkelo** [comment]
Hm, found it EndpointConfCtrl is created twice, it is refereed to once in the route and once in the markup.
