### ISSUE TITLE
Collector List language (configure, edit)

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#15]
In the elipses menu, you can "edit" a Collector but in the detail view, the tab says "Configuration".

Let's standardize on "configure" and "configuration" as what you do to a Collector, and make no mention to "edit" or "editing"

**Comment by mattttt** [comment]
Fixed in Pull Request mattttt-patch-tinyalpha-1

**Comment by nopzor1200** [comment]
Could you also do this on endpoint so it's consistent?

**Comment by mattttt** [comment]
Fixed in Pull Request #46
