### ISSUE TITLE
Litmus TinyAlpha Dashboard Audit

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#151]

**Comment by mattttt** [comment]
I know they're mostly coming together, but want to make sure are all uniform, and add in the missing ones where feasible. Also focusing on the way people will navigate around dashboard (drilldowns, etc).

**Comment by mattttt** [comment]
Started going through the dashboards, first aiming to organize the Dashboard Search & Sub-Navs with tags. 

Made some good headway, opened a Grafana issue (https://github.com/grafana/grafana/issues/2091).

![screenshot 2015-06-01 17 36 21](https://cloud.githubusercontent.com/assets/2886187/7923872/bbb0ec56-0884-11e5-838e-4f6c669fd271.png)

(1) Current schema I'm thinking is to tag all raintank dashboards as [raintank], and hard-code in the raintank blue for that unique hash. (not pictured above).This allows you to quickly filter the Dashboard Search by [raintank] and see all our dashboards. 

(2) Introduce have a second tag for the type of raintank dashboard, which will drive the menus:
- [endpoints]
- [collectors]
- [events]


(3) On the dashboard itself, the dropdown menu feels like the more effective style, especially as customer dashboards tagged as [endpoint] are added. This then leaves the challenge of making sure people know which Dashboard they're on (DNS, Ping, Web, Summary), as it doesnt feel immediately clear yet. More to come there.

**Comment by mattttt** [comment]
@woodsaj This is addressed in Grafana https://github.com/grafana/grafana/issues/2091. Can we grab upstream soon?

**Comment by nopzor1200** [comment]
Discussed some possible series naming changes with @woodsaj that will allow us to possibly consolidate our endpoint.http, endpoint.https, endpoint.dns, and endpoint.ping into one endpoint.performance dashboard

This might allow us to dramatically reduce the number of dashboards that we ship.

More to follow.

**Comment by nopzor1200** [comment]
notes:

possibly call the "default" response time value the same thing across all protocols (ie. maybe "responsetime" or something) rather different things per protocol (eg. total, mean, response)

network.dns.response = network.dns.responsetime
network.ping.mean = network.ping.responsetime
network.http.total = network.http.responsetime
network.https.total = network.https.responsetime

**Comment by nopzor1200** [comment]
rt-collector-summary now exists in tinyalpha

**Comment by mattttt** [comment]
@nopzor1200 rt-collector-summary is looking good. 

I like the idea of consolidating the dashboards a lot - submitted a pull request that kept the "per-check" dashboard structure for the moment, but if this works out, I'd love to consolidate to endpoint.performance.

**Comment by mattttt** [comment]
Grabbed the event panel from portal.raintank.io, but  forgot to push. Need to commit it tomorrow and push it.
