### ISSUE TITLE
Skeleton Pages during Load vs Bad Data

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#153]
When loading a page on slow connections, the first data being displayed in incorrect. For example on Endpoint Summary, even though all of the checks are all ONLINE and Enabled, they are shown to be 'Not Enabled' for a brief time. 

Instead of defaulting to this 'Not Enabled' state, we should show a blank space in the interface until we can provide accurate data. It's been referred to lately as Skeleton Pages (ref below). 

In lieu of showing a spinner, we can just make sure the page is properly blocked out with divs, and the content appears when it's available. 

Example:
![loading-example](https://cloud.githubusercontent.com/assets/2886187/7875782/bf16c426-058f-11e5-84d1-89fd83a91805.gif)

reference: 
http://www.lukew.com/ff/entry.asp?1797
https://github.com/ksux/ks-design-guide/issues/38

**Comment by mattttt** [comment]
Talked to @woodsaj about this on Monday. It's a fairly simple feature to implement, just adding in some awareness of what data needs to be received to make a page "ready". 

Let's start with these couple:

Endpoint List
- Currently: No Endpoints 
- Ready when: the first item is received or confirmed that there are 0 items. 

Individual Endpoint Summary
- Currently: As illustrated above
- Ready when: state is received for each check. Do we receive them piecemeal, or do all 4 come through at once?

**Comment by woodsaj** [comment]
Added scope variable for all endpoint pages (list, status and configuration).   

can be used with:

```
<div ng-if="pageReady">
  if they exist, endpoints/monitors will be loaded.
</div>
<div ng-if="!pageReady">
....loading
</div>
```

**Comment by mattttt** [comment]
Added loading states for endpoint list and endpoint summary. I'd like to merge these into master and see how they work with the Packet account before making any other adjustments. I think it's a solid start, but expect to refine it after real use. 

branch: mattttt-loading-states

**Comment by mattttt** [comment]
Merged into master: https://github.com/raintank/grafana/pull/175

**Comment by mattttt** [comment]
Updated messaging to be less dumb in Pull Request: https://github.com/raintank/grafana/pull/176

**Comment by mattttt** [comment]
This is in good shape for the moment. Closing now, and will reopen a new issue as we want to refine.
