### ISSUE TITLE
Collector Select - Frontend Styling Issues

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#154]
The collector select is experiencing some issues after switching the order of the fields a bit. It does not impact functionality, but definitely looks broken:

![collector-div-issue](https://cloud.githubusercontent.com/assets/2886187/7875880/ead85916-0590-11e5-825e-14f6b85226f2.gif)

**Comment by mattttt** [comment]
Also, scroll is not working in Safari:
![screenshot 2015-06-01 11 00 47](https://cloud.githubusercontent.com/assets/2886187/7915735/8c3c2d78-084d-11e5-9f7a-7fa77ba2df2c.png)

**Comment by mattttt** [comment]
I think both of these are best handled by Nick. @nchristus Do you have time some evening this week?

**Comment by woodsaj** [comment]
have these been fixed?  I noticed some CCS changes to set a min-width for the rt-form-long class which appears to have fixed this for me.

**Comment by mattttt** [comment]
Actually, after chatting with @nopzor1200 today, going to do a version that drops the update/cancel buttons entirely for the moment. We do still need to make sure it works and the search bar is fixed, but not that bottom div.

**Comment by mattttt** [comment]
This has been implemented and looking good. Closing.
