### ISSUE TITLE
Form Behavior

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#159]
There was a grafana issue a couple months back that suggested some form behavior. I'd like to pick this this up here for Litmus, iterating on form design as time allows. 

Areas to address:
- In-line validation
- Focus state helper text
- Optional vs Required
- Focus state vs error state behavior
- Error States
- [stub for additional]

**Comment by nopzor1200** [comment]
suggest closing this and opening individual issues for each area as needed? (but not immediately)
