### ISSUE TITLE
Initial dashboard creation

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#17]
Need initial versions of the following Dashboards created. These will be the "stock" (and non editable) Dashboards that will ship with Litmus.

·      Endpoint Summary (attempted)
·      Endpoint DNS (attempted)
·      Endpoint PING (attempted)
·      Endpoint WEB (attempted)
·      Collector Summary
·      Collector DNS
·      Collector PING
·      Collector WEB
·      Events

**Comment by nopzor1200** [comment]
Updated dashboards in our staging server:

rt2-endpoint-summary
rt2-endpoint-ping
rt2-endpoint-dns
rt2-endpoint-web

Please make these the latest default Litmus dashboards

**Comment by woodsaj** [comment]
dashboards committed and published to tinyAlpha

**Comment by woodsaj** [comment]
i notice that the for all dashboards, the errors panel needs
1) in display styles set 'stacked values' to individual
2) in axis & grid, set the left-y axis min to 0

**Comment by nopzor1200** [comment]
The following fixes have been made to the following Dashboards in staging:

1) rt-endpoint-summary
2) rt-endpoint-ping 
3) rt-endpoint-dns
3) rt-endpoint-web

Changes made.

- Detailed performance panel: Only show avg and current in detailed graphs [do not have show min & max & avg & total on the same legend, will be very misleading values. max, min and avg cannot be correct at the same time. This is one thing I want graphite, influxdb and opentsdb to implement (so that it returns series summary data, like max, min, avg, total, values that are calculated before being consolidated down the the amount of values grafana wants)] (thx @torkelo)

- Error bar: error bar label should be called status bar or something else since we are showing errors, warning, ok (not just errors) (thx @bulletfactory)

- Summary percentage panels: bad/useless height specified on singlestat panels in summary (thx @torkelo)

- Status panel: Y axis set to 0 for all of these panels (thx @woodsaj)

- Status panel: Stacked values set to individual for all panels (thx @woodsaj)

**Comment by nopzor1200** [comment]
Closing this for now. Will open separate ticket for Collector dashboards
