### ISSUE TITLE
raintank tags in raintank blue (tm)

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#172]
In tag lists, any raintank tanks should use our reserved blue. This should go for collector tags, endpoint tags and dashboard tags:

Ideally using the LESS variable: @rt-blue 

For reference, it's rgb(19,178,212);

Trying to find this now myself, but wanted to start the issue.

**Comment by mattttt** [comment]
I got as far as here: https://github.com/raintank/grafana/blob/master/public/app/controllers/search.js#L126

but dont know how to get the hash for raintank and put the if statement together.

**Comment by mattttt** [comment]
Related to: https://github.com/raintank/grafana/issues/151#issuecomment-107720903

**Comment by mattttt** [comment]
@torkelo Any chance you can sneak this in tomorrow?

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/8124703/c820a744-10de-11e5-8f81-93bf88926370.png)

**Comment by mattttt** [comment]
thanks @torkelo, looks great.
