### ISSUE TITLE
Access to Litmus data within a dashboard panel

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#178]
I'd like to have conditional Call To Actions on the Litmus Home Dashboard - so we can better direct the user on next steps. 

For example, if there are no endpoints, this is the biggest focus of Litmus:
![grafana_-_home](https://cloud.githubusercontent.com/assets/2886187/8039688/7e581a32-0dd9-11e5-9af6-adf79e4a5578.png)

But once an endpoint is created, I'd like us to show the next most important thing. 

How can we accomplish this?

**Comment by mattttt** [comment]
Same as https://github.com/raintank/grafana/issues/171#issuecomment-111551391

**Comment by torkelo** [comment]
I think this needs to be a custom panel

**Comment by nopzor1200** [comment]
So we want to create a custom panel to help drive user flow once they log in.

Currently we have some dumb HTML in the Home Dashboard asking the user to do various stuff (eg. add endpoint, add users, add collector, etc etc).

We would like to replace this with a single custom panel that is a bit smarter, and helps us control behavior based on what is _actually going on_ in the Org.

The custom panel will check certain conditions about the Org and based on what it finds display particular html/partial in the panel.

It is OK if the logic is hard coded into the panel. It is important that @matttt be able to edit and control the output/partials that the panel displays.

*** Explanation ***

If they don't have an endpoint, the panel should direct them to add an endpoint
If they have an endpoint, but dont have any additional users, the panel should direct them to invite their team
If they have an endpoint, have an additional user, the panel should direct them to add a private collector

*** Pseudologic ***

If (org_endpoint_count == 0) show ("add endpoint"); exit; // first thing we show if no endpoints
If (org_user_count = 1) show ("invite colleague"); exit; // have endpoint but no users, ask them to invite
If (private_collector_count = 0) show "add private collector"; exit; // have endpoint and a user, ask them to add private collector

**Comment by woodsaj** [comment]
This is quite straight forward.  And the new quota support makes it quite easy to query the data as the /api/quotas call returns the limit and used counts of each of endpoints, users, collectors etc..

**Comment by nopzor1200** [comment]
Awesome can you try working it up? I think the v1 plan is to consolidate some of the static Call to Actions on the Home Dashboard into 1 smart panel.

**Comment by woodsaj** [comment]
@mattttt panel added to home_dash_panel branch.
let me know what you think.

Panel HTML is in public/plugins/raintank/panels/raintankCallToAction/module.html

**Comment by mattttt** [comment]
Excellent - will work on this next week.

**Comment by mattttt** [comment]
Pulled the branch, looks great. Took a bit longer than anticipated going through a number of variations, but I think this is by far the best version. Code-wise will be extremely simple to implement, and I think is a much more focused version of our landing page. 

### Now:
![dashboard-home-cta-now](https://cloud.githubusercontent.com/assets/2886187/9029860/6684a942-3968-11e5-8e36-a67560a9191c.png)

### After we have email validation:
![dashboard-home-cta](https://cloud.githubusercontent.com/assets/2886187/9029863/6a5cc766-3968-11e5-92c8-fda741c00d80.png)

### 100% Complete State

This needs to be done, but I want it to be a reserved space for Common Help questions & timely notifications (until we've got something more firm in place elsewhere)

**Comment by bulletfactory** [comment]
Visually slick and helpful. A good place to teach people to look for answers

**Comment by Dieterbe** [comment]
looks nice.  but what happens if there is only one person in the org that deals with website availability and there isn't really anyone else for them to add?
does our logic deal with this and suggest something else that is more relevant to them or will it keep saying "invite a new team member" ?

**Comment by woodsaj** [comment]
we could use local browser storage to allow users to skip steps.

**Comment by mattttt** [comment]
@nopzor1200 and I chatted about this a bit. Going to implement it initially without the progress indicator while we think about how we want to extend that. Without it, we wont need any backend changes yet.

**Comment by mattttt** [comment]
Bah, just realizing we dont split up first name and last name currently, but we do ask for it in the future (I think). Will revisit that at a later time.

**Comment by nopzor1200** [comment]
Looks good @mattttt, would love to see an initial iteration of this up there.

**Comment by mattttt** [comment]
Yep, trying to bang out a few other outstanding items and then move back to this.

**Comment by mattttt** [comment]
Merging into master to do some user testing. It looks like this right now.

<img width="1199" alt="screenshot 2015-08-11 22 48 37" src="https://cloud.githubusercontent.com/assets/2886187/9215635/299b3f54-407b-11e5-9199-b7553a73ba48.png">


Known issues: 

1. Non-retina screens, the check mark icon is too thin. @bulletfactory needs to address this. 

2. At 1010px wide with sidemenu open, and 814px wide with sidemenu closed, the Welcome box starts to look pretty poor. This can easily be fixed, just needs some more time/love:

<img width="280" alt="screenshot 2015-08-11 22 46 33" src="https://cloud.githubusercontent.com/assets/2886187/9215629/03acb066-407b-11e5-8650-1affdf1d2f47.png">
<img width="240" alt="screenshot 2015-08-11 22 46 27" src="https://cloud.githubusercontent.com/assets/2886187/9215628/03aaea9c-407b-11e5-9166-3ab16c308144.png">
