### ISSUE TITLE
Dashboard-based navigation between "related" dashboards

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#18]
This was discussed before and during the summit. 

We need a way to provide navigation to related dashboards without having to go to the big Dashboard picker. When we distribute bundles of related dashboards, this becomes very necessary (as it is for Litmus).

This has been requested a few times within the Grafana community.

Possibility of links in top bar? https://github.com/grafana/grafana/issues/572

Navigation Panel Type https://github.com/grafana/grafana/issues/517

Table of Contents and hierarchy for nav https://github.com/grafana/grafana/issues/1378

Linked dashboards: https://github.com/grafana/grafana/issues/1617

How should we do this?

Interim plan vs long term? HTML panel with static links?

**Comment by nopzor1200** [comment]
I talked to Matt about this more last week. Really starting to believe that Dashboard grouping and Dashboard navigation are very related.

In the interim for 0.1, we have a static HTML panel that links to related Dashboards with URL parameters for endpoint and collector (eg. &var-endpoint=xyz, etc).

**Comment by torkelo** [comment]
Merged this feature to master
https://github.com/grafana/grafana/issues/1944

Until I make search more pluggable so raintank dashboards can be included in them, I think the manual links in https://github.com/grafana/grafana/issues/1944  feature should be flexible enough.

Specify a url like "dashboard/raintank/rt-endpoint-summary" and enable "include current time range" and "include current template variables".

**Comment by nopzor1200** [comment]
Looks like a really good start @torkelo. I think we'll want to avail ourselves of putting links to docs/help in there for now too, which you've allowed for.

Eager to play around with it, so we can comment further and iterate.

Manual links should work fine for beta, although the pluggable search problem needs to be urgently addressed because it is presumably the way we solve #47, which is a huge usability issue. There are other ways of solving #47 in the interim though.

**Comment by nopzor1200** [comment]
If we use #1944 with manual links, is there any way for the current dashboard link to visually show up?

(eg. in tinyalpha we make the current "subnav" bigger on each dashboard to reinforce which one you are on. With @mattttt  mockup he had an underline similar to the way it's used elsewhere in Grafana). 

Is there any way to accomplish this with the current feature?

**Comment by nopzor1200** [comment]
Looks like a great start torkel, played around for 20 minutes so far, Tag pulldowns are pretty cool but not sure if our raintank dashboards can have tags. Will review and open another issue for feedback
