### ISSUE TITLE
New Endpoint: Auto-discover skip

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#182]
If you check out my branch new-endpoint-autodiscover, we've split up the New Endpoint into two steps on the same page, and the interface forces auto-discover as the only CTA initially. 

If auto-discover is failing for some reason, we dont want to impede a manual entry, so I'd like to introduce a link (during the "Autodiscover in progress" message) that lets them skip the auto-discover and manually create the endpoint. 

I presume it'll be an alternate version of  <div ng-show="discovered">, but dont know how to accomplish it in angular.

**Comment by woodsaj** [comment]
merged into master.
