### ISSUE TITLE
panel-based navigation

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#19]
Many dashboards will show summaries of a particular endpoint or collection, it is important that users are able to click a panel to go to another dashboard / set template variables.

For Litmus, we want to be able to navigate to a given Dashboard with a given set of template variables by clicking on a particular panel.

This feature has already been discussed at length by the Grafana community, and some functionality exists within Grafana to help accomplish it:

links to other dashboards https://github.com/grafana/grafana/issues/1041

Make Drill­down easier https://github.com/grafana/grafana/issues/1575

Whole panel clickable https://github.com/grafana/grafana/issues/1377

Drilldown graph link https://github.com/grafana/grafana/issues/1232

**Comment by nopzor1200** [comment]
Being discussed again in grafana#1797

The requirement for Litmus can be implemented in numerous ways (including some in the original issue post)

**Comment by torkelo** [comment]
how important is this for litmus beta? How should it work?

**Comment by nopzor1200** [comment]
Out of all the issues that kind of address this I personally like grafana#1232

**Comment by nopzor1200** [comment]
So, we discovered that this feature pretty much already existed in Grafana. @torkelo fixed it so that it would work with file based dashboards (like the picker now does) and now we just need to edit dashboard(s) to take advantage of it. Sound right @mattttt? If so close this out

**Comment by nopzor1200** [comment]
This was working-ish when playing around with it on dev-portal

There's basically no hit area on anything but the single stat panel. 

My asks:

1) The icon be more prominent or a different color
2) If you click on the icon itself you should be taken to the link

In the meantime I think we should roll forward as-is

**Comment by mattttt** [comment]
This will need to be addressed as a grafana enhancement - will need to pop a ticket over there with ideas/discussion on how to improve.

**Comment by torkelo** [comment]
There doesnt appear to be any concrete idea/mockup for this issue. Just links to a few navigation related grafana issues. Maybe we should try to identify a few concrete things and turn them into issues?

**Comment by mattttt** [comment]
Agreed - I'm going to close out this ticket and create some tickets on the grafana side. It feels like a much larger issue of navigation between groups of dashboards (I know I sound like a broken record at this point). Litmus is *an* example of a group of dashboards, but it's just as appropriate for any organization that has a Summary -> Detail 1 -> Sub-detail 1 situation.
