### ISSUE TITLE
Events on Endpoint Detail Dashboards

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#193]
Ref: On staging under the jneuser account: /dashboard/db/endpoints-dns-copy

The current event panel seem reliant on dashboard variables that do not appear in Endpoint Detail dashboards, therefor we cant do a small version of the events. 

@woodsaj What would we do in this case?

**Comment by nopzor1200** [comment]
We should be able to hardcode these variables for the event panel in cases where there isn't the appropriate pulldown
