### ISSUE TITLE
Tag Colors not rendering properly

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#196]
tag-color-from-name is being included, but the colors stopped rendering sometime recently. It's working on portal.raintank.io, but not on staging. Currently broken on both endpoint list and collector list, but working on dashboard search. 

![screenshot 2015-06-12 14 13 00](https://cloud.githubusercontent.com/assets/2886187/8136896/9863185a-110d-11e5-87cc-c34967b299c7.png)

**Comment by woodsaj** [comment]
fixed in https://github.com/raintank/grafana/commit/59c6a05b02e3a7861b1ebbd1aa6433ce3b234dcd
