### ISSUE TITLE
map panel

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#20]
We need to create a map panel to support map functionality around Collectors, both in the Litmus pages as well as the Grafana Dashboards.

Ideally this can be accomplished as a stock Grafana panel, and can be used in an embedded manner in necessary Litmus pages.

Requirements of the map:

- Autowindow/autozoom based on the items selected (ie. smart enough to show the world for listing all collectors, but zooming into Europe for EMEA, down to showing New York metro for someone looking at a hypothetical "NYC" tag, etc etc)

- Be able to represent 1-5 values on each item in the map (either as a color shade, dots, etc etc), alongside annotations or notes

- Make sure its consistent with our look and feel

- Ideally not dependent on external accounts / costs

**Comment by nopzor1200** [comment]
This has also been discussed within the Grafana community before:

https://github.com/grafana/grafana/issues/1088

https://github.com/grafana/grafana/issues/1520

**Comment by nopzor1200** [comment]
Perhaps in the interim we should change the map graphic in Collectors List to indicate where our default public Collectors are. Thoughts?

**Comment by bulletfactory** [comment]
I like that- a static graphic until we get the live map solution worked out.

T

**Comment by nopzor1200** [comment]
Static map up on 0.10-pre

**Comment by torkelo** [comment]
I can't really give an ETA on this, I would expect this to take a couple of days at least or more than a week. And my feeling is that there are more important things to work on.

**Comment by mattttt** [comment]
Some updates since we chatted:
Torkel did some testing in codepen with: http://codepen.io/awilbert/pen/wAGLp

Also, here's an explainer that we had kicked around internally on how the stack fits together:
http://www.sarasafavi.com/making-a-web-map-with-leaflet.html

**Comment by nopzor1200** [comment]
Still would be a big win for certain components.

**Comment by nopzor1200** [comment]
Just pinging on here because I want to talk about this and get a strategy together. I still feel this is something that's important to drive Litmus adoption.

I think that it gets more interesting with the Elasticsearch datasource, too.
