### ISSUE TITLE
Litmus Event Dashboard - No Events

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#218]
The event dashboard (dashboard/file/rt-events.json) was functioning in testing earlier this week, but now is returning no events. 

![screenshot 2015-06-19 11 04 35](https://cloud.githubusercontent.com/assets/2886187/8256201/4a2758de-1673-11e5-9740-68692c24f858.png)

**Comment by Dieterbe** [comment]
also noticed this yesterday, we're supposed to be able to just import the dashboard from the json file in the code , and that should be it, right?

**Comment by nopzor1200** [comment]
fixed from the old network.* namespace to the litmus.* namespace
now working in newevents

**Comment by nopzor1200** [comment]
this is all working but the event panel needs regex for multiple values not graphite style globs

so the big limitation we have is we cant combine the event panel with other panels in a single dashboard currently. closing this out for now
