### ISSUE TITLE
Too many protocols in Litmus Endpoint: |--- Web Dashboard

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#220]
The protocol dropdown for the web dashboard has all available protocols (ping, dns, http, and https). Instead, it should just have HTTP and HTTPS.

![screenshot 2015-06-19 13 30 46](https://cloud.githubusercontent.com/assets/2886187/8259046/9bc1cc24-1687-11e5-8d37-786b58986605.png)

**Comment by nopzor1200** [comment]
This is fixed on newweb

**Comment by Dieterbe** [comment]
what is newweb?

**Comment by nopzor1200** [comment]
it was fixed by changing the query for the template to litmus.$endpoint.$collector.{http,https} instead of litmus.$endpoint.$collector.*

This will limit the web dash to http and https pending their availability in the metric tree

newweb is the new versions of the dashboards that matt is pushing
