### ISSUE TITLE
Link Endpoint Event Count to Event Dashboard

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#221]
![screenshot 2015-06-19 14 24 23](https://cloud.githubusercontent.com/assets/2886187/8259998/e6dff238-168e-11e5-8098-b91c94fa1780.png)

When the user clicks the numbers in OK, Warn and Error, link to the Event Dashboard with $endpoint, $monitor_type and $severity pre-filled.

**Comment by mattttt** [comment]
Implemented on Friday in PR https://github.com/raintank/grafana/pull/227, but still seeing some issues.

**Comment by nopzor1200** [comment]
Needs event panel

**Comment by nopzor1200** [comment]
Only link numbers for Errors to the Event Dashboard

**Comment by nopzor1200** [comment]
Remove warn text
Make sure unknown is showing up

**Comment by mattttt** [comment]
This is looked good on dev-portal. 

Warn has been removed, and unknown counts are being properly calcul
![screenshot 2015-06-26 17 16 17](https://cloud.githubusercontent.com/assets/2886187/8388380/1efbd572-1c27-11e5-8275-df41b2901dc9.png)
ated:
