### ISSUE TITLE
Endpoint Status: Individual Check 

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#223]
(Picked up from Issue https://github.com/raintank/grafana/issues/119)

Addition of a per-check accordion to show check status on a per-collector basis. Ideally this will include a map as well (down the road). 

![fullsizerender 2](https://cloud.githubusercontent.com/assets/2886187/8261382/2cd93af2-1698-11e5-8b55-b96a3aca580a.jpg)

Open question: What else do we want to show?

**Comment by nopzor1200** [comment]
Collector Name | Last Status | Last Measurement
Amsterdam | OK | 456ms

The way I'm thinking of it i'd basically be a table.
Would be good to be able to sort by each heading.
