### ISSUE TITLE
Delete Endpoint (backend)

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#224]
Do the needful to delete the endpoint and all data points in the backend.

**Comment by mattttt** [comment]
@nopzor1200 this is the backend ticket. What do I need to do here? (front-end ticket is #225)

**Comment by woodsaj** [comment]
Deleting an endpoint will delete from the DB and emit an event that the endpoint has been deleted.

we need to process that event and do the following:

1) delete from elasticsearch. This should be done after 5minutes to ensure that no lingering metrics from collectors come in as these will cause the elasticsearch data to be re-created.  Once the elasticsearch data is deleted, users wont see any trace of the endpoint via graphite.
2) delete the data from cassandra.  The data will just get marked for deletion by wont be removed from disk for a while.  http://docs.datastax.com/en/cassandra/2.0/cassandra/dml/dml_about_deletes_c.html

**Comment by Dieterbe** [comment]
> 1) delete from elasticsearch. This should be done after 5minutes to ensure that no lingering metrics from collectors come in as these will cause the elasticsearch data to be re-created. Once the elasticsearch data is deleted, users wont see any trace of the endpoint via graphite.

is that robust? aren't there scenarios like when the collector can't temporarily send metrics, where it might send metrics more than 5 minutes after the fact? or maybe an other part of the pipeline backs up, like the inbound queue in grafana
