### ISSUE TITLE
Delete Endpoint (frontend)

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#225]
Currently the only way to delete an Endpoint is through the endpoint list view. Add an additional configuration box for more general settings at the bottom, which will include a big red button that lets someone delete the endpoint. 

On click, they will be shown a modal that will explain the gravity of deleting an endpoint, and making them confirm deletion by typing DELETE. 

![photo jun 19 2 23 58 pm](https://cloud.githubusercontent.com/assets/2886187/8433550/2fdc8160-1f0c-11e5-89dc-a65ff56218cd.jpg)

Related: Issue https://github.com/raintank/grafana/issues/224, Delete Endpoint (backend)

**Comment by mattttt** [comment]
Working on this now.

**Comment by mattttt** [comment]
Working on a couple different options (both done in code). Almost there. 

<img width="1183" alt="screenshot 2015-11-03 11 19 59" src="https://cloud.githubusercontent.com/assets/2886187/10913656/ded52ea6-821c-11e5-8fcc-75f5bd14d1ec.png">

<img width="1212" alt="screenshot 2015-11-03 11 04 20" src="https://cloud.githubusercontent.com/assets/2886187/10913626/bc541162-821c-11e5-90d5-4e4cd68b6a61.png">

With the *big red button* option, we'll need to trigger a modal to say "Are you sure???".

**Comment by mattttt** [comment]
getting a js error on delete, also. Need to troubleshoot (probably with @woodsaj)

<img width="893" alt="screenshot 2015-11-03 11 29 42" src="https://cloud.githubusercontent.com/assets/2886187/10913955/3158504e-821e-11e5-94f1-bc2d1d8164ff.png">

Also, currently the Destroy box is loading first and then the check boxes load into place. I'd like to have the destroy box load last, after the check boxes appear. Destroy is a strong word to blink subliminally at someone. :imp:

**Comment by Dieterbe** [comment]
@mattttt i like the design of the 2nd one, the all-red one. though perhaps it's maybe a bit too strong of a red.
the difference in style with the other button, the blue one, on that screenshot does hurt my eyes a bit though. but i notice we have 2 styles of blue buttons too, the "framed" variety as on that screenie, as well as a "full" variety (see "New endpoint" button).
maybe we should uniformize our button styles to be all "full" ones, and no more framed ones. though the red could maybe be a bit softer of color.

**Comment by bulletfactory** [comment]
I feel strongly that have 2-3 button styles is necessary to properly convey
hierarchy of importance. PrimaryCTA, SecondaryCTA, TertiaryCTA. This is
even more important when we're using a small, reserved palette of color for
buttons and UI elements. While I'm all for tweaking specific colors (ie: if
the red is blinding you), I think the 2 different main button styles are
effective.

**Comment by mattttt** [comment]
Thanks for the feedback, actively working on this.  Let's not appropriate this ticket to start redoing button styles system-wide. 

Im adding a new smaller filled in-style (red outlined button readability is too low). I'm using our rt-red variable, which is effective on the hearts, but maybe we need a variant for buttons. Will get this looking good and then we can introduce a new red variable if we think it's necessary.

For those playing along at home, current state:
<img width="1033" alt="screenshot 2015-11-03 12 09 54" src="https://cloud.githubusercontent.com/assets/2886187/10915228/d4c66ad6-8223-11e5-81a3-cf99b1afd564.png">

**Comment by mattttt** [comment]
This is looking close to done on `https://github.com/raintank/grafana/tree/delete-endpoint`, but needs to get the deleting functionality working. Can you help with this, @woodsaj ?

**Comment by woodsaj** [comment]
@matt deletes work fine for me in this branch.  I did just push a commit to redirect to the endpoint_list page after deleting.

If you still have errors can you also include the grafana logs when the delete fails.

**Comment by mattttt** [comment]
Styles are all functional and ready to go, but cant get the endpoint to delete properly. Will include Grafana log when I get home.

<img width="512" alt="screenshot_2015-11-06_09 11 39_1024" src="https://cloud.githubusercontent.com/assets/2886187/11011052/71a613de-84b2-11e5-902d-27bf01ab3de5.png">

**Comment by woodsaj** [comment]
this works in production.
