### ISSUE TITLE
Periodic 'permission denied'

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#23]
I consistently get periodic 'permission denied' with navigating around the current staging server.

Reloading causes it to go away, but it is definitely an annoyance.

This isn't a one-off issue as it's happening both at home on Windows/Chrome and at work on OSX/Chrome. @mattttt also said this has been happening to him periodically.

**Comment by nopzor1200** [comment]
@woodsaj confirms he's seen this issue too. he thinks it happens when the app is idle but I seem to be able to reproduce it quite consistently just bouncing around endpoints/collectors

**Comment by woodsaj** [comment]
This looks to be an issue with the macaron-contrib/session library.  
Looks like some kind of race condition is resulting in the session file being truncated.

**Comment by woodsaj** [comment]
opened an issue in macaron-contrib/session

https://github.com/macaron-contrib/session/issues/7

**Comment by nopzor1200** [comment]
Although the root problem is still unresolved per @woodsaj, the symptoms are now practically non existent now that the staging environment has been minified

**Comment by nopzor1200** [comment]
I haven't run into this in a while. Is it still a known bug?

**Comment by nopzor1200** [comment]
I've heard _sporadic_ reports of this _occasionally_ happening to people.

**Comment by bulletfactory** [comment]
Closing out for now. Rumor has it this isn't happening to anyone. As soon as we hear of it rearing its ugly head we'll reopen
