### ISSUE TITLE
Colors choice: Endpoint Ping Dashboard

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#231]
I'm going to add one comment per color, +1 the ones you think are most effective.

**Comment by mattttt** [comment]
![screenshot 2015-06-22 11 52 05](https://cloud.githubusercontent.com/assets/2886187/8286161/0c2b41f2-18d6-11e5-8e7c-c4a61260b8db.png)

**Comment by mattttt** [comment]
![screenshot 2015-06-22 11 52 42](https://cloud.githubusercontent.com/assets/2886187/8286168/111e2742-18d6-11e5-872a-f292271208d0.png)

**Comment by mattttt** [comment]
![screenshot 2015-06-22 11 53 42](https://cloud.githubusercontent.com/assets/2886187/8286172/14f9d834-18d6-11e5-94dc-ccefc4bdba69.png)

**Comment by mattttt** [comment]
![screenshot 2015-06-22 11 54 24](https://cloud.githubusercontent.com/assets/2886187/8286177/18e69a7c-18d6-11e5-8140-f34961dbe76c.png)

**Comment by mattttt** [comment]
![screenshot 2015-06-22 11 55 42](https://cloud.githubusercontent.com/assets/2886187/8286185/22e6c3e4-18d6-11e5-926e-df2a273c6dd4.png)

**Comment by mattttt** [comment]
![screenshot 2015-06-22 11 56 16](https://cloud.githubusercontent.com/assets/2886187/8286192/289b09b2-18d6-11e5-8af0-0d13ad3c66a2.png)

**Comment by mattttt** [comment]
![screenshot 2015-06-22 11 56 39](https://cloud.githubusercontent.com/assets/2886187/8286197/2e7764e8-18d6-11e5-8444-8e7f373e9ad3.png)

**Comment by mattttt** [comment]
![screenshot 2015-06-22 11 57 01](https://cloud.githubusercontent.com/assets/2886187/8286201/33366d26-18d6-11e5-8c25-71637d4b429b.png)

**Comment by bulletfactory** [comment]
I +1'd inline - but to expand a bit, i think we have some nice choices in the last 4. 

The very last one [light blue] might be a tad less-desirable on light theme, but still works/looks nice. 

The purple stands out well on both themes, and am also a fan of the darker orange.

The second to last blue/grey combo looks pretty sophisticated.

**Comment by Dieterbe** [comment]
we should also take into account color blindness issues. datadog had a designer take that into account for their dashboards, resulting in their use of a particular set of colors, (mostl shades of purple IIRC)

**Comment by mattttt** [comment]
Good call dieter.

**Comment by mattttt** [comment]
Went through and checked these through a simulator for Protanopia (no red cones; red-green color blindness), Deuteranopia (no green cones, red-green cb) and Tritanopia (no blue cones, blue-yellow cb) and all looked good except the last. 

Commenting it out of the running.

**Comment by mattttt** [comment]
We decided to go with this one, because it offered the best contrast (and support for color blindness) with the loss 'red', which we wanted to remain red. 

![screenshot 2015-06-22 11 56 39](https://cloud.githubusercontent.com/assets/2886187/8286197/2e7764e8-18d6-11e5-8444-8e7f373e9ad3.png)


Closing.
