### ISSUE TITLE
tooltip on endpoint list always says "disabled"

### ISSUE THREAD

**Issue by bulletfactory** [raintank/grafana#232]
Hovering on any of the health indicators shows a tooltip that says "disabled"
![screenshot 2015-06-22 16 37 23](https://cloud.githubusercontent.com/assets/1950595/8292345/318a0394-18fd-11e5-9823-6c95023d0df1.png)

**Comment by nopzor1200** [comment]
Matt is going to:

1) Remove tooltip status
2) Link to dashboard

Long term fix:

1) Matt can have one of our contractors look at it.

**Comment by mattttt** [comment]
for Long term fix?: https://stackoverflow.com/questions/9501921/change-twitter-bootstrap-tooltip-content-on-click

**Comment by mattttt** [comment]
Removed tooltips in PR https://github.com/raintank/grafana/pull/240

Didnt link to dashboard yet for this reason:
(1) If you click on the heart, I think you expect to see that heart reinforced in the link destination
(2) But the ping dashboard doesnt yet show the Current Health. 

So I propose we link this as soon as we implement the current health single-stat panel.

**Comment by mattttt** [comment]
Short term fixes in PR: https://github.com/raintank/grafana/pull/242

- Entire row is now clickable (sans Jump to Dashboard and "more dots"), and will go into the Endpoint Summary.

**Comment by mattttt** [comment]
So for 0.15 milestone, this is done.

**Comment by mattttt** [comment]
Reference video: https://www.youtube.com/watch?v=jKBMRlAacAs

**Comment by mattttt** [comment]
Still working on getting Patrick going with his build - no progress made yet.

**Comment by mattttt** [comment]
Poked patrick, dont believe he's set up yet.

**Comment by mattttt** [comment]
@reduxdj is all set up and I ran through the issue with him. He will update tomorrow/Thursday on progress.

**Comment by mattttt** [comment]
@reduxdj did some awesome work, submitted PR https://github.com/raintank/grafana/pull/286 for review.

**Comment by mattttt** [comment]
PR has been merged into master.
