### ISSUE TITLE
alerting doesn't work against graphite on non-default port

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#236]
see comment at https://github.com/raintank/grafana/commit/c52e75f480ab0e37b2843c9858895cf0e3de1964

**Comment by woodsaj** [comment]
as per my reply to your comment, the port should already be getting passed through.  Have you seen it behaving differently?

**Comment by Dieterbe** [comment]
you're right, the port bug didn't exist.

I did just push some improvements:
* updated bosun upstream to take in custom path
* updated godep for bosun
* changed our code to pass in the URL instead of host:port so bosun can see the custom scheme, proto.
