### ISSUE TITLE
issues creating new endpoint. no data, claims "disabled", etc.

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#238]
created an endpoint for metrics20.org on my account. i used discovery and enabled ping, dns and http monitoring. all at 10s res.
1. however, in the endpoint status panel,
all protocols (minus https) just say "nodata for 5 minutes.. OK:  --
Warn:  --
Error:  --
Unknown:  --
"
why is no new data showing up??

2. in the endpoints overview, it shows like so:
![rxf1rpg](https://cloud.githubusercontent.com/assets/20774/8299882/42028440-1933-11e5-993f-5ecec6570787.png)
hovering over all the hearts, shows "disabled" for all protocols. why?

**Comment by nopzor1200** [comment]
I assume if you reload say 10 seconds later you start to see stuff, right? (ie. this is really a problem after initial endpoint creation)

**Comment by Dieterbe** [comment]
nope.  waited 5 minutes.  now it says "nodata for 14 hours" and still no data.
maybe related: when i select a different dashboard such as https://app.raintank.io/dashboard/file/rt-endpoint-dns.json, the endpoint dropdown doesn't even list this endpoint.

**Comment by nopzor1200** [comment]
app.portal is broken i just learned, pending a deploy of master(?)

**Comment by Dieterbe** [comment]
so this is still an issue, but presumably this is due to alerting being disabled and us not being clear towards the user about it. see #331
![nodata](https://cloud.githubusercontent.com/assets/20774/8683761/6bf52238-2a29-11e5-86c2-012306f63823.png)
going to close this for now.
