### ISSUE TITLE
Broken forms

### ISSUE THREAD

**Issue by torkelo** [raintank/grafana#239]
There are many broken forms due to incompatible changes in css between raintank and grafana branches, 

Dashboard links (main culprit tags input css I think)
![image](https://cloud.githubusercontent.com/assets/10999/8307066/dbeafaae-19bc-11e5-81ee-4e8a72a6fdc2.png)

Dashboard settings (main culprit tags input css I think)
![image](https://cloud.githubusercontent.com/assets/10999/8307086/f8b0ce3e-19bc-11e5-89b8-9cf4c0cbf530.png)

Template settings (main culprit body font size change)
![image](https://cloud.githubusercontent.com/assets/10999/8307096/08bc5820-19bd-11e5-93a7-9b181c46d919.png)

Graph Legend options (main culprit body font size change)
![image](https://cloud.githubusercontent.com/assets/10999/8307140/3aeb312c-19bd-11e5-9ab7-3b1d23744210.png)

**Comment by bulletfactory** [comment]
Font size changes are fixed and merged into master. 
<img width="477" alt="screenshot 2015-07-23 11 06 57" src="https://cloud.githubusercontent.com/assets/1950595/8853885/f49a421e-312a-11e5-9e81-42a687a0ff8e.png">

<img width="527" alt="screenshot 2015-07-23 11 00 15" src="https://cloud.githubusercontent.com/assets/1950595/8853843/be4b2c28-312a-11e5-9104-4cb31fd941c1.png">




Will have to look into the tags input css issue.

**Comment by mattttt** [comment]
This is great. I'll pop an issue for @nchristus to look at the tag issue.

**Comment by mattttt** [comment]
Opened issue for https://github.com/raintank/grafana/issues/362
