### ISSUE TITLE
out of memory issues

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#248]
we saw cases this morning in prod where grafana kept allocating more memory and eventually got killed. it was visible with grafana as single instance but seemed to go away when running 3 grafana's. in the latter case @ctdk notes memory slowly rising on grafana-1-prod, but holding steady on grafana-(2|3)-prod 

we enabled profiling on dev-portal (and can go in prod after some testing. should be good, they should have no overhead when unused and limited overhead during profiling)

on dev-portal we tried both cases (3 grafana's, and 1 grafana) and in both cases the profile looks like so:
```
(pprof) top30
10291.99kB of 10291.99kB total (  100%)
Dropped 279 nodes (cum <= 51.46kB)
Showing top 30 nodes out of 50 (cum >= 553.04kB)
      flat  flat%   sum%        cum   cum%
 4999.19kB 48.57% 48.57%  4999.19kB 48.57%  github.com/hashicorp/golang-lru.NewWithEvict
 1536.03kB 14.92% 63.50%  1536.03kB 14.92%  github.com/rainycape/unidecode.decodeTransliterations
 1044.30kB 10.15% 73.64%  1044.30kB 10.15%  reflect.Value.call
  623.02kB  6.05% 79.70%   623.02kB  6.05%  github.com/grafana/grafana/pkg/alerting.distributed
  553.04kB  5.37% 85.07%   553.04kB  5.37%  github.com/grafana/grafana/pkg/log.newLogger
  512.14kB  4.98% 90.05%   512.14kB  4.98%  mcommoninit
  512.14kB  4.98% 95.02%   512.14kB  4.98%  newproc_m
  512.12kB  4.98%   100%   512.12kB  4.98%  regexp.progMachine
         0     0%   100%  1044.30kB 10.15%  github.com/Unknwon/macaron.(*Context).run
         0     0%   100%   512.04kB  4.98%  github.com/Unknwon/macaron.(*Macaron).ServeHTTP
         0     0%   100%  1044.30kB 10.15%  github.com/Unknwon/macaron.(*Router).ServeHTTP
         0     0%   100%   512.04kB  4.98%  github.com/Unknwon/macaron.func·015
         0     0%   100%   532.26kB  5.17%  github.com/Unknwon/macaron.func·016
         0     0%   100%  1044.30kB 10.15%  github.com/Unknwon/macaron/inject.(*injector).Invoke
         0     0%   100%  1536.03kB 14.92%  github.com/gosimple/slug.Make
         0     0%   100%  1536.03kB 14.92%  github.com/gosimple/slug.MakeLang
         0     0%   100%  4999.19kB 48.57%  github.com/grafana/grafana/pkg/alerting.Executor
         0     0%   100%   623.02kB  6.05%  github.com/grafana/grafana/pkg/alerting.Init
         0     0%   100%   553.04kB  5.37%  github.com/grafana/grafana/pkg/log.NewLogger
         0     0%   100%  1536.03kB 14.92%  github.com/grafana/grafana/pkg/models.(*Dashboard).UpdateSlug
         0     0%   100%  1536.03kB 14.92%  github.com/grafana/grafana/pkg/models.NewDashboardFromJson
         0     0%   100%   512.12kB  4.98%  github.com/grafana/grafana/pkg/services/notifications.Init
         0     0%   100%  1536.03kB 14.92%  github.com/grafana/grafana/pkg/services/search.(*JsonDashIndex).updateIndex
         0     0%   100%  1536.03kB 14.92%  github.com/grafana/grafana/pkg/services/search.Init
         0     0%   100%  1536.03kB 14.92%  github.com/grafana/grafana/pkg/services/search.NewJsonDashIndex
         0     0%   100%  1536.03kB 14.92%  github.com/grafana/grafana/pkg/services/search.func·001
         0     0%   100%  1536.03kB 14.92%  github.com/grafana/grafana/pkg/services/search.loadDashboardFromFile
         0     0%   100%   553.04kB  5.37%  github.com/grafana/grafana/pkg/setting.NewConfigContext
         0     0%   100%   553.04kB  5.37%  github.com/grafana/grafana/pkg/setting.initLogging
         0     0%   100%   553.04kB  5.37%  github.com/grafana/grafana/pkg/setting.loadConfiguration

```

so we haven't been able to reproduce yet.

if you want to profile, you can't do it on the system itself, you need the `go` tool, so better do it from your machine (which also lets you use your browser to do svg graphs)
i made a script to make this a bit easier:
```
#!/bin/bash
host=$1
profile=$2
declare -A profiles
profiles[profile]="cpu"
profiles[heap]="heap allocation"
profiles[block]="goroutine blocking"

if [ -z "$host" -o -z "$profile" ] || [ -z "${profiles[$profile]}" ]; then
  echo "$0 <host> profile|heap|block" >&2
  exit 2
fi

rsync $host:/usr/sbin/grafana-server grafana-server

cmd="ssh -fN -L 3000:localhost:3000 $host"
if pgrep -fl "$cmd" >/dev/null; then
  echo "ssh tunnel already running.."
else
  $cmd
fi

go tool pprof http://localhost:3000/debug/pprof/$profile
```

invoke like so:
```
profile-grafana.sh 104.197.5.117 heap
```

now we should come up with a way to timely spot when memory starts rising and trigger a profile.
perhaps with an alert on grafana memory usage, if we can react in time we can manually get a profile.  (automatically getting it might be a bit too advanced)

cc @torkelo @ctdk @woodsaj

**Comment by torkelo** [comment]
good work trying to identify the issue. I guess learning about profiling go applications will come very much in handy in the future :)

**Comment by Dieterbe** [comment]
the go profiling support is pretty sweet, especially the svg viz you get with `web` command.. http://blog.golang.org/profiling-go-programs is a very good introduction.

**Comment by Dieterbe** [comment]
looking at the graph, memory free going under 5GB seems like a good indicator that it consistently leaks and will run OOM. so i've set up a datadog alert for that posts in slack and emails me and @ctdk , hopefully we can kick off a profile in time when it fires

**Comment by Dieterbe** [comment]
I just pushed 950b44f5e9b3650b8ae105d3c0f325171cb77049 which let's grafana automatically take a heap profile whenever memory used by the process exceeds a specified threshold.
disabled by default for now, but should be harmless to enable by default. i tested it in dev stack (with very low threshold and low wait) and seems to work fine.  I recommend enabling this on dev and then in prod.
settings like https://github.com/raintank/raintank-docker/commit/7290aaf28a99426d36a8306f45f182800e9fa203 should work fine:
```
profile_heap_MB = 4000 # threshold in megabytes
profile_heap_dir = /foo/bar # any writable, existing directory here 
profile_heap_wait = 3600 # seconds to wait between each dump.
```

we will hit memory consumption issues sooner or later, perhaps the bug we saw yesterday, or others, and I think this will be very useful.  It saves us from having to manually collect a profile in the (possibly very short) timeframe between problem detected and grafana killed :)

**Comment by nopzor1200** [comment]
@woodsaj @ctdk  what's the status of the OOM issue? I know @ctdk got upstart going in the latest grafana chef (which automatically restarts it right?) and awoods made a fix too (but it wasn't the permanent fix?)

**Comment by Dieterbe** [comment]
@ctdk do we have the automatic profile trigger enabled in prod and dev-portal? that should tell us where the leak is whenever a significant leak happens again.

**Comment by woodsaj** [comment]
The fix i made was for the grafana-server regularly panicking.

I am not convinced that there is a memory leak. Given that GO does garbage collection memory leaks are rare.

I think that the problem we saw in production was due to more data coming in then could be processed.  eg, If grafana is not able to publish metrics to rabbit for some reason, then it will buffer the metrics until it can.  If raintank-metric is not able to publish to kairosdb then it will buffer the metrics till it can.

Looking at the memory graphs, there is no indication that memory use is growing.

**Comment by Dieterbe** [comment]
> I think that the problem we saw in production was due to more data coming in then could be processed. eg, If grafana is not able to publish metrics to rabbit for some reason, then it will buffer the metrics until it can. If raintank-metric is not able to publish to kairosdb then it will buffer the metrics till it can.

then we should put a cap on the buffer where it drops new (or old) metrics instead of growing infinitely.
or persist a buffer to disk. (i know, easier said then done, but nsqd's diskqueue can make this a lot easier at least: https://github.com/bitly/nsq/blob/917a6c8c25e2f91ad8cd9696b89330b5bb799334/nsqd/diskqueue.go)

**Comment by Dieterbe** [comment]
so to summarize, I agree with @woodsaj that leaks are rare, and whatever issue we were seeing is now not really happening anymore.  but there's still two things we need to do:

1) an overly large heap is perhaps rare and uncommon, but it is likely that it will happen again at some point in the future.  so we should assure profile trigger is enabled in prod so we can investigate the cause ( @ctdk ?)
2) avoid getting OOM killed due to a large in-memory buffer of metrics, by capping buffer and/or writing to disk. (see comment above)

**Comment by ctdk** [comment]
@Dieterbe: As I'm circling back around to some of my older tickets, I came across this one. Number 2 is obviously still a thing, unless we start using heka and possibly sidestepping this particular issue. I can't remember though if we've already addressed Number 1 here - did one of us already add a profile trigger?

**Comment by ctdk** [comment]
@Dieterbe Huh, profiling is in fact enabled with that configuration, but it's not writing anything to that directory. Grafana may not have gotten big enough to trigger it yet.

**Comment by Dieterbe** [comment]
> but it's not writing anything to that directory. Grafana may not have gotten big enough to trigger it yet.

that's good. we both tested (me on my laptop, you in dev) that it dumps profiles once the memory reaches the threshold so i'm confident it will in prod.

**Comment by ctdk** [comment]
@Dieterbe is there anything left here to keep this issue open?

**Comment by Dieterbe** [comment]
I think we can consider this pretty much done
* that said it would be nice if we were made aware when a profile is dumped so we can inspect it, but it's not a must. i guess do it if it's simple to do, otherwise don't worry too much about it.
* as for capping collector-controller memory that is part of https://github.com/raintank/raintank-metric/issues/11 now

**Comment by ctdk** [comment]
I'll close this out then. I'll see what I can do to turn up a way to be alerted if something shows up in the profile directory.
