### ISSUE TITLE
make sure grafana /debug endpoint is hidden to public, should only be reachable in local network

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#249]
@ctdk @woodsaj not sure how to do this, maybe it's already the case?
we don't want people to hit our /debug and profiling endpoints

**Comment by torkelo** [comment]
local network is not secure either, just add a datasource with "proxy" mode and query away :)

**Comment by Dieterbe** [comment]
why is local network not secure? is it accessible somehow to non-raintank?

**Comment by torkelo** [comment]
yes, any user can add a datasource in proxy mode and specify a local ip or address, we have not implemented a method to prevent this yet

**Comment by Dieterbe** [comment]
ah yes. whoopsie.

**Comment by woodsaj** [comment]
i think these are two different issues.  /debug should be limited to localhost.  Preventing proxied datasources from hitting internal IP address is a separate issue.

**Comment by ctdk** [comment]
That's a super easy nginx config change. I've added it to our nginx config for grafana already, in fact, and deployed it to dev-portal. I'm opening a separate issue for the proxy thing.

**Comment by Dieterbe** [comment]
i want to make sure we don't forget to test https://app.raintank.io/debug/pprof once this change makes it to prod. maybe you're more confident this fix will seamlessly propagate to prod (and that you'd know if not),
but i'm not that familiar with that process yet so i want to make sure i manually verify.

**Comment by Dieterbe** [comment]
throws 403 on prod now too.
