### ISSUE TITLE
automate creation of dashboards

### ISSUE THREAD

**Issue by woodsaj** [raintank/grafana#25]
We want users to automatically be provided with our stock dashboards for displaying the litmus data. These dashboards should only be added to organisations when there is data available to be displayed.
eg. When a user adds their first endpoint, the summary status dashboard should be added to their account.  When they add their first Ping check, the Ping dashboard should be added.

**Comment by nopzor1200** [comment]
This ticket made sense to me assuming that we were adding Dashboards to Organizations. I guess this is really a bit irrelevant if the dashboards are in raintank/ and accessible to all users?

**Comment by woodsaj** [comment]
yeah i agree.  
Opened a separate issue for showing the dashboards in the list/search menu.

https://github.com/raintank/grafana/issues/47
