### ISSUE TITLE
Collector: Time since State change

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#255]
Similar to how we do with endpoints in the interface, I'd like to expose the time since the last state change on Collectors. For example: "Online for 2 days" or "Offline since 6:49 PM - 23 Jun 2015"

**Comment by mattttt** [comment]
Looks like this is ready to go, and we can move this into 0.16 milestone for the front-end.

**Comment by mattttt** [comment]
A quick shot of the current branch ```collector_info```

![screenshot 2015-06-30 09 52 58](https://cloud.githubusercontent.com/assets/2886187/8433845/d9fe983a-1f0d-11e5-857a-18a2b2c47e22.png)

**Comment by nopzor1200** [comment]
@woodsaj will separate the timestamps for offline|online and enabled|disabled

**Comment by nopzor1200** [comment]
I think that it'd be a good idea to better explain what the difference between online|offline and enabled|disabled is (either through text, helper, something)

**Comment by woodsaj** [comment]
merged PR #317 which splits the enabled and online stateChange timestamps into separate fields.

Also, moved the duration formatting into a filter.  So, you can now format any timestamp in any partial by by using the `timeDuration` filter.

```
 {{collector.online_change | timeDuration}}
```

**Comment by mattttt** [comment]
awesome, thanks!

**Comment by nopzor1200** [comment]
functionality seems to be working on dev-portal. Could still use some style/UI love.

**Comment by mattttt** [comment]
This still needs to be addressed. Will pick this up next week.
