### ISSUE TITLE
What collector information is available?

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#256]
Chatting with @woodsaj today, he said there was additional information that's being stored (and available via the API) about each collector that we're not exposing in the interface.

This ticket is simply to paste in what's being stored, and we can then decide what, if anything, we want to expose for both public and private collectors.

**Comment by nopzor1200** [comment]
@woodsaj can you comment what information would be available?

**Comment by woodsaj** [comment]
Pretty much everything we are storing in the collector_session table.  It is important to note that a single collector/location can have multiple sessions if the collector is running on multiple nodes, or just multiple processes.

Count of collector_sessions.
Timestamp of when the collector_sessions where establised.

Not present yet, but would also like to add.
Collector IP address.
