### ISSUE TITLE
endpoint summary dashboard too hidden?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#258]
is the little icon on the right the only way to go to summary dashboard?
![a](https://cloud.githubusercontent.com/assets/20774/8367555/3c3ef796-1b54-11e5-8945-0488c63ca8a0.png)

the summary page is one of my favorite dashboards cause it's highlevel and contains all in 1 shot, but there only seems to be 1 tiny link that goes to it.  i often find myself in the "main endpoint view page" and was thinking it would be nice to also have something there, like so:
![b](https://cloud.githubusercontent.com/assets/20774/8367627/201d8a04-1b55-11e5-9e83-2967a0e3bc1a.png)

**Comment by mattttt** [comment]
This is a great point. What data would be able to show (without breaking the time-series 'great wall') for global status?

Havent gotten a chance to think much about this, but totally agree with the issue.

**Comment by nopzor1200** [comment]
At the very least for now can we make the dashboard links a little bit more prominent, while we think about grander issues

**Comment by mattttt** [comment]
A couple weeks ago, I put this temporary linkage in place:

![screenshot 2015-07-21 12 51 02](https://cloud.githubusercontent.com/assets/2886187/8806987/7e77b6c2-2fa7-11e5-8edd-6a179bbdd29c.png)

Not the best answer, long term, but at least the functionality is there.
