### ISSUE TITLE
handler not found for GetMonitorsForAlertsQuery

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#260]
`pkg/alerting/alerting_executor_test.go` has an `init` which calls `standalone()` which launches the `Dispatcher` which calls `dispatchJobs` which trigger `GetMonitorsForAlertsQuery` queries to the bus, which the bus can't serve because the bus only has 1 handler:
```
handlers map[EndpointDiscoveryCommand:0x754d00]
```

**Comment by woodsaj** [comment]
=== RUN TestExecutor

  executor must do the right thing 2015/06/26 19:46:45 [D] T foo-0 doing
2015/06/26 19:46:45 [D] job results - job:<Job> key=foo generatedAt=0001-01-01 00:00:00 +0000 UTC lastPointTs=1970-01-01 00:00:00 +0000 UTC definition: <CheckDef> Crit: ''graphite("foo", "2m", "", "")' -- Warn: '0' err:graphite ParseError (<nil>): empty response res:Unknown
2015/06/26 19:46:45 [D] T foo-1 doing
2015/06/26 19:46:45 [D] job results - job:<Job> key=foo generatedAt=0001-01-01 00:00:00 +0000 UTC lastPointTs=1970-01-01 00:00:01 +0000 UTC definition: <CheckDef> Crit: ''graphite("foo", "2m", "", "")' -- Warn: '0' err:graphite ParseError (<nil>): empty response res:Unknown
2015/06/26 19:46:45 [D] T foo-2 doing
2015/06/26 19:46:45 [D] job results - job:<Job> key=foo generatedAt=0001-01-01 00:00:00 +0000 UTC lastPointTs=1970-01-01 00:00:02 +0000 UTC definition: <CheckDef> Crit: ''graphite("foo", "2m", "", "")' -- Warn: '0' err:graphite ParseError (<nil>): empty response res:Unknown
2015/06/26 19:46:45 [D] T foo-2 alredy done
2015/06/26 19:46:45 [D] T foo-1 alredy done
2015/06/26 19:46:45 [D] T foo-0 alredy done
CRITICAL handler not found



75 total assertions

--- PASS: TestExecutor (1.00s)

**Comment by Dieterbe** [comment]
I think this is due de507160841966aa29c6f789f6e25f08cc11d37f
my original point of view was to have the "root of the logic" (i.e. main app or whatever) control what kind of dispatcher/executor it wanted to create (in case of main.go it needs to query the database)
but this stuff was moved into the init of the alerting, which the tests invoke, so now they create a dispatcher which tries to query for jobs, although for unit tests we don't need that, we create the jobs out of thin air and feed them "manually" onto the job queue channel.
@woodsaj see the `CRITICAL handler not found` message toward the end of your paste

**Comment by Dieterbe** [comment]
```
diff --git a/pkg/alerting/alerting_executor_test.go b/pkg/alerting/alerting_executor_test.go
index 31efac1..d783b4f 100644
--- a/pkg/alerting/alerting_executor_test.go
+++ b/pkg/alerting/alerting_executor_test.go
@@ -13,8 +13,6 @@ import (
 func init() {
        Stat, _ := statsd.NewClient(false, "localhost:8125", "grafana.")
        setStatsdClient(Stat)
-
-       standalone()
 }
 
 func assertReq(t *testing.T, listener chan *graphite.Request, msg string) {
```
looks like this is all that is needed

**Comment by woodsaj** [comment]
looks good to me.

all that standalone does is initialize the jobQueue chan then start the dispatcher and Executor in goroutines.

The unittest already initializes the jobQueue and also starts the executor, and as you pointed out, we dont need the dispatcher to run.
