### ISSUE TITLE
compilation from source failed

### ISSUE THREAD

**Issue by JulienChampseix** [raintank/grafana#261]
Hi,

Following docs http://docs.grafana.org/project/building_from_source it appear nothing generated into bin folder.

How to build grafana from https://github.com/raintank/grafana ?

Thanks for your help

**Comment by JulienChampseix** [comment]
@torkelo @Dieterbe any idea about it ?

**Comment by JulienChampseix** [comment]
fixed but can't find alerting part, where it's based on the Grafana WebUI ?

**Comment by Dieterbe** [comment]
in the configuration for new endpoints

**Comment by JulienChampseix** [comment]
i build the grafana repository without trouble but when i'm trying to do same on raintank repo i cant, see bellow error:

Command run for have grafana with alerting part : go get github.com/raintank/grafana
Output:
package github.com/raintank/grafana
	imports github.com/Dieterbe/profiletrigger/heap
	imports github.com/Dieterbe/statsd-go
	imports github.com/grafana/grafana/pkg/alerting
	imports github.com/grafana/grafana/pkg/alerting
	imports github.com/grafana/grafana/pkg/alerting: cannot find package "github.com/grafana/grafana/pkg/alerting" in any of:
	/usr/local/go/src/pkg/github.com/grafana/grafana/pkg/alerting (from $GOROOT)
	/root/go/src/github.com/grafana/grafana/pkg/alerting (from $GOPATH)
package github.com/raintank/grafana
	imports github.com/Dieterbe/profiletrigger/heap
	imports github.com/Dieterbe/statsd-go
	imports github.com/grafana/grafana/pkg/alerting
	imports github.com/grafana/grafana/pkg/api
	imports github.com/Unknwon/macaron
	imports github.com/Unknwon/com
	imports github.com/gosimple/slug
	imports github.com/rainycape/unidecode
	imports github.com/grafana/grafana/pkg/log
	imports github.com/grafana/grafana/pkg/setting
	imports github.com/macaron-contrib/session
	imports github.com/grafana/grafana/pkg/metrics
	imports github.com/macaron-contrib/session/mysql
	imports github.com/go-sql-driver/mysql
	imports github.com/macaron-contrib/session/postgres
	imports github.com/lib/pq
	imports github.com/macaron-contrib/session/redis
	imports github.com/grafana/grafana/pkg/plugins
	imports github.com/grafana/grafana/pkg/services/search
	imports github.com/grafana/grafana/pkg/social
	imports github.com/macaron-contrib/binding
	imports github.com/grafana/grafana/pkg/cmd
	imports github.com/grafana/grafana/pkg/services/elasticstore
	imports github.com/grafana/grafana/pkg/services/elasticstore
	imports github.com/grafana/grafana/pkg/services/elasticstore: cannot find package "github.com/grafana/grafana/pkg/services/elasticstore" in any of:
	/usr/local/go/src/pkg/github.com/grafana/grafana/pkg/services/elasticstore (from $GOROOT)
	/root/go/src/github.com/grafana/grafana/pkg/services/elasticstore (from $GOPATH)
package github.com/raintank/grafana
	imports github.com/Dieterbe/profiletrigger/heap
	imports github.com/Dieterbe/statsd-go
	imports github.com/grafana/grafana/pkg/alerting
	imports github.com/grafana/grafana/pkg/api
	imports github.com/Unknwon/macaron
	imports github.com/Unknwon/com
	imports github.com/gosimple/slug
	imports github.com/rainycape/unidecode
	imports github.com/grafana/grafana/pkg/log
	imports github.com/grafana/grafana/pkg/setting
	imports github.com/macaron-contrib/session
	imports github.com/grafana/grafana/pkg/metrics
	imports github.com/macaron-contrib/session/mysql
	imports github.com/go-sql-driver/mysql
	imports github.com/macaron-contrib/session/postgres
	imports github.com/lib/pq
	imports github.com/macaron-contrib/session/redis
	imports github.com/grafana/grafana/pkg/plugins
	imports github.com/grafana/grafana/pkg/services/search
	imports github.com/grafana/grafana/pkg/social
	imports github.com/macaron-contrib/binding
	imports github.com/grafana/grafana/pkg/cmd
	imports github.com/grafana/grafana/pkg/services/elasticstore
	imports github.com/grafana/grafana/pkg/services/eventpublisher
	imports github.com/streadway/amqp
	imports github.com/grafana/grafana/pkg/services/metricpublisher
	imports github.com/grafana/grafana/pkg/services/metricpublisher
	imports github.com/grafana/grafana/pkg/services/metricpublisher: cannot find package "github.com/grafana/grafana/pkg/services/metricpublisher" in any of:
	/usr/local/go/src/pkg/github.com/grafana/grafana/pkg/services/metricpublisher (from $GOROOT)
	/root/go/src/github.com/grafana/grafana/pkg/services/metricpublisher (from $GOPATH)

**Comment by JulienChampseix** [comment]
Build command return that:

-@grafanabox:~/go/src/github.com/raintank/grafana# go build .
main.go:15:2: cannot find package "github.com/grafana/grafana/pkg/alerting" in any of:
	/usr/local/go/src/pkg/github.com/grafana/grafana/pkg/alerting (from $GOROOT)
	/root/go/src/github.com/grafana/grafana/pkg/alerting (from $GOPATH)
main.go:21:2: cannot find package "github.com/grafana/grafana/pkg/services/elasticstore" in any of:
	/usr/local/go/src/pkg/github.com/grafana/grafana/pkg/services/elasticstore (from $GOROOT)
	/root/go/src/github.com/grafana/grafana/pkg/services/elasticstore (from $GOPATH)
main.go:23:2: cannot find package "github.com/grafana/grafana/pkg/services/metricpublisher" in any of:
	/usr/local/go/src/pkg/github.com/grafana/grafana/pkg/services/metricpublisher (from $GOROOT)
	/root/go/src/github.com/grafana/grafana/pkg/services/metricpublisher (from $GOPATH)

**Comment by JulienChampseix** [comment]
@Dieterbe you have a way to compile it successfully ?

**Comment by Dieterbe** [comment]
this should do it
```
go get github.com/grafana/grafana
go get github.com/raintank/grafana
cd $GOPATH/src/github.com/grafana/
mv grafana grafana-upstream
ln -s $GOPATH/src/github.com/raintank/grafana .
cd grafana
go run build.go setup            (only needed once to install godep)
godep restore                    (will pull down all golang lib dependecies in your current GOPATH)
go build .
```

**Comment by JulienChampseix** [comment]
thanks ! that's works ! really appreciate your quick help!
Do you know if is it already possible to setup alerting on some metrics based on influxdb ?

**Comment by Dieterbe** [comment]
it's not. current engine is for graphite only at this point.

**Comment by Dieterbe** [comment]
updated readme with these instructions. acd5e9c
