### ISSUE TITLE
dynamic footprint checks are not automatically computed and scheduled

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#262]
With a dynamic footprint configured for a particular check, updating a relevant tag in a Collector does not result in the test footprint automatically changing (as would be expected)

If I go into endpoint.configuration and update the check configuration (with the same dynamic footprint), the test footprint does change.

After discussing with @woodsaj it seems that we need to (re-add) periodic computation of dynamic footprints based on tags.

(reported by packet)

**Comment by woodsaj** [comment]
This requires sending periodic refreshes to collector nodes.
