### ISSUE TITLE
tracking state for alerting scheduler

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#266]
when the alerting scheduler stops/crashes/is killed, and we start a new one, we need to be able to cleanly resume where we left off.
(the extent to which we travel back in time is by itself a topic worth discussing. traveling back hours in time doesn't seem worth it, but seconds to a minute or two, i think it does. users may get a critical followed by a warning, depends on how much they care about issues in the past i guess. anyway that's another topic)

last friday I wrote a better ticker (#259) which supports resuming ticks from a given timestamp.
so every second, the alerting scheduler(s) need to update some datastore with with what's the last succesfully processed timestamp.   so that when a scheduler starts, it can read this out again.  This could be as simple as a row/column in mysql somewhere, but I'm not sure what's the cleanest way to do this in the code / mysql schema? @torkelo ? @woodsaj ? we currently only have a hard depedency/commitment to 1 datastore, right, mysql?

**Comment by woodsaj** [comment]
This is what we need a distributed commit log for (Raft).  Long term that is going to be the way to go.  But in the short term, just running the dispatcher on multiple nodes will avoid this problem (unless all nodes running the dispatcher fail at the same time)

**Comment by Dieterbe** [comment]
I think we should allow single-instance setups to restart and resume where they left off. I presume (?) a lot of folks out there will simply run 1 grafana instance. Even in the multiple-instances scenario (like wat we're building) having the state persisted somewhere feels a lot safer to me. raft is in memory only right?

**Comment by torkelo** [comment]
maybe a table in the sql store for the scheduler to keep track of this?

**Comment by Dieterbe** [comment]
i'm going ahead with this unless @woodsaj has an argument against mine.

**Comment by woodsaj** [comment]
I am not really convinced that the gains from doing this outway the cost.  This is far more complex then just reading and writing a position stored in the DB.

For a single node instance:

if the node is offline for 5minutes, when it starts up again how are you going to schedule the jobs missed during the 5minutes.  You cant just run all of the missed jobs at once as this will break state transitions if a job with a later start time finishes before older jobs. Jobs need to run in sequential order, but jobs are currently processed asynchronously so you wont know when to kick of the next job.

**Comment by Dieterbe** [comment]
>  You cant just run all of the missed jobs at once as this will break state transitions if a job with a later start time finishes before older jobs.

this concern applies also in normal operation (jobs scheduled 10 seconds apart can still finish in the wrong order if one of them takes 2 seconds and the other more than 12).  It's just that this concern is a bit more apparentl in this scenario, but it's definitely not unique to this scenario.
The solution is only update the state, in a transaction, if our state is newer than the last state known in the database. (I thought we discussed this somewhere but couldn't immediately find it). anyway i hope we can agree on at least this.

>  This is far more complex then just reading and writing a position stored in the DB.

I do not agree. unless I am missing something.  As far as I see it's only about incrementing the db and reading from it.

See also #291 which evolved into a discussion about whether this is useful at all.

**Comment by Dieterbe** [comment]
so #291 convinced me that for now we don't need the state tracking.  However I'ld still like to see your feedback/response on the above comment @woodsaj just to make sure we're aligned. thanks

**Comment by Dieterbe** [comment]
ok AJ upvoting the only-if-newer state in #346 is most of what i wanted to know.

**Comment by Dieterbe** [comment]
[test | uploaded via ZenHub](https://files.zenhub.io/55afc412849fd9803bf8fbbf)
