### ISSUE TITLE
Not all endpoints appearing in dropdown

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#275]
Reference: https://app.raintank.io/dashboard/file/rt-endpoint-ping.json

A client is unable to find one of their endpoints (www_domain_com) in the $endpoint dropdown, however they are able to manually add the arguments to render the dashboard successfully. 
https://app.raintank.io/dashboard/file/rt-endpoint-ping.json?var-endpoint=www_domain_com

Will replicate in dev and post screenshots.

**Comment by mattttt** [comment]
In this particular client's account, the $endpoint dropdown shows 63 endpoints, and the Litmus endpoint list shows 68.

**Comment by mattttt** [comment]
Chatting with Jeremy at Packet today and they're still experiencing this issue.

**Comment by woodsaj** [comment]
this should be fixed by: https://github.com/raintank/graphite-kairosdb/commit/1f4232f1f86ada36309e875ca11fff5027eae93b

i dont believe this has been pushed to production though.

**Comment by nopzor1200** [comment]
This looks to be resolved in dev-portal at least (where Master account has 140+ endpoints and can test this well). Haven't verified on app.raintank.io @mattttt ould you verify and close this?

**Comment by mattttt** [comment]
As of tonight, 66 in the dashboard dropdown and 71 showing in Litmus.

**Comment by mattttt** [comment]
@ctdk Let me know when this is in product and I can check again.

**Comment by woodsaj** [comment]
@mattttt the has already been pushed to production.

But i just did some testing and due to the volume of data the 10K document limit is not enough for packet.   They have ~70K metrics indexed.  

I am not sure that i am comfortable increasing the document limit that high and we might need to look at other options.  Having to process 70K documents to return just 70ish results is pretty expensive.

**Comment by ctdk** [comment]
@mattttt I'm not sure if this still needed my attention or not, but production has the latest grafana code now.

**Comment by woodsaj** [comment]
Fixing this will be related to https://github.com/raintank/raintank-metric/issues/11

**Comment by mattttt** [comment]
Let me know when I should verify this again - alternately, you guys can verify directly by going to Packet's endpoint list and getting a count, then going to the endpoint template dropdown in a dashboard and manually counting.

**Comment by mattttt** [comment]
This is still an issue, and needs to be addressed. From Jeremy @ Packet today:

![screenshot 2015-09-15 14 48 52](https://cloud.githubusercontent.com/assets/2886187/9886543/e71a0ec2-5bb8-11e5-81ff-d3782a414350.png)

**Comment by woodsaj** [comment]
This will be fixed by: https://github.com/raintank/graphite-kairosdb/issues/16

**Comment by woodsaj** [comment]
This has been fixed in https://github.com/raintank/graphite-raintank/pull/4

This is the new graphite plugin which uses the new metric-tank TSDB.  This should be rolled out to prod in 2-3weeks.

**Comment by woodsaj** [comment]
FYI, the changes to fix this were deployed to production before christmas.
