### ISSUE TITLE
Frontend enhancement: Auto-discovery failed styling 

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#276]
When auto discover fails, the html/CSS can be a lot nicer.

**Comment by mattttt** [comment]
![image](https://cloud.githubusercontent.com/assets/2886187/8446274/0378413a-1f76-11e5-8a33-dffad7d14c92.jpg)

**Comment by nopzor1200** [comment]
And when you cancel it it shouldn't say it was successful, either.
