### ISSUE TITLE
the "save" button for endpoint is called "add endpoint"

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#277]
the "save" button for a new endpoint is called "add endpoint" and this is confusing. it looks like it might create a new endpoint rather than saving the existing form values.

contrast with adding a datasource where the similar button just says "add" which is clearer.

**Comment by Dieterbe** [comment]
@mattttt ?

**Comment by mattttt** [comment]
I like simplifying it to 'Add'. I can make that change.

**Comment by bulletfactory** [comment]
are you suggesting a conditional button, so when initally adding an
endpoint, the button label reads "add," but after you've already added an
endpoint, and are changing some of the configuration of a check at a later
time, the button label reads "save"?

**Comment by mattttt** [comment]
That's already conditional and reads "Update" on a per check basis.

**Comment by nopzor1200** [comment]
Is there anything that actually needs to happen here @mattttt ? 

I interpreted @dieterbe original question as if he was saying that it was bad to call it "Add" and advocating calling it "Save". You say "you like simplifying to Add and can make that change".  Am I misunderstanding @dieterbe intent or are you disagreeing with it?

**Comment by bulletfactory** [comment]
The suggestion is changing the button at the bottom from "Add Endpoint" to simply "Add" which aligns with verbiage in adding a new datasource.

The confusion is the word "Endpoint" as it reads like it would be adding a second endpoint.

![screenshot 2015-07-22 11 00 20](https://cloud.githubusercontent.com/assets/1950595/8828629/2c17d528-3061-11e5-8e46-2daa132e6637.png)

If the button just said "Add" it would feel more clear.

**Comment by bulletfactory** [comment]
Pushed the update. Will merge unless someone wants to tweak further
![screenshot 2015-07-22 14 22 20](https://cloud.githubusercontent.com/assets/1950595/8833528/3478562c-307d-11e5-83e1-41d6e5aca046.png)

**Comment by nopzor1200** [comment]
looks good trent

**Comment by bulletfactory** [comment]
ok - thanks.
