### ISSUE TITLE
can we rename collector? perhaps to probe?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#278]
i've been thinking and feeling this out for a little while now.  I don't think "collector" is a very appropriate word for what our collectors do.
What do collectors collect, really? It's not like they collect metrics or measurements from the endpoints.  In fact they *generate* the metrics themselves.  The only things they collect are their configuration (not a significant feature that should drive their naming) and responses to the requests they execute (which is only a small part of what they do, and is also an awkward part to be named for)

instead, i propose "probe"

```
    2. a small device, especially an electrode, used for measuring, testing, or obtaining information

v. verb

    1. physically explore or examine (something) with the hands or an instrument researchers probing the digestive glands of mollusks
    2. seek to uncover information about someone or something 
```

The name "probe" is IMHO a lot more representative of the main logic performed by our collector: small application that examines something and provides measurements
bonus point: only 5 letters instead of 9 :)

To change this in order of priority:

- [x] Change language in the HTML (everywhere in-app)
- [ ] Change website and docs
- [ ] Change Less files and CSS class names
- [ ] Change backend

**Comment by nopzor1200** [comment]
I don't disagree with this at all, I actually voted for probe as my first choice in the summit. What did you vote for? 

It's just a pain in the ass to rename it everywhere obviously.

The cincher for me was hearing @woodsaj describe Litmus and say "you install our collector software which are probes..."

Would be curious what others think at this point.

**Comment by Dieterbe** [comment]
> What did you vote for? 

i don't remember for sure, but I think probe.
Now that you mention it, I think at summit we decided to stick with the name "for now" as it would be too much work to change.  I think we should just change it, at least in the docs/UI.  it can't be *that* much work, right? the longer we wait the harder it becomes.  for the software, we can just adopt the new term when we do the golang rewrite.

**Comment by nopzor1200** [comment]
probe was my number #1 choice
sensor was my number #2 choice
collector was my number #3 choice

**Comment by mattttt** [comment]
To memorialize, though I cant remember why, Collector was my #1 choice - but I'm cool with renaming to Probe if we think it's the better choice.

**Comment by nopzor1200** [comment]
Adam touched base with me via text just now to continue the discussion about Packet helping with the rewrite of the "probe software"

**Comment by woodsaj** [comment]
I cant remember why i was against probe and so I see no problem with renaming.

In that effort i have created https://github.com/raintank/raintank-probe which contains the the rewrite in Go of the collector.

**Comment by nopzor1200** [comment]
OK, let's rename it to probe. I think it's a good call.

#decisionmade. 

Obviously implications across the board @dieterbe @mattttt @bulletfactory in how we reference stuff and frontend.

@woodsaj its probably a PITA but can you refactor things in our collector software to reference probe instead (across the board...)

**Comment by woodsaj** [comment]
This is a big job, but achievable

From a quick review of the code the following will need to be done:

1. rename table names and foreign_key column names in the DB.
  * collector
  * collector_tag
  * collector_session
  * monitor_collector_tag
  * monitor_collector
2. update references in pkg/api/socket.io

Changes will also need to be made in raintank-collector while we transition to the all Go version

**Comment by bulletfactory** [comment]
And just when I was about to start referring to the new collectors written in Go as "gollectors".

**Comment by Dieterbe** [comment]
ha. they'll have to be "grobes".

**Comment by woodsaj** [comment]
So i now remember why i preferred collector:

As the raintank platform is built out new capabilities will be added to the "collector" code base.  Some things i see it doing:
- perform synthetic browser tests (sitespeed.io)
- graphite/carbon proxy that can run on hosts to accept any metrics, ie from collectd or statsd
- collecting metrics from cloudwatch
- handle custom data collection added by users.

So "Collector" might not be the best name, but i dont think that probe is any better.

The collector needs to be rewritten soon, and this will also involve a re-architecture to allow extending its capabilities over time.  The way i see it working is that the "collector" is the base entity that "collects" data from various sources and transmits it back to app.raintank.io. This entity will have a list of "capabilities" that it registers when connecting. Through the UI we can assign litmus checks to collectors with the capability "litmus-probe" and assign cloudwatch collection to a collector with the capability "CloudWatch"

**Comment by mattttt** [comment]
Spoke with @nopzor1200 yesterday IRL, decision is to change Collector to Probe everywhere in the front-end, but keep the raintank collector software named that. 

Will make the changes within the interface and highlight any inconsistencies/confusion on this issue.

**Comment by mattttt** [comment]
From this point forward, Collectors are now to be referred to as Probes. This is a pretty substantial task in the backend, but not so much in the frontend. 

Starting a ticket to change this in order of priority:

- [ ] Change language in the HTML (everywhere)
- [ ] Change Less files and CSS class names
- [ ] Change backend

branch: `goodbye-collector`

Instances of the word collector in the entire repo: 843 matches across 38 files

**Comment by nopzor1200** [comment]
I'm fine keeping collector in the backend for now. Awoods brings up good points about how the software itself could evolve to be more collector-like instead of probe-like.

But, for Litmus, I think we're making the right decision, and good job on the change @mattttt and I really really like the probe icon that @bulletfactory whipped up. In Litmus parlance and context, it's easier to think of things as "probes" as opposed to "collectors". I feel very strongly about that point.

No urgency or rush at the moment to refactor the backend to change collectors to probes.

**Comment by Dieterbe** [comment]
does anything else need to happen for this?
I think all remaining todo's in OP are addressed now. (except for backend). @mattttt ?

anything else need to happen in backend or shall we just close this? @woodsaj ?
