### ISSUE TITLE
alert notifications should contain check type and state in subject

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#279]
otherwise it's not easy to discern what's going on.
![wzgxogm](https://cloud.githubusercontent.com/assets/20774/8460858/ec0214ce-1fdc-11e5-8652-0ed2d84c3843.png)

**Comment by nopzor1200** [comment]
Totally agree. Mention this to @mattttt a couple of times. Maybe you guys can work together to see 

what's possible? I think that the alert should ideally show "Alert: $endpoint went from OK to ERROR" or something like that.

**Comment by mattttt** [comment]
Thanks for popping this issue @Dieterbe, had completely slipped my mind. Will ask @woodsaj on what's feasible currently, and pop issues for the future things.

**Comment by mattttt** [comment]
Submitted in PR: https://github.com/raintank/grafana/pull/288

![screenshot 2015-07-03 10 45 52](https://cloud.githubusercontent.com/assets/2886187/8501197/207918f2-2171-11e5-9955-e1fb81f139df.png)
![screenshot 2015-07-03 10 45 13](https://cloud.githubusercontent.com/assets/2886187/8501196/207680c4-2171-11e5-8eb7-19536e532775.png)

**Comment by mattttt** [comment]
We now almost have finished responsive templates. This is code in browser, not a mockup:

![screenshot 2015-07-03 13 35 12](https://cloud.githubusercontent.com/assets/2886187/8503135/66b595cc-2188-11e5-824f-d106817b5319.png)
![screenshot 2015-07-03 13 34 48](https://cloud.githubusercontent.com/assets/2886187/8503136/66b814e6-2188-11e5-9f2c-d7cea758a667.png)

**Comment by mattttt** [comment]
Merged into master.

**Comment by mattttt** [comment]
Note: Images will be busted until assets are pushed up onto production.
