### ISSUE TITLE
alert executor shouldn't rely on job state at schedule time, it should use the latest state.

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#291]
with the current code, the executor evaluates the expression and compares the result to what it was when the job was created.
note that a significant (or at least >0) amount of jobs for the same endpoint/checktype can be waiting in the queue. for example this scenario:
```
state in db is ok
at 10:20:00, schedule a job, begin state is ok
at 10:20:10, schedule next job, begin state is ok
at 10:20:30, schedule next job, begin state is ok
at 10:20:40, schedule another job, begin state is ok
for whatever reason, (perhaps some executors crashed and had to be restarted, causing processing to slow down) there was a 40 second delay. so now:
first job finds endpoint down, and begin state was ok, so sends email
second job finds endpoint down, and begin state was ok, so sends email
third job finds endpoint down, and begin state was ok, so sends email
fourth job finds endpoint down, and begin state was ok, so sends email
```

instead, the executors should consult the database so that they always see the result of the job that came before them. jobs are always sequential and time-ordered so this should be safe and accurate.

this may or may not be a cause/contributing factor to #280 . @woodsaj suggested monitoring the time difference between job scheduled and executed, which i think is a great idea as it will uncover whether the above scenario is manifesting itself or not.  So I'll do that now.

**Comment by woodsaj** [comment]
This is almost certainly the cause of #280

While delaying the look up of the state until the check has been run is probably the best solution, it also doubles the number of SQL queries needed and is still vulnerable to race conditions (if two checks execute at the same time for some reason)

The alternative is to simply change the SQL statement used to update the state to be.
`UPDATE monitor set state=? where id=? and state=?; args(newState, id, oldState)`

This will ensure that the state only gets changed if it is still in the same state as when the alerting job was scheduled.

**Comment by Dieterbe** [comment]
> This will ensure that the state only gets changed if it is still in the same state as when the alerting job was scheduled.

there's potential for mistakes with that too. we're not using warning right now, but when we do, and state at schedule time was ok, then another jobs set warn, and we want to set to critical, then this wouldn't cause the update. what we could do is `"update .. where .. and state != ?", currentstate`

> While delaying the look up of the state until the check has been run is probably the best solution, it also doubles the number of SQL queries needed

Well at least only single rows need to be locked per query, and if we ever get to it, this data is easily sharded or moved into optimized stores.

> ... and is still vulnerable to race conditions (if two checks execute at the same time for some reason)

So my goal is to make sure a job for any combo of endpoint-checktype-timestamp can only be executed once, except in scenarios where we purpously do it for whatever reason and manage it carefully, see below.

In normal operation I think we can easily guarantee this.

`max-window`: maximum delay between data age and scheduling age (if alerting executors were out for a while, do we care about executing jobs for data 5 minutes ago, an hour ago?, a day ago?)
`max-jobs-rate`: maximum rate of jobs per second going into a process. this is based on average jobs/s being scheduled, rated for how much of that load a single process might have to take on (in worst case, like if other executors die),which we could keep at 100% for now.

* all executors in a process share an LRU, so we can tune LRU size to something like `max-window  * max-jobs-rate = LRU size`. duplicate jobs would either fall out of the window and be dropped, or guaranteed to be present in the LRU and skipped. 
* for a stable single node, that's all we need.
* for a stable cluster setup, the same logic extends beatifully because we route based on the key of the job and it will hit the same LRU.

things get more interesting in the following cases:

* manual interventions, we may have to rerun jobs if we found out something get messed up. I guess we'll have to look at this on a case by case basis, I find it hard to think in advance about such cases but I'll pain my brain a bit.

* single instance dies, and the single node comes back: the "last executed tick" might be several seconds behind, those jobs would get rescheduled and either dropped due to `max-window` or acted upon because the LRU would be reset. Those would cause errorous state changes and duplicate notifications if not handled properly. I propose we could store a "last executed timestamp" field for every monitor-checktype combo, and ignore jobs who are older, both at scheduling time and "i have a result, i'm considering updating the db and sending a notification" time.

* node dies in cluster and/or adding a new executor to the cluster:  this causes jobs to go to different istances and actually looks a lot like the above case I think. a "last executed timestamp" should alleviate most issues except for which goes first, processing (email) an event, or updating he timestamp, either order is racey in light of crashes. 
- email first, update timestamp then: might see duplicate emails when executor crashes in between steps
- update timestamp, then email: ditto.

all of the above of course also requires that email sending is reliable (instead of directly sending the email, we need to setup a reliably persisted queue with workers that can do retry and ack)

**Comment by woodsaj** [comment]
I dont think there is any value in tracking the last run check time.  Whenever you start/restart a node you only ever want to start checking from NOW().  Any checks that were skipped while the node was down will get scheduled to run at the next interval.  Likewise, there should never be a need to re-run a job. If there is a bug that causes invalid results, once the bug is fixed the next run of the check will correct the state of the check.  i dont see there being any value to knowing what alerts should have been sent in the past but weren't,  i only want to know what the current state is.  If i want historical data i will look at my timeseries data.

Also emails are already currently handled asynchronously.  Once the email template has been parsed and validated, the email is pushed into a queue that is asynchronously handled. Though this obviously needs to be extended to handle retries.

**Comment by Dieterbe** [comment]
> i dont see there being any value to knowing what alerts should have been sent in the past but weren't, i only want to know what the current state is. If i want historical data i will look at my timeseries data.

I don't agree at all with this.  I think there is a lot of value in receiving alerts even after the fact.
Here's an example scenario to explain:
let's say we have an infrastructure problem and for 5 minutes long, we don't have any executors running. let's say this happens from 10:55 to 11:00. Now let's say amongst the many endpoints we are monitoring, there is an endpoint that was down from 10:58 until 11:00. 
(for simplicity let's assume 0 offset and only check 1 point in a row, the logic extends for the 30-second offset we have and x-points in a row though)

when we restart our executors, we have two options:
A) start creating jobs for data at NOW, as you suggest, resulting in no notifications sent for the endpoint outage.
B) start creating jobs for data at a certain point in the past, and later. start at a timestamp possibly 1,2,3,4,5 minutes in the past.

My take is that B is better, because you can still get alerted about outages, just with a few minutes delay.
If you're an ops engineer and you rely on raintank to monitor your website, then you're probably happier with receiving alerts x minutes late rather than never.  If you don't get an alert, you might not notice the short-lived outage at all. I can speak from experience it's not fun if a CEO storms into the ops room because the site is offline and you didn't know. 
The main question is: 
**at which point is a stale notification really not worth sending anymore?**
and this question depends on another:
**how long does it take before an ops engineer notices the website is down without raintank telling him/her?** 
If your website is down because of a reason you're not monitoring with anything else (backend/infra you're probably monitoring, but often not WAN links) than this timeframe can be very long, potentially days, or never.

So in my opinion it's more like:
![delayed-notifications-tradeoff](https://cloud.githubusercontent.com/assets/20774/8505557/66f75aa0-219e-11e5-87a6-59e12a26ed17.png)

**Comment by nopzor1200** [comment]
Personally I think it's a bit of an edge case; I agree with @woodsaj . Just to rephrase and make sure I understand: we're asking whether it's worth it to send stale alerts for outages that are no longer ongoing? 

If it means complicating our code or adding load my vote is no. 

IMO the alert is pretty useless after just a few minutes. Especially if the site is up now. Infact, for many many use cases if the site is back up now I don't want to get an alert especially if it means getting woken up?

Even in your example of CEO storming into a room because the site is offline and nobody knew. That's not the real example for this feature because if the site was still offline, and we didn't have this feature, they'd still get notified as soon as our alerting backend came back up. 

The correct example would be the CEO storming into a room because the site WAS offline (but is online now) and nobody knew, right?

(underscores how important to make the alerting backend solid and continue to make progress on making sure we have good coverage, tooling, monitoring etc to make sure we do recover from issues very quickly)

**Comment by Dieterbe** [comment]
> Just to rephrase and make sure I understand: we're asking whether it's worth it to send stale alerts for outages that are no longer ongoing? 

yep. 

ok. so you and anthony managed to convince me that this is not enough of a concern right now.
I think things change once our alerting system distinguishes critical (wake up ops engineer!) from warning (email only).  Once we have "soft" alerts (warning, no wake-up) I think it would make sense to send stale notifications for outages no longer ongoing, up to a certain point in the past.  In that sense the "noise" should be worth it when weighed against the fact that the ops engineer might have totally been unaware of the outage.  I'ld like to keep this discussion going because at some point we will differentiate warning from critical.

**Comment by Dieterbe** [comment]
in addition, we should consider the option of running missed jobs to cover the timespan of an alerting system outage, but without sending notifications or updating the db, merely to assure the state-over-time metrics in graphite are filled in, so that things look good in the dashboards.
(this would need a different mechanism than what i described in #266 though, as we would want to run current jobs and gradually fill in the past at the same time)
