### ISSUE TITLE
New Scope Variables for Emails

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#295]
In order of priority:

- Time of alert (the exact second we made the determination)
- Endpoint ID
- Endpoint Name

**Comment by nopzor1200** [comment]
The time of alert is really the key one here... it's really annoying to receive a few alerts in a row and have to look at headers...
Is this something best assigned to @Dieterbe ?

**Comment by Dieterbe** [comment]
i suspect awoods is much more familiar with the code but i can give this a shot

**Comment by woodsaj** [comment]
endpointId and time of have already been added in, see https://github.com/raintank/grafana/commit/92b73558636b3fc457a5f25a6c8c2d12070fd3de

 all that is missing is endpointName.

**Comment by Dieterbe** [comment]
@woodsaj what do you think of https://github.com/raintank/grafana/pull/373
I realized just the endpoint name is not enough to be really useful. it's better if we can include port, path and so on.

**Comment by woodsaj** [comment]
#373 looks good, but what is needed comes down to what @mattttt  needs to for the email templates.

**Comment by Dieterbe** [comment]
ok well @mattttt this gives you access to a bunch of the parameters:
```
map[string]string{"port":"443", "path":"", "method":"GET", "expectRegex":"", "headers":"Accept-Encoding: gzip\nUser-Agent: raintank collector\n", "validateCert":"true", "host":"www.dnsbelgium.be"}
```
you can use as many, or as little of these as you please ;)

**Comment by Dieterbe** [comment]
@mattttt can you confirm whether you need anything else?

**Comment by nopzor1200** [comment]
Is it easy for you to do time too?

The User Agent, Cert  etc I think is a bit extraneous. 

Endpoint name and time need to be front and center and are much more important.

Is it easy for you to make endpoint name and time of alert available?

**Comment by Dieterbe** [comment]
well time is already available. re endpoint name, isn't that just the host field, which I made available earlier (see above)?

**Comment by woodsaj** [comment]
Host field is not always the endpoint name.  Typically when using the endpoint discovery the endpoint name and hostname are the same, but the user can change it.

To get endpoint name, we would need to add endpointName to model.MonitorForAlertDTO{} and update the query in sqlstore.GetMonitorsForAlerts() to retrieve the endpoint.name (the existing query already has a table join with the endpoint table, so should be straight forward)
