### ISSUE TITLE
Collectors page and render calls

### ISSUE THREAD

**Issue by torkelo** [raintank/grafana#299]
The collectors page is hammering the graphite api backend. 

![image](https://cloud.githubusercontent.com/assets/10999/8517632/f0cc228a-23c2-11e5-8756-0fb9fb232e58.png)

Is this expected?

**Comment by mattttt** [comment]
@torkelo This is the collector list page or  collector summary?

**Comment by torkelo** [comment]
The list page, it takes about a 40 seconds to complete all requests that it generates.

**Comment by woodsaj** [comment]
@matt this is the collector list page.  and is from the the <rt-collector-health> counters.

**Comment by nopzor1200** [comment]
I'd like to remove those counts from the collector list page. They're a heck of a lot faster with the new graphite-api but I don't think the numbers are really all that useful there.

**Comment by mattttt** [comment]
Agreed.

**Comment by nopzor1200** [comment]
Assigning to @mattttt assuming he can remove the counters from the list page and close this out

**Comment by Dieterbe** [comment]
+1 on counts not useful on list page. all i care about is whether collector is considered online or offline.
this info could go to collector summary/details page.

**Comment by mattttt** [comment]
Will remove counters from page.

**Comment by mattttt** [comment]
Thanks @Dieterbe

**Comment by mattttt** [comment]
Removed in PR https://github.com/raintank/grafana/pull/368, merged into master.

Closing ticket.
