### ISSUE TITLE
BUG: Repeat panel & auto span causes very narrow panels

### ISSUE THREAD

**Issue by torkelo** [raintank/grafana#300]
https://app.raintank.io/dashboard/file/rt-endpoint-comparison.json 

I added auto span handling to panel repeats some weeks ago, seems to cause issues when you select many values. 

This is now fixed in upstream Grafana by adding another option (in the templating options in panel general tab next to the panel repeat dropdown). This option is `minSpan` and it controls the minimum span the panel should take when repeating. So if this is set to 4 the panel will take up all horizontal space if only one values is selected (span 12), 50% if two is selected (span 6), but if 10 values are selected the span will be 4 and the panels will wrap. 

https://github.com/grafana/grafana/commit/37d75905ed9e3d1f13f822a1a63653a3276c5851

**Comment by nopzor1200** [comment]
Thanks @torkelo this is now fixed in #335 I will close this when I see it looking good in dev-portal too

**Comment by torkelo** [comment]
did another fix today, concerning repeat panels and unwanted unsaved changes warning, will not effect json dashboards (the default raintank ones) but it will affect user copies of those. 

https://github.com/grafana/grafana/commit/0a59d6ab2fb4646e309ea748ad35566b1d992379
