### ISSUE TITLE
Standardize order of Checks across endpoint screens

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#301]
The current order on assorted screens:

Endpoint List: Ping, DNS, HTTP, HTTPS
Endpoint Summary: Ping, DNS, HTTP, HTTPS
Endpoint Config: DNS, Ping, HTTP, HTTPS

Several weeks ago, we charged endpoint config to list DNS first (OSI model driven), but did not update the other two pages accordingly.

@nopzor1200 Can you confirm that we'd like to keep DNS first, and I'll push those changes. Thx!

**Comment by nopzor1200** [comment]
Yes, DNS first I think is best. TBH while it should be consistent we're not representing the OSI model as much as I'd originally anticipated.

**Comment by Dieterbe** [comment]
huh according to OSI http, https and ping are all layer 7 (application layer) protocols, whereas ping is icmp is layer 3 (network). so wouldn't it make more sense to make it ping, dns, http, https?
am i missing something?

**Comment by mattttt** [comment]
@nopzor1200 What say you? I'd like to close this oout.

**Comment by nopzor1200** [comment]
I think that technically dieter is correct. But, practically, the DNS check is the only thing that's validating resolution from the auth DNS servers. So, it's going to fail independent of the health of the entire endpoint. And, if it fails, it will cause ping|http/s to both too. 

Therefore I think the order everywhere should be dns | ping | http/s

**Comment by Dieterbe** [comment]
Sounds good to me

**Comment by Dieterbe** [comment]
on https://app.raintank.io/dashboard/db/worldping-home the order is still incorrectly ping dns http/s
