### ISSUE TITLE
Endpoint List - More Menu Bug

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#305]
On endpoint list, the previously working More Menu (vertical ellipses) now automatically takes you to endpoint/summary/{{endpoint.id}} instead of triggering the dropdown menu:

![endpoint-menu-issue](https://cloud.githubusercontent.com/assets/2886187/8536143/32976046-241b-11e5-8b87-dcd26648e9ca.gif)

On click, correct behavior is to show a menu of View, Configure, Delete. 

This appears to be happening on production, but dont yet know when it was introduced.

**Comment by mattttt** [comment]
@woodsaj Im working on some other changes with these pages, so I'd love to squash this bug while im at it. Anything immediately come to mind?

**Comment by mattttt** [comment]
Actually realizing this might be related to the merge by @reduxdj. Patrick, can you take a look and see if you know what's up?

**Comment by woodsaj** [comment]
anything i can do to help here?

**Comment by mattttt** [comment]
Passed along to a contractor to eval. Expect to here back today'ish.

**Comment by mattttt** [comment]
@nchristus just fixed this in https://github.com/raintank/grafana/issues/411
Closing.
