### ISSUE TITLE
IsGrafanaAdmin

### ISSUE THREAD

**Issue by torkelo** [raintank/grafana#31]
I am little worried that IsGrafanaAdmin is used so much, this is a temporary flag that marks a super admin that will probably replaced with a more detailed role and permission system. 

It looks like public collectors are controlled by IsGrafanaAdmin. Is there not a better way to do this? That public collectors bellow to a specific organization and the admin for that org can edit them?

I see conditionals for IsGrafanaAdmin in many places and this feels very dirty and fragile. But I am not sure, just trying to review some raintank grafana code to see if there is anything to worry about long term. This might not be a big issue, just one thing that popped into my head. 

The same thing about using isGrafanaAdmin for ApiKeys seems like a big security issue. Basically all remote collectors will have a super duper password that can do everything (or am I missing something?). 
```
	</li>
							<li ng-hide="collector.public && !contextSrv.isGrafanaAdmin"h>
								<a href="collectors/edit/{{collector.id}}">
									Edit
								</a>
							</li>
							<li ng-hide="collector.public && !contextSrv.isGrafanaAdmin">
								<a ng-click="remove(collector)">
									Delete
								</a>
							</li>
```

**Comment by woodsaj** [comment]
I agree that there are better options then using "isGrafanaAdmin" attribute.  This options was used as it was the path of least resistance.  

Ideally, i would like to just be able to use
```
ng-show="collector.org_id == contextSrv.user.orgId"
```

But the orgId is not currently passed via the grafanaBootData.

Though this looks fairly easy to fix. just need to add OrgId to dtos.CurrentUser struct, which is only used by api.setIndexViewData()

**Comment by torkelo** [comment]
@woodsaj yea, adding org_id would be very easy, I can do it or send a PR to upstream. 

raintank grafana is 209 commits behind grafana master, did try a test merge yesterday, merge conflicts did not look too bad. 

Interested in getting the raintank grafana branch up and running, do I need anything special? Fake data?

**Comment by woodsaj** [comment]
https://github.com/grafana/grafana/issues/1907

**Comment by woodsaj** [comment]
grafana upstream now exposes the org_id via the grafanaBoot data.
Just need to update the frontend code to use it.
