### ISSUE TITLE
Remove title from events panel config

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#310]
Instead of the title appearing as part of the panel, we'd like to move it up into the collapsable row:

**before**
![screenshot 2015-07-07 17 05 39](https://cloud.githubusercontent.com/assets/2886187/8557329/89248e66-24ca-11e5-9f8a-ee5aec5fe527.png)

**after**
![screenshot 2015-07-07 17 05 57](https://cloud.githubusercontent.com/assets/2886187/8557328/86fd281e-24ca-11e5-8760-6d50a3450280.png)

This also has the added benefit of looking much nicer on the panel embed on Collector Summary screen.

**Comment by nopzor1200** [comment]
This still needs to be done. Obviously a really easy fix.

**Comment by mattttt** [comment]
This still needs to be done.

**Comment by mattttt** [comment]
Fixed in https://github.com/raintank/grafana/pull/369
