### ISSUE TITLE
Loading state for events in Endpoint Summary

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#315]
While improving on the events on Endpoint Summary (and linkage to Event Panel), I wanted to introduce some subtle loading animations to convey that events were still being lazy loaded (even though the page was painted).

![event-loading-animation](https://cloud.githubusercontent.com/assets/2886187/8575501/568f01b6-256a-11e5-91ab-184169ff457b.gif)

This is all CSS keyframes, no JS. I introduced a new made-up state called ```eventReady```, would like each Event count to display only when available - and leave the loading states going otherwise. 

When that works, I'll circle back and make sure there is an end to the animation (should it time out)

**Comment by mattttt** [comment]
This is in: https://github.com/raintank/grafana/tree/loading-text-animation-events

**Comment by nopzor1200** [comment]
Is this going into master Matt? Still really nice to have, though thankfully these items are loading almost instantly now on prod (as opposed to 5-10 seconds for packets ~50 collectors)

**Comment by mattttt** [comment]
talked to @woodsaj today and he said he could bang this out pretty quickly.

**Comment by woodsaj** [comment]
wired up.  I also merged master into this branch so it should be ready to merge back into master if you are happy with it.

**Comment by mattttt** [comment]
This is looking great, but one thing. In the case of NODATA, the loading animation will just run forever, even though there aren't any events to come through, right?

![events-loading](https://cloud.githubusercontent.com/assets/2886187/9265537/6f9a1ef2-4202-11e5-8fa9-a22c2a8e5ce9.gif)

Once thats put in place, I'd say we can go ahead and merge into master. L

**Comment by woodsaj** [comment]
the issue here was simple that the animation ran forever when the graphite query failed.  This is now resolved.

**Comment by mattttt** [comment]
Excellent, closing ticket. Thanks Anthony.
