### ISSUE TITLE
TestAdvanceWithUpdateOffset fails test

### ISSUE THREAD

**Issue by woodsaj** [raintank/grafana#318]
master is broken to due to:

--- FAIL: TestAdvanceWithUpdateOffset (1.04s)
	ticker_test.go:25: waited 8ms for ticker to advance to 1970-01-01 01:59:55 +0000 UTC, but only went up to 1970-01-01 00:59:55 +0000 UTC

This was introduced in: https://github.com/raintank/grafana/commit/4fc7e0979355cc51ceaf6a0785ec6c54af5c4edf

**Comment by Dieterbe** [comment]
sorry about that. fixed in 30377d917ead6596a37b1f1107d520f9cc27c75e
