### ISSUE TITLE
Basic Quota support

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#321]
We need basic quota support for the following items. They can be on a per Org basis (no need to think about per user quotas initially, I don't think)

1. Endpoints
2. Collectors
3. Users

We will have default quotas for both (I don't care if the defaults are just MySQL defaults initially)

We need the ability to tweak (generally upwards) Endpoint/Collector quotas on a per org basis. (I don't care if we have to manually do an UPDATE query initially)

Not necessarily the best way to do this in the long term, but having something in place in the short term is important in order to up the volume on early access.

**Comment by woodsaj** [comment]
this has been merged into master.
https://github.com/raintank/grafana/pull/339
