### ISSUE TITLE
CSS - Make sure all raintank overrides are in /rt folder

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#327]
The only main difference between raintank and grafana (currently) is the font declaration and variable declarations on light/dark, but we should do a comparison on all Grafana CSS and make sure that the buck stops there.

I noticed a new DarkGrey that doesnt appear in Grafana master, so it's worth checking this.

**Comment by bulletfactory** [comment]
the variablesdark.less and variables.light.less now match grafana's. 

Originally, the new raintank specific variables were appended to the bottom of varibles.dark and variables.light files. I decided to create new "raintank.variables.dark.less" and "raintank.variables.light.less" to store all raintank-specific variables. 

This should keep the grafana variables files exactly as they exist in grafana/grafana. Going forward we shouldn't have to touch those files and now only use raintank.variables.dark/light.

Does this make sense and seem like the right direction?

**Comment by mattttt** [comment]
This is great, as it means we can pull upstream Grafana without dealing with merge conflicts. Makes sense to me.

**Comment by bulletfactory** [comment]
pinging @Dieterbe

**Comment by Dieterbe** [comment]
@bulletfactory what's up, i don't know much about this stuff.

**Comment by bulletfactory** [comment]
I need to double check some of the wayward less files to compare (there are
a ton in bootstrap), but should be complete. The idea is to have all css as
grafana-proper, and raintank overrides only in the rt folder.

**Comment by Dieterbe** [comment]
sounds good to me. but is there anything you wanted from me? (if you want advice on how good this approach is, i'ld ask anthony or torkel)

**Comment by bulletfactory** [comment]
Appreciate the offer. I think we're set, I just got pulled away from it last week. 

I just need to diff all the less files to see if there are any classes we overwrote (shouldn't be, but can't be reckless; need to confirm). I don't see any downsides to this approach, since raintank styles are called after all the grafana styles. What do you use to diff a dir of files?

**Comment by Dieterbe** [comment]
`diff -r` maybe but that assumes that changed files still have the same name at least

**Comment by mattttt** [comment]
hehe, you guys are silly ( @bulletfactory & @Dieterbe ). Wasnt that ping in response to @Dieterbe asking people to ping him on tickets while testing project management software?

**Comment by Dieterbe** [comment]
k
