### ISSUE TITLE
"new endpoint" input should be more forgiving

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#329]
pasting in something like `http://stopabusingsiprefixes.org/` results in `Failed to discover endpoint.`
requiring me to take out the `http://` prefix and the `/` suffix.

we currently don't, but i think we should allow prefixes such as `http://` and `https://`, basically allow me to enter any web uri, ip, fqdn.

and perhaps use the specified scheme to explicitly enable http/https even if it's down at time of auto-discover.

**Comment by Dieterbe** [comment]
cc @nopzor1200

**Comment by woodsaj** [comment]
This seems reasonable.  The form clearly asks for `domain name` but given that when copying just the domain name from the location bar in Chrome you end up with a full url, it makes sense that we should accommodate that.

Should be pretty straight forward to do.  if the string entered contains "://" then treat it as a url and parse it to get the domain name.

**Comment by Dieterbe** [comment]
so what happens if you enter https:// and auto-discovery finds https down? @nopzor1200 mentioned it would be nice if we enabled https anyway, because the user explicitly pasted it in.
we don't even have to try to autodiscover https in that case as we'll auto-enable.

likewise if you paste in http://

**Comment by woodsaj** [comment]
if you pass http://host and it is not discovered i would think that you would want to know that.

**Comment by Dieterbe** [comment]
why? why would discovery be helpful?

**Comment by woodsaj** [comment]
i think that there is a higher probability that i put the wrong address in then there is that it I want to monitor a site that is currently unreachable.

**Comment by Dieterbe** [comment]
ok I think I agree with that and I think nothing else needs to happen here. @woodsaj and @nopzor1200 ok with that?

**Comment by nopzor1200** [comment]
I can see a few edge use cases where I am adding a URL with the intent to configure a footprint from my internal network collectors inside my network. Polling might not work from app.raintank.io. I admit that this is somewhat of an edge case for now and we an always revisit.

The more important part (which everyone seems to agree on, I think) is that we should accept 3 inputs:

1. domain name (current functionality)
2. URL (basically current functionality but correctly parse the domain, port, path, etc settings. eg. if I typed http://www.nopzair.com/travel/foo, then it'd suggest /travel/foo as a separate path setting in the config.)
3. IP address (in this case we would only do ping (and perhaps reverse DNS?)

Does this sound right? Doable @woodsaj

**Comment by Dieterbe** [comment]
> IP address (in this case we would only do ping (and perhaps reverse DNS?)

i think websites accessible via `http://<ip>` are an acceptable case that may happen once in a while, and i'ld still do http/https discovery

**Comment by Dieterbe** [comment]
> I can see a few edge use cases where I am adding a URL with the intent to configure a footprint from my internal network collectors inside my network. Polling might not work from app.raintank.io. I admit that this is somewhat of an edge case for now and we an always revisit.

so in that case it's better to have auto-discovery make it apparant that the site is currently down, which is similar to "i put in the wrong address" case @woodsaj mentioned, so i think we all agree on this too. (if auto-discovery fails, make that apparant, instead of still silently starting to monitor something we detected as down)

**Comment by woodsaj** [comment]
great.  So what is discussed here is already what has been done.

**Comment by Dieterbe** [comment]
on dev portal:
![fail](https://cloud.githubusercontent.com/assets/20774/8812488/a22e2088-2ffc-11e5-8748-70349cd897a3.png)
the given http path definitely works in browser:
![fail2](https://cloud.githubusercontent.com/assets/20774/8812507/bc2c13f0-2ffc-11e5-8f33-e56bdec33f98.png)

**Comment by woodsaj** [comment]
This does work, you must have just tested it before the latest code was deployed to dev-portal.

**Comment by Dieterbe** [comment]
ah yes, seems to work now.
