### ISSUE TITLE
dns checks on an ip succeed?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#330]
```
dieter@dieter-m6800 ~ nslookup dns.be
Server:		66.28.0.45
Address:	66.28.0.45#53

Non-authoritative answer:
Name:	dns.be
Address: 149.126.56.5

```
i can add `149.126.56.5` as an endpoint, and autodiscover enables the DNS check for it, against 8.8.8.8 
so not sure if it does a regular, or reverse dns lookup, but if i manually run a nslookup i get this:
```
nslookup 149.126.56.5 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find 5.56.126.149.in-addr.arpa: NXDOMAIN

```

however, litmus claims everything is ok:
![dns-ip](https://cloud.githubusercontent.com/assets/20774/8683572/804edfae-2a28-11e5-9fe9-1fcee44e228b.png)

what's going on?

**Comment by Dieterbe** [comment]
cc @nopzor1200

**Comment by woodsaj** [comment]
I have updated the endpoint discovery to not enable DNS checks if the endpoint is an IP.

But the actual issue of checks succeeding would be a bug in the collector.

**Comment by Dieterbe** [comment]
and we'll rewrite the collector anyway, so no need to open a ticket there.
