### ISSUE TITLE
state should be unknown if we haven't updated state recently

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#331]
in addition to last state change in monitor table, we should track last alert run, 
so that in endpoint health overview, we can show unknown state in cases where alerting has been disabled or for whatever reason we haven't been able to update the state.

so, never take state in table for granted, always look at last alert run, frequency and current time, to validate the state. also use a buffer of time to account for duration of executing alerting logic and update the db, perhaps 10s or so.

@nopzor1200 this covers what we agreed on, i think?

cc @woodsaj @mattttt

**Comment by Dieterbe** [comment]
@torkelo @woodsaj I made some progress in the above commit but I keep getting:

```
2015/07/17 21:00:40 [I] Migrator: exec migration id: create index IDX_monitor_collector_tag_monitor_id - v1
2015/07/17 21:00:40 [D] Migrator: Executing SQL: 
 CREATE UNIQUE INDEX `UQE_monitor_collector_tag_monitor_id_tag` ON `monitor_collector_tag` (`monitor_id`,`tag`); 

2015/07/17 21:00:40 [I] Migrator: exec migration id: create index UQE_monitor_collector_tag_monitor_id_tag - v1
2015/07/17 21:00:40 [D] Migrator: Executing SQL: 
 alter table `monitor` ADD COLUMN `health_settings` VARCHAR(2048) NULL  

2015/07/17 21:00:40 [I] Migrator: exec migration id: monitor add alerts v1
2015/07/17 21:00:40 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: Error 1054: Unknown column 'state_check' in 'field list'

```

interestingly, when I change the file and it recompiles and reruns I get this:

```
2015/07/17 21:05:43 [D] Migrator: Skipping migration: create monitor_collector table, Already executed
2015/07/17 21:05:43 [D] Migrator: Skipping migration: create index IDX_monitor_collector_monitor_id_collector_id - v1, Already executed
2015/07/17 21:05:43 [D] Migrator: Skipping migration: create monitor_collector_tag table v1, Already executed
2015/07/17 21:05:43 [D] Migrator: Skipping migration: create index IDX_monitor_collector_tag_monitor_id - v1, Already executed
2015/07/17 21:05:43 [D] Migrator: Skipping migration: create index UQE_monitor_collector_tag_monitor_id_tag - v1, Already executed
2015/07/17 21:05:43 [D] Migrator: Executing SQL: 
 alter table `monitor` ADD COLUMN `health_settings` VARCHAR(2048) NULL  

2015/07/17 21:05:43 [I] Migrator: exec migration id: monitor add alerts v1
2015/07/17 21:05:43 [migrator.go:134 func·001()] [E] Migrator: exec FAILED migration id: monitor add alerts v1, err: Error 1060: Duplicate column name 'health_settings'
2015/07/17 21:05:43 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: Error 1060: Duplicate column name 'health_settings'
```

please help me out with this.

also @woodsaj we'll need a way to make sure that whenever we show the "state" and we pull the state from the db, we also look at this field, and compare it to now() and frequency, and switch the state to unknown if the last update was too old.  not sure what's the best way to assure this is done consistently. could you do this or point me in the right direction

**Comment by woodsaj** [comment]
I commented in your commit what the likely issue is.

As for modifying the `state` field, i would handle that in the GetMonitorById() and GetMonitors() functions.
When creating the DTO response i would just adjust the state field to be Unkown if check_state is more (frequency * X) seconds old.

What are your plans for setting this field. Are you going to update on every check or only every X checks to reduce the load on the DB?

**Comment by Dieterbe** [comment]
> Are you going to update on every check

that's the plan.  I think we'll be able to a whole lot (at least thousands) of updates per second before this becomes a problem, so once we're past 1k customers this might become an issue and then we'll figure out something better (in memory state, sharded db, ...)

**Comment by Dieterbe** [comment]
@woodsaj I think the `Unknown column 'state_check' in 'field list'` comes from the `migration.OnSuccess` callback from the "monitor add alerts v1" migration.  It uses `m.Monitor` which now has the `state_check` field in the Go code, but the database (at that step of the migrations) doesn't have the field yet.  I'll try putting my migration before that one

**Comment by Dieterbe** [comment]
aaaaaaaarg!
so `Name: "state_check", Type: DB_DateTime, Nullable: false` works in devstack just fine.
but circi throws out ` exec FAILED migration id: monitor add state_check v1, err: Cannot add a NOT NULL column with default value NULL`
(*nevermind the fact that other fields are defined the same way, e.g. `{Name: "state_change", Type: DB_DateTime, Nullable: false}` in monitorV3 and monitorV4 and the migrator never complains about that*)

so I thought ok maybe i just need to do 
```
-               Name: "state_check", Type: DB_DateTime, Nullable: false,
+               Name: "state_check", Type: DB_DateTime, Nullable: false, Default: "1970-01-01 00:00:00",
```

but this then results in
```
2015/07/22 13:17:03 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-01-01 00:00:00' at line 1
```

mysql providing superhelpful errors as usual.

so ok then i thought maybe if i change this
```
diff --git a/pkg/services/sqlstore/migrator/migrator.go b/pkg/services/sqlstore/migrator/migrator.go
index 57ec5dd..1e86acf 100644
--- a/pkg/services/sqlstore/migrator/migrator.go
+++ b/pkg/services/sqlstore/migrator/migrator.go
@@ -30,7 +30,7 @@ type MigrationLog struct {
 func NewMigrator(engine *xorm.Engine) *Migrator {
        mg := &Migrator{}
        mg.x = engine
-       mg.LogLevel = log.WARN
+       mg.LogLevel = log.DEBUG
        mg.migrations = make([]Migration, 0)
        mg.dialect = NewDialect(mg.x.DriverName())
        return mg
```
i would actually be able to see the sql queries being executed maybe? but nope

@woodsaj do you want to be my savior? this is your chance to shine :)

**Comment by woodsaj** [comment]
I am pretty sure the 'Default' field is not implemented. you would need to check with @torkelo 

sqlite3 will not let you alter a table and add a column that is set to nullable=false and doesn't have a default.

Just set `Nullable=true`. Within GO there is no 'null' value for a time.Time variable.  If the DB had null, GO would assign the zero time.Time value, which is 1970-01-01 00:00:00 anyway.

**Comment by woodsaj** [comment]
also, you can see the SQL queries being executed if you set 'app_mode = development' in your grafana config.  sql statements are then logged to data/log/xorm.log

**Comment by woodsaj** [comment]
actually, that wont show the statements of the migrator.  Look at the sqlstore package for how to enable logging the sql statements.

**Comment by woodsaj** [comment]
Also, i do think that the problem you are seeing is due to the OnSuccess callback expecting the table to already have the state_check field.  
This could be fixed by changing the DB update from 
`sess.Id(mon.Id).Update(mon)`  to `sess.Id(mon.Id).Cols("health_settings").Update(mon)`

**Comment by Dieterbe** [comment]
I tried that change, and moved my new migration behind the "monitor add alerts v1" again, but then I get the dreaded `2015/07/23 09:41:55 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: Error 1054: Unknown column 'state_check' in 'field list'
` again

**Comment by Dieterbe** [comment]
needs #360

**Comment by torkelo** [comment]
?
