### ISSUE TITLE
make instance id's settable through config

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#332]
and use current approach as a fallback.
otherwise it's hard to work with them in dashboards.
we can then use config management to assign id's such as web-1, web-2, alert-scheduler-1, etc.

**Comment by woodsaj** [comment]
we already have an instance-id used for the collector-ctrl.  It stores the instance_id in data-dir/instance-id

https://github.com/raintank/grafana/blob/master/pkg/api/socketio.go#L220-L240

maybe we can move this to the settings package.

**Comment by Dieterbe** [comment]
1) looks like that code saves it to a datapath which is probably the same for different instances on same host, and so they override each other's files. unless they have a different datapath setting in config
2) I only want to have randomly generated stuff like `instanceId = uuid.NewV4().String()` as a fallback, and prefer human readable and comprehensible instance id's. and in the fallback case i think host+pid is better than a uuid because it's shorter and makes troubleshooting a bit easier.

do you think the instance-id for collector-ctrl should be the same instance id as used in statsd metrics? i.e. have it be the global instance-id for the entire grafana process? (I think so)

are you ok with making it configurable in config, and fallback to uuid or host+pid, and which do you prefer?

**Comment by woodsaj** [comment]
host+pid doesn't work for the collector-ctrl as it needs the instance-id to be persistence across restarts.

You can already set the instance-id to whatever you want, just write it to data-path/instance-id and it will be used. it does not need to be a uuid, i just used uuid's as i wanted something that would be unique,

**Comment by Dieterbe** [comment]
hmm i'm not seeing a nice way to combine collector-ctrl-id and statsd-id then. does the current uuid approach support running multiple instances on the same host? it seems the uuid gets written to the same path.

**Comment by woodsaj** [comment]
if you were running multiple instances on the same server you wouldn't have them all use the same datapath.  The datapath is used for:
- sqlite db (which you wouldnt be able to use with multiple instances) 
- default log path
- xorm log path (when app_mode=development xorm logs all sql queries)
- file based sessions

Just to separate logs, multiple instances should all use a separate dataPath

**Comment by Dieterbe** [comment]
oh, we should clarify that in http://docs.grafana.org/installation/configuration/#paths and in conf/defaults.ini , that multiple instances should have different paths.

what we could also do is, instead of forcing users to make sure they specific different paths, have them specify a "base path" (could be same for multiple instances), as well as an instance key (which must be different), and then put those logs/sqlite in `base-path/instance-key/`, that would also provide us with an instance key to use for collectorctrl as well as statsd metrics.

**Comment by woodsaj** [comment]
forcing users to use `base-path/instance-key` is not a good idea.  The whole reason for having the paths configurable is so that users can set them however they want.

I agree that when running multiple instances on the same server (which would be rare) base-path/instance-id is a good approach, but it can just as easily be achieved by just setting the dataPath to `basePath/instance-key`

**Comment by Dieterbe** [comment]
ok so how about this:
in config/defaults.ini
```
instance-id = default
```
with a note that *all* grafana instances should have a unique instance-id, so they can change it in their config.

we then use instance-id for both statsd and collector-ctrl.
it also means we can remove the reading/writing to that id file cause now it's just in the config.

and in the path section, we add a notice to make sure that people set unique paths in case of multiple instances on same machine.

**Comment by woodsaj** [comment]
sounds good to me.  Clean and simple.
