### ISSUE TITLE
still seeing a few http ok's after I kill the server

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#347]
step 1: kill web server:
```
[dieter@dieter ~]$ ./bad-http-server 0.0.0.0:8888
will listen for http traffic on 0.0.0.0:8888
^C[dieter@dieter ~]$
```
step 2: wait 4 minutes minutes.
step 3: for a couple of minutes it claims there are still 2 ok's next to 19 errors:
(this is with 15minutes ago to a minute ago)
![too-long-down](https://cloud.githubusercontent.com/assets/20774/8800986/7b5be4d0-2fb7-11e5-8f78-9fe2b66dc48c.png)
in the endpoint summary, i believe it does correctly show 0 OK events

**Comment by nopzor1200** [comment]
Which endpoint/dashboard can I reproduce this on? msg it to me on slack if you'd like. I'd like to play around with it.

**Comment by woodsaj** [comment]
my first thought is that the time on some of the collectors is wrong.  but will look into it more.

**Comment by nopzor1200** [comment]
can you validate the time on all the prod collectors are the same and ntp is running?

**Comment by ctdk** [comment]
All production machines in GCE have NTP and have been synced up; however, not all collectors have it. Rectifying the situation. Some of the Amazon collectors have changed IPs, so I'm going in and running chef on those now.

**Comment by ctdk** [comment]
Aside from any potential date problems with the Amazon collectors, it seems that only one (seattle) had an inaccurate clock. NTP is now explicitly in the base recipe, instead of taking it for granted that it's part of the base system (which it generally is).

**Comment by ctdk** [comment]
All prod collectors have the correct time, and ntp is running.

**Comment by ctdk** [comment]
@dieterbe, can you test and see if any more OKs come in when they shouldn't?

**Comment by Dieterbe** [comment]
I verified this issue no longer manifests, both on dev and prod. thanks. they jump straight to 100%  error now.
