### ISSUE TITLE
Tag form broken in Grafana screens

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#362]
The raintank tag styles are appearing in the dashboard sections:

![tags-dashboards](https://cloud.githubusercontent.com/assets/2886187/8856456/e86f6f4c-311f-11e5-9636-be8569d8416b.gif)

But they shouldnt be there. Dashboards should look like core grafana tag interface:
![tags-dashboards-grafana](https://cloud.githubusercontent.com/assets/2886187/8856466/f3f6c130-311f-11e5-9d78-8f0dc0b576aa.gif)

This is likely due to the raintank tag css styles being too broad - and should be scoped to only appear on custom raintank pages:

Example:
![tags-endpoints-raintank](https://cloud.githubusercontent.com/assets/2886187/8856508/323034d6-3120-11e5-937b-6c25407c8e5b.gif)

Fix: Moving the raintank tag styles into rt-less, and then scoping them properly on any pages using it in: https://github.com/raintank/grafana/tree/master/public/plugins/raintank/features/partials
Problem: It's all handled by bootstrap and I dont know how to style it differently:
`<bootstrap-tagsinput ng-model="endpoint.tags" tagclass="label label-tag" placeholder="add tags"></bootstrap-tagsinput>`

**Comment by mattttt** [comment]
@nchristus After the event panel, can you hop on this?

**Comment by nchristus** [comment]
@mattttt you bet!
