### ISSUE TITLE
track how many emails sent to each org/user

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#374]
so that if they get too many emails, we can reach out to them to:
* help them/advise them on how to tune alerting configuration to be less noisy, a prerequisite to being more relevant and useful. also should build a much stronger relationship between us and them.
* reach out to them and apologize if we suspect the problem is on our side.

first step could be using mysql and have a record for each day, increment it for each message.
we could also log into ES for all sorts of reporting

when/if we get a datasource for mysql or ES we could also visualize this for them in their org section.
but for all i care, i will personally just run a query each day (without viz) to see how we're doing and reach out when appropriate.

**Comment by Dieterbe** [comment]
49a415175d865834cf61ff23a06a8825b3c4d184
+
```
knife ssh name:grafana-* "sudo grep 'sending email' /var/log/grafana/grafana.log" -a cloud_v2.public_ipv4 | grep $(date '+%Y/%m/%d')
```

**Comment by mattttt** [comment]
Nice!
