### ISSUE TITLE
tracking alerting state changes

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#375]
I want to see graphs annotated with state changes (ES annotations)
* as a user, i'ld broadly like to see the kind of info we show in the alert notification (which btw, should be extended with some more details)
* as a litmus operator I'ld like to see the above, but i also want debug information (such as input data used) in case the alert didn't behave as expected.

as long as there's nothing too private in the latter, we could include all this data into single events, I think

**Comment by nopzor1200** [comment]
This is a great idea. Can't believe we didn't think of this before.

Would be cool to do even with the feature 'as-is' in Grafana.

(when I say as-is I mean the limitation of ALL annotations showing up on ALL panels which I think its the case right now. Perhaps something to improve in upstream Grafana)

**Comment by nopzor1200** [comment]
@Dieterbe

**Comment by Dieterbe** [comment]
are you saying we can't include $endpoint in the search string configured for ES annotations?
ALL on ALL is probably acceptable, except for those customers who have a lot of endpoints.

**Comment by woodsaj** [comment]
i think raj means that annotations are scoped to a dashboard, not a panel.  This would be fine on a protocol specific dashboard, eg rt-endpoint-ping, as it would make sense to show the annotations on all panels.  But on the rt-endpoint-summary you would have annotations for ping, dns and http showing on all panels which would be confusing.

Writing the data to ES should be pretty straight forward and this was always the plan, it just hasnt happened yet.

**Comment by nopzor1200** [comment]
@woodsaj yep thats what i meant should have been clearer

@woodsaj would anything have to be done to make the current "events" usable as annotations? (ie dieters first original use case. I assume basically nothing?). When you say "writing the data to ES should be pretty straight forward" I assume you mean "app events" (ie. dieters second original use case) - things like updating HTTP check, adding an endpoint etc etc?

would be really nice if we scope annotations by panel. Something for @torkelo to think about I suppose there seems to be a couple of grafana issues on it eg. https://github.com/grafana/grafana/issues/133 and https://github.com/grafana/grafana/issues/1959 and https://github.com/grafana/grafana/issues/717

**Comment by woodsaj** [comment]
we would need to add a datasource to serve the annotations.  Even though the events are stored in ES, we cant just gives uses full access to our ES cluster.

**Comment by Dieterbe** [comment]
while we don't have panel-scoped annotations and so probably wouldn't expose them to users yet (?), i could already load them in admin-only dashboards. this would be really helpful for me in looking into matching up notification events with the graphs of the data, especially if i could activate the annotation and get a popup with more details that include which probes fired. i presume for @matt and marlene this would be useful as well, helping out the people with onboarding identify why they alerts fired and if it's on us or them.

so what needs to happen:
1. grafana needs to emit structured events (should be easy?)
2. something moves the events into ES (is this raintank-metric's job? or something else? heka?)
3. some sort of proxy that uses authentication+authorization so that:
   * users can only see events from their org
   * a "debug" property in the structured event from ES is stripped.
   * admins like us should be able to see events from anyone, and any data in a "debug" field in the doc should be shown as well.
   * an elegant way perhaps to implement the special "debug" field would be the ability to set orgId restrictions on individual fields/sub-documents.

I would like this to move forward soon. 3 sounds like @woodsaj's specialty, I can take care of 1+2.

**Comment by woodsaj** [comment]
look like we can just use the existing Elasticesearch datasource already in grafana.  The query format is well structured that we can insert a filter on OrgId.

https://github.com/raintank/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.js#L71-L78

So we just need to make sure that the format we use for the events we store is inline with what this datasource expects.

**Comment by Dieterbe** [comment]
if we leave it all up to the query format, wouldn't people be able to remove the orgId clause in their own custom dashboards, and get other customer's data?

**Comment by woodsaj** [comment]
The orgId would be inserted within the grafana back-end that is proxying the request to ES.

**Comment by torkelo** [comment]
What log messages are taking up most space? request logs? Do we have debug logging on on dev - portal or production?

**Comment by Dieterbe** [comment]
@torkelo i think you mistakenly posted your comment in the wrong ticket.
@woodsaj i can update the nsq branches to also submit alerting state changes into ES. the only thing is i'm not quite sure on the format. can you help me out? :
```
{
@timestamp: <unix ts in milliseconds>
desc: <title (same as email subject)>
content field for extra info?
org id?
tags: [
"monitor_id": 123,
"endpoint_id": 456
}
```

**Comment by woodsaj** [comment]
https://github.com/raintank/raintank-collector/blob/metric-schema/serviceManager.js#L254-L269
