### ISSUE TITLE
autodiscovery skipped?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#376]
on dev, new addpoint, paste in `http://metrics20.org:8888/bad/0`
(this endpoint always returns 200 OK also at time of testing)
results in
```
Discovery Skipped.You can manually configure your endpoint below or start over to enter a new domain.
```

1) we should tell the user why we skipped discovery
2) why did it skip in this case? it shouldn't

**Comment by bulletfactory** [comment]
I see tested your address in dev and saw the same result. auto discovering
http://metrics20.org, without port/path seemed to auto discover
successfully however

**Comment by woodsaj** [comment]
This is a frontend bug.  Discovery is successful and the checks are populated with the correct settings, but for some reason "discovery skipped" is displayed.

**Comment by mattttt** [comment]
I'll look into this one. I also want to include some better feedback on the front-end when the discovery is taking more than ~5s (similar to the loading messages on list screens)

**Comment by woodsaj** [comment]
@mattttt want me to take care of this. I am pretty sure it is a JS issue in the controller.

**Comment by mattttt** [comment]
@woodsaj Yes please - I took a look but dont know how to address.

**Comment by woodsaj** [comment]
this should be fixed by: https://github.com/raintank/grafana/pull/417
