### ISSUE TITLE
why can you rename endpoint only after it's been created?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#377]
i've been using litmus since forever and i just found out you can rename endpoints.
i never knew because when you add an endpoint, you do discovery etc, there's no option to give it a different name.
but when you go to it after creating, and configuration tab, there you can change the name

**Comment by woodsaj** [comment]
You can change the name. Just click "start over" and input a different name.

**Comment by Dieterbe** [comment]
that's not "just changing the name though", if you then input a different "name" it will run autodiscovery on that name, that's not what i want, i want to just change the name.
