### ISSUE TITLE
numbers of collectors don't match on dev

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#378]
![huh](https://cloud.githubusercontent.com/assets/20774/8962004/964bb2ea-3618-11e5-9163-5fbbfd0a3f00.png)
5 or 6?

**Comment by Dieterbe** [comment]
`/endpoints/summary/470`

**Comment by woodsaj** [comment]
this shows on 5 results for me.  

@Dieterbe 
Did you change the the tags on collectors?
If a check is configured to run on all collectors using tags, and you add or remove a tag from a collector it can take up to 5minutes for the change to take affect.

**Comment by Dieterbe** [comment]
hmm yeah it's 5 now.
maybe, i don't remember.
let's close for now, if i see it again and it's not due to tag change i'll reopen.
