### ISSUE TITLE
changing endpoint name changes hostnames

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#379]
in endpoint config i changed the name to a name i liked more.
little did i know, this also changed the hostname of the endpoint in the http/ping monitors, thereby breaking my monitoring, making everything critical and leaving me puzzled as to why.

**Comment by Dieterbe** [comment]
interestingly, i can then just change the hostnames back to what they should be, and at least i can keep my custom name.

**Comment by bulletfactory** [comment]
We also have different terminology for the field depending on if you're
creating a new endpoint, or configuring an existing. It's called Domain
Name when adding new and Endpoint Name when changing an existing. This can
be confusing, though It's probably not necessary to have a 2 fields; one
that's a "friendly name" and the other that's the domain name. Thoughts?

**Comment by nopzor1200** [comment]
Lets chat about this today

**Comment by nopzor1200** [comment]
100% agreed @Dieterbe this is extremely confusing. Matt and I have actually discussed this very issue before. Am on the same page here.

**Comment by Dieterbe** [comment]
k

**Comment by woodsaj** [comment]
this has been resolved.

**Comment by Dieterbe** [comment]
cool. seems to work fine now indeed.
