### ISSUE TITLE
Alphabetize Collector List

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#392]
In the endpoint config, collector list should be ordered in some way. I'm suggesting we alphabatize.

It looks like this currently:
![screenshot 2015-08-04 12 06 21](https://cloud.githubusercontent.com/assets/2886187/9065687/3e5b5dfa-3aa1-11e5-9215-6e5f821579e1.png)

**Comment by Dieterbe** [comment]
![pkvkcol](https://cloud.githubusercontent.com/assets/20774/9090739/5aa8756e-3b9c-11e5-9caf-cfa60c818a03.jpg)
