### ISSUE TITLE
Display Alert Status on Endpoint Summary

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#393]
Alert Status is currently only exposed within the config of each check, and needs to be shown on the endpoint summary screen. Need to implement this pretty quickly, so opening up the issue to explore some ideas.

**Comment by mattttt** [comment]
![screenshot 2015-08-04 12 42 35](https://cloud.githubusercontent.com/assets/2886187/9066539/4cbe8674-3aa6-11e5-8821-7de671810515.png)

**Comment by mattttt** [comment]
![screenshot 2015-08-04 12 43 14](https://cloud.githubusercontent.com/assets/2886187/9066550/635d644a-3aa6-11e5-84a1-7c59e53d2964.png)

**Comment by mattttt** [comment]
![screenshot 2015-08-04 12 43 39](https://cloud.githubusercontent.com/assets/2886187/9066558/754f7abc-3aa6-11e5-9578-6eee39e3971f.png)

**Comment by mattttt** [comment]
I like the first one. We dont say the word alerting, but I think the icon can be sufficient here. Also, I like adding in a tooltip to show what emails are configured.

**Comment by mattttt** [comment]
An example of how it could step down responsively at the smallest breakpoint:
![screenshot 2015-08-04 13 17 06](https://cloud.githubusercontent.com/assets/2886187/9067399/29f6969a-3aab-11e5-907f-bfba780ff756.png)

**Comment by Dieterbe** [comment]
+1 first one

**Comment by mattttt** [comment]
[Note: Deleted the other options to clean up this ticket. Option 1 is the winner]

@nchristus Can you please go ahead and tackle the addition of the alerting stuff to the Endpoint Summary page? You can use dummy text to do the styles, and we'll wire it up to the controller later. Needs to be responsive, as outlined above. 

The icons you need are already in the font: `icon-rt-alert`, `icon-rt-alert-disabled`

What questions am I not asking?

**Comment by nchristus** [comment]
Added the initial styles and small screen layout.

![nchristus-alert-status-endpoint-summary_small](https://cloud.githubusercontent.com/assets/136611/9127938/4a7df27c-3c87-11e5-8d42-4209da352662.png)

@mattttt what should we do in this middle-sized layout? 

![nchristus-alert-status-endpoint-summary_med](https://cloud.githubusercontent.com/assets/136611/9127963/916faefa-3c87-11e5-9eb0-d830fb48a503.png)

**Comment by bulletfactory** [comment]
Alerting is tied to status (ie: critical to OK would send you an alert if it was configured) - so it would make sense to have it visually linked together, positioning it below the status at the far left. 

So in the middle breakpoint the left column will have 3 rows. checktype, status, alerting.

Anyone have a counter to that suggestion?

**Comment by mattttt** [comment]
No, I think that sounds good. Let me do a quick mockup to make sure it looks good.

**Comment by mattttt** [comment]
I did two versions, and Trent had the right recommendation. Let's go with this one:

![untitled__canvas_3](https://cloud.githubusercontent.com/assets/2886187/9176625/5b6b6da0-3f5a-11e5-9045-3eab5af975b5.png)



For reference, here is the other one, but it reads much less organized and more cluttered:
![untitled__canvas_4](https://cloud.githubusercontent.com/assets/2886187/9176643/7c1d7c8c-3f5a-11e5-9bdb-d1e252c764a5.png)

**Comment by nchristus** [comment]
Agreed, this looks great. I'll work on getting it implemented.

Thanks for doing the mockup.

**Comment by nchristus** [comment]
Updated screenshots. Still testing, but looking good so far.

![nchristus-alert-status-endpoint-summary_small](https://cloud.githubusercontent.com/assets/136611/9188827/7fd53de6-3fa6-11e5-855c-cb4a9d6a9fdb.png)
![nchristus-alert-status-endpoint-summary_wide](https://cloud.githubusercontent.com/assets/136611/9188828/7fda2b8a-3fa6-11e5-8e90-733852af3459.png)

**Comment by mattttt** [comment]
Looking great.

**Comment by nchristus** [comment]
@mattttt I just pushed some updates to branch 'nchristus-alert-status-endpoint-summary'.

Would you mind taking a look at how the 'Ping' row is working before I roll it out to the other rows (lots of markup to change)?

**Comment by mattttt** [comment]
@nchristus Sure, standby

**Comment by mattttt** [comment]
@nchristus I think it looks pretty fantastic. Just one small things - when the sidebar is open, it's got a weird breakpoint. 

So instead of this:
<img width="788" alt="raintank_-_new_dashboard" src="https://cloud.githubusercontent.com/assets/2886187/9215025/30587bc0-4073-11e5-87ca-348bb1b1e796.png">


It should be this (with alerts on a single line):
<img width="652" alt="raintank_-_new_dashboard" src="https://cloud.githubusercontent.com/assets/2886187/9215017/0e129dde-4073-11e5-99b6-95bbc889b9cd.png">

With the menu closed, works like a charm.

**Comment by nchristus** [comment]
@mattttt Ah, good catch! Just pushed a fix. Let me know how it looks now.

**Comment by mattttt** [comment]
@nchristus Just tested, works great. Go ahead and roll out to the rest. Thanks!

**Comment by nchristus** [comment]
Great, new update pushed. Rolled out to remaining rows. Looking great.

**Comment by mattttt** [comment]
Talked to @woodsaj this morning and wiring it up to the controller should be pretty straightforward. He said it would take him ~30m, and would likely take me the better part of a day, so I'll elect he do it.

**Comment by woodsaj** [comment]
wired up, also merged master into this branch so that it is ready to merge back into master when you are happy with it.

**Comment by mattttt** [comment]
This is coming together, a few more tweaks:

<img width="1062" alt="raintank" src="https://cloud.githubusercontent.com/assets/2886187/9265618/d894a2be-4203-11e5-9412-3642adabb4b3.png">

1. Move the "configure now" line to the right a it, so it matches indentation of the other sections.
2. Add a tooltip and a link to the "Enabled"
3. Fix these swapped icons on the right
4. Add a tooltip with email addresses on the "[x] recipients"

**Comment by nchristus** [comment]
@mattttt pushed up an update for issues 1, 3, and 4. 

Would you provide a little more info/direction for issue 2?

**Comment by mattttt** [comment]
@nchristus You're a beast! #2 I can take care of tomorrow. I have to give that one a little thought still.

**Comment by mattttt** [comment]
Ok, this is in solid shape - just one more small tweak before we can deploy. I need to add in a message that says "No recipients specified".

![screenshot 2015-08-17 18 33 19](https://cloud.githubusercontent.com/assets/2886187/9318238/d87c7978-450f-11e5-802f-44f82f2e0237.png)


Also I'd like to remove the brackets an quotes from the array:
![screenshot 2015-08-17 18 31 56](https://cloud.githubusercontent.com/assets/2886187/9318241/dbc24126-450f-11e5-9e0b-bc7d370d0aa9.png)

**Comment by mattttt** [comment]
@woodsaj I putzed around with it for a bit today, but didnt put the time into figuring it out. Is this super easy for you?

**Comment by woodsaj** [comment]
for these type of formatting issues, it is easiest to just create a scope function to process the data and return it how you want, which is what i have done.

The getNotificationEmailsAsString() function gets the array of email address from getNotificationEmails() if the list is empty, returns "no recipients specified". otherwise it iterates through the list to check if the email is in the format `"display name" <user@domain.com>` and if so just uses the display name, otherwise the whole email address is used.  Finally, we concatenate the list of addresses into a string, with each item separated with ", "
