### ISSUE TITLE
compressing grafana logs

### ISSUE THREAD

**Issue by ctdk** [raintank/grafana#402]
Grafana has a built-in log rotation which seems to work pretty well for what we need, but when debug logging is on it spews out a *lot* of logs. It automatically rotates the logs when they reach (by default) 256MB, but by default it keeps these logs for 7 days. That needs to be lowered in any case, and can be done in the config file, but I think we should consider compressing the logs when we rotate them.

My inclination is to just run gzip on them after the rotation has happened, but we could also use golang's compression libraries to compress the old logs. Also, should this be an optional compression, or just compress then without giving the option of not compressing?

**Comment by Dieterbe** [comment]
why does grafana have to worry all this? isn't log rotation a solved problem, i would rather *remove* log rotation code out of grafana. (except for renewing file descriptors on a given signal).
or am i missing something?

**Comment by ctdk** [comment]
That would be my natural inclination, except that grafana with debug on spews *so* much that even rotating once a day raises issues with running out of disk space.

**Comment by Dieterbe** [comment]
and we can't run the grafana logrotate schedule more frequently? or is it somehow fixed at 1/day?

**Comment by ctdk** [comment]
I thought daily was the most frequent you could do it, but I was mistaken - hourly is possible (but I need to check and make sure the cookbook won't flip if I try that). That's way better than trying to do it ourselves. Checking now.

**Comment by woodsaj** [comment]
I really think that this discussion needs to be moved to upstream grafana.

**Comment by ctdk** [comment]
It's ended up being an irrelevant discussion anyway. I'm just going to close this out.

**Comment by Dieterbe** [comment]
why is it irrelevant? what's the outcome?

**Comment by ctdk** [comment]
Because I thought we decided that it was better to just run logrotate more often and not try to extend grafana's functionality here. Do you all think we should take this over to grafana/grafana then?

**Comment by Dieterbe** [comment]
ah no, i just didn't know the decision had been definitely made to just use logrotate. so that sounds good to me.
