### ISSUE TITLE
default dashboard assumes litmus hosted by raintank inc

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#412]
default page when logging in first time mentions "join early access program", this is a raintank inc specific thing. remember that people can run the raintank platform (with litmus) themselves in which case this doesn't make sense.

**Comment by nopzor1200** [comment]
Yes. @mattttt and I have been talking about this. 

The idea is to transition to not taking over the "Dashboards" top level left menu.

Instead, as Litmus is refactored as a plugin, it will occupy a Litmus-specific top level menu as defined within the plugin.

You will get the "Litmus home dashboard" when you click the Litmus top level menu item.

I think all three of us are on the same page.

**Comment by Dieterbe** [comment]
i get that, but don't see how it answers the concern in OP.
since anyone can run litmus internally, or offer it as a service (we do it, others should be able to do it too), messaging like "join <raintank> early access program" should be optional. will it be a setting of some sort so that we can show that in our deployment of litmus, and others wouldn't show anything , or others would be able to mention whatever they want (their own early access program or whatever) ?

**Comment by nopzor1200** [comment]
The scope of this is really about the use case of someone downloading the Litmus client-app, and running it inside their Grafana. They will still require an "early access @ raintank" login to actually use the app.

I don't think we should be optimizing for other use cases, can discuss in strategy

**Comment by woodsaj** [comment]
The home dashboard is just static JSON, anyone with an on-prem deployment can customize it however they want.  The RaintankCTA panel is a raintankSaaS specific panel.
