### ISSUE TITLE
move raintank email notifications to own directory

### ISSUE THREAD

**Issue by woodsaj** [raintank/grafana#415]
The email notifications used by raintank are significantly different from upstream grafana.  Keeping them in the same location is a pain for merges.

all templates should be moved into their own directory.  `public/plugins/raintank/emails` would probably make sense.

**Comment by mattttt** [comment]
@woodsaj Is this something I can do myself, or is there backend changes to support it as well? At the very least, I'll go ahead and relocate the directories.

**Comment by woodsaj** [comment]
I am happy to make the change if you want, I just really wanted to make sure there were no in-progess issues that were modifying the templates. 

 Will also need to get @ct involved as well for when we deploy the change as we would need to update the templates path in the grafana config 
```
[emails]
templates_pattern = emails/*.html
```

**Comment by woodsaj** [comment]
I have updated the templates in  https://chef.raintank.io/environments/development_gce/edit
