### ISSUE TITLE
Add default tags for region for all public collectors

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#42]
Tags as follows:-

USA
EMEA
ASIAPAC

**Comment by nopzor1200** [comment]
Users should be able to customize / override these tags, but we should ship with these defaults

**Comment by woodsaj** [comment]
when new orgs are added, all admin assigned tags on public collectors are copied into the new org.
However there is currently no mechanism to push new admin assigned tags to all users when changes are made.

**Comment by nopzor1200** [comment]
I've added all the default Tags to the Collectors on prod
