### ISSUE TITLE
"dashboards" link a bit confusing

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#422]
when you hit the dashboards link in upper left, you go to the main page. the main page explains what litmus is, it encourages you to use litmus features, and also links to a few of the dashboards.
overall the page is not really about dashboards and i find it confusing
![dashboards-confusing](https://cloud.githubusercontent.com/assets/20774/9367004/0434bc22-46bb-11e5-80eb-1bc5018c7302.png)

when I think "dashboards" I think i want to see all available dashboards, and create new ones.
in that sense, the dashboards menu feels more appropriate and representive of what I think you should get once you click a dashboards button/link
![dashboards2](https://cloud.githubusercontent.com/assets/20774/9367008/0b4edff6-46bb-11e5-9ee2-b56208b8d7ff.png)

just me?

**Comment by mattttt** [comment]
These screenshots are old, but you bring up a good point, regardless. 

We have some ideas about this that I want to flesh out; more to come here.

**Comment by Dieterbe** [comment]
matt pointed out that i'm using an older version, and this has changed a bit lately:
![better-home](https://cloud.githubusercontent.com/assets/20774/9378781/6ce94eea-4724-11e5-9e2b-bcd7fd2303dc.png)

so now it makes more sense, i hit dashboards and i get a list of dashboards.. but also a bunch of other stuff. i still think there's too much of an impedance mismatch.
I think it's great to have a "home page" with the todo/complete stuff, and maybe put a list of dashboards there, and maybe a few other things we want people to see when they login (see also https://github.com/raintank/customer-experience/issues/14)
but then I don't think that should be "the dashboards page"

**Comment by mattttt** [comment]
Yep, our conversation yesterday went the exact same way, eventually thinking that we'll want to introduce a Home page that can best summarize the info you need to see. 

This is something we should discuss with Torkel, as it's super useful when you start adding integrations on top of Grafana, but at the moment, isnt really needed.

**Comment by mattttt** [comment]
The Litmus home page has been adjusted, so this is no longer valid. Some of the points are however, and will be included in redesign.
