### ISSUE TITLE
New Collector Page

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#423]
Formal writeup to come, but here is a first pass at the New Collector screen. 

![newcollector](https://cloud.githubusercontent.com/assets/2886187/9370881/ce548ccc-46a1-11e5-8355-5d85ea465d5b.png)

> When you enter a collector name or generate an API key, expected behavior will be to pre-fill the snippet. This needs to be fleshed out more.

**Comment by mattttt** [comment]
The directions need to be rewritten to be clearer/work, so consider some of this placeholder. I took it from the github readme.md on raintank-collector.

**Comment by woodsaj** [comment]
I think we need to create the collector (give the collector a name and submit it to the backend) as step1.  This ensures that the collector name is not already in use.
We can then show the config that should be used and the "Verify" step can just wait for the collector state to transition to "online".

**Comment by mattttt** [comment]
How does that work with the API?

**Comment by woodsaj** [comment]
?? i am not sure what you are asking.

All actions are performed via the API.

When a collector connects to the backend, we check to see if it already exists and if not, we create it.
This simplifies the deployment of collectors but also introduces problems.

Eg, if a collector.name in the collector config is entered incorrectly, the collector will still start up normally, and will just create a new collector instance in the DB.  I would prefer to remove the auto-create feature from the backend so that the collector will instead fail to start up.  

Users can still achieve auto-creation of collectors by using the API to create the collector within their deployment scripts.
```
curl -X PUT -H 'Authorization: Bearer <API_KEY>'  -d '{"name": "newCollector"}' https://app.raintank.io/api/collectors
```

So i feel that the first step in bringing a collector online should be to 'reserve' the name of the collector.  If a collector by that name already exists we can warn the user (as they may want to de-deploy an existing collector)

**Comment by Dieterbe** [comment]
we might want to mention you need node and npm for this to work as well.
though all that will change too.

**Comment by woodsaj** [comment]
i wouldnt worry about installation.  most likely we will just provide a install script that the user can download and run

`curl https://raintank.io/install_collector.sh | sudo bash`

**Comment by mattttt** [comment]
@woodsaj 
> I would prefer to remove the auto-create feature from the backend so that the collector will instead fail to start up

Ah, makes more sense now. I was wrestling with the fact that specifying a collector name in the interface isnt actually required, and could be bypassed by just spinning up a new collector. But if we do away with that functionality, it makes more sense.

**Comment by mattttt** [comment]
Make some headway on a multi-step process, what do you think of this @woodsaj?

Invision prototype: https://invis.io/PA3Z0OND8

Some select images:
![newcollector2-2](https://cloud.githubusercontent.com/assets/2886187/9451277/b69da6f8-4a7b-11e5-9f0a-ec5943058558.png)
![newcollector2-3](https://cloud.githubusercontent.com/assets/2886187/9451275/b6778158-4a7b-11e5-83a2-bfb4ddeef796.png)
![newcollector2-4](https://cloud.githubusercontent.com/assets/2886187/9451276/b6788f58-4a7b-11e5-9406-a68799e7ec6c.png)
![newcollector2-5](https://cloud.githubusercontent.com/assets/2886187/9451274/b676191c-4a7b-11e5-8056-c9f70ce2377d.png)

**Comment by Dieterbe** [comment]
this looks sooo pretteeeehhhh

**Comment by woodsaj** [comment]
This looks really good matt.

The install instructions will be much simpler then what you have there.

1) have an input field for entering the API key, with a "generate New Key" button to populate it for the user if they want to use a new key.
2) Rather then instructing the user to install then configure, we will provide a script to do both.  The command will be something along the lines of
```
curl https://raintank.io/collector_install.sh | sudo KEY="<API_KEY>" NAME="<COLLECTOR NAME>" sh
```
The user will just need to copy and paste the command, and things will just work.  The Install command will only work for RedHat/CentOS and Debian/Ubuntu, so a link will need to provided to the Documentation for manually installation.

**Comment by mattttt** [comment]
Update to the New Collector - I think this is good for @nchristus to start working on. 

https://invis.io/PA3Z0OND8

![newcollector2-4](https://cloud.githubusercontent.com/assets/2886187/9480116/20f147de-4b4f-11e5-9055-2ce1f34c714d.png)
![newcollector2-3-other](https://cloud.githubusercontent.com/assets/2886187/9480115/20efeef2-4b4f-11e5-88fc-0a20fcdb4077.png)

> I'll need to get some better logos that work on that backgroud. There are a bunch of use guidelines, so I'll tap @bulletfactory to help me work that out.

**Comment by mattttt** [comment]
@nchristus Some updates to come, a little user testing showed some flaws.

**Comment by mattttt** [comment]
Link has been updated, but want to make a couple other tweaks. Nothing that'll hold you back @nchristus, so go ahead and get started as planned.

**Comment by bulletfactory** [comment]
Ah - yeah, I'll dig up some pngs w/ transparent backgrounds for this.

**Comment by mattttt** [comment]
This is in a good spot from @nchristus, just waiting on images from @bulletfactory and the script from @woodsaj. 

@woodsaj If you arent able to write the script for the moment, should we launch with the directions on the github page, and then add in the additional functionality shortly thereafter?

nick's branch is: https://github.com/raintank/grafana/tree/nchristus-new-collector-page

**Comment by woodsaj** [comment]
Lest just go with the Instructions on the Readme.md for now.
https://github.com/raintank/raintank-collector/blob/master/README.md

**Comment by mattttt** [comment]
:+1:

**Comment by mattttt** [comment]
Updated the instructions to match the instructions. 

Currently working on:
(1) Now that we're only supporting one set of instructions for the moment, back out the functionality to choose between the two. 
(2) Add in a check for user permissions for (a) adding new collector and (b) generating new API key

**Comment by bulletfactory** [comment]
Perhaps something like this? Example of both themes on left

![linux-distros](https://cloud.githubusercontent.com/assets/1950595/9882533/116a07f6-5ba3-11e5-9cc2-9fec825016f3.png)

These are all svgs on a circular div w/ @rt-light-gray bg color.

**Comment by mattttt** [comment]
Looks good to me - will get the images and get this updated.

**Comment by mattttt** [comment]
This has been completed until the scripts are written, in which case we can switch to the more dynamic page we built. cc @woodsaj
