### ISSUE TITLE
optimize serialization of metrics

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#424]
i don't think this is high priority and shouldn't delay our NSQ release, though we should address high cpu usage + high data footprint at some point.

so i did https://github.com/raintank/grafana/commit/25a2b51e783f5f8b8a283825c582d2f67529a123

on my computer (i7-4810MQ), go 1.4.2 I get:
```
dieter@dieter-m6800 models go test -bench=.
.
1 total assertion

.
2 total assertions

PASS
BenchmarkSerialize3000MetricsJson	     100	  11585789 ns/op
--- BENCH: BenchmarkSerialize3000MetricsJson
	metric_serialization_bench_test.go:62: final size: 847716
	metric_serialization_bench_test.go:62: final size: 847716
BenchmarkDeSerialize3000MetricsJson	      50	  28080364 ns/op
BenchmarkSerialize3000MetricsGob	     200	   7877874 ns/op
--- BENCH: BenchmarkSerialize3000MetricsGob
	metric_serialization_bench_test.go:94: final size: 492328
	metric_serialization_bench_test.go:94: final size: 492328
	metric_serialization_bench_test.go:94: final size: 492328
BenchmarkDeSerialize3000MetricsGob	     100	  11660870 ns/op
ok  	github.com/grafana/grafana/pkg/models	6.255s
```
--> gob only needs 68% the cpu time to serialize and 42% the cpu time to deserialize and the message is only 58% the size.

pretty good, especially the space reduction.  though we can probably do better.  gogoprotobuf should be faster (though i had a hard time with it), and maybe we should try msgpack.
gob is also go-only ..

**Comment by Dieterbe** [comment]
now with messagepack 07f28c7
```
BenchmarkSerialize3000MetricsJson	     100	  11600713 ns/op
--- BENCH: BenchmarkSerialize3000MetricsJson
	metric_serialization_bench_test.go:62: final size: 847716
	metric_serialization_bench_test.go:62: final size: 847716
BenchmarkDeSerialize3000MetricsJson	      50	  28236292 ns/op
BenchmarkSerialize3000MetricsGob	     200	   7871277 ns/op
--- BENCH: BenchmarkSerialize3000MetricsGob
	metric_serialization_bench_test.go:94: final size: 492328
	metric_serialization_bench_test.go:94: final size: 492328
	metric_serialization_bench_test.go:94: final size: 492328
BenchmarkDeSerialize3000MetricsGob	     100	  11718933 ns/op
BenchmarkSerialize3000MetricsMsgp	    1000	   2256535 ns/op
--- BENCH: BenchmarkSerialize3000MetricsMsgp
	metric_serialization_bench_test.go:128: final size: 645887
	metric_serialization_bench_test.go:128: final size: 645887
	metric_serialization_bench_test.go:128: final size: 645887
BenchmarkDeSerialize3000MetricsMsgp	     300	   4340955 ns/op
ok  	github.com/grafana/grafana/pkg/models	10.513s
```

this is getting fast.. though a 100kB in data difference at 100Mbps is `100000/(1024*1024*1024/8)` = 8ms

**Comment by Dieterbe** [comment]
the thing about protobuf though, it's pretty hardcore. you have to write a schema in their own language, and then it generates go structs that you have to use. it's pretty offputting.
i was also interested in flatbuffers since that had a bit higher serialization overhead in https://github.com/alecthomas/go_serialization_benchmarks but an extremely low deserialization time, which seems useful in our case where we [can] have multiple consumers processing the same data. but also here you have to settle for whatever code it generates and modify our business logic.. i think that takes us too far.

msgp seems very simple and a big performance improvement, it looks like a great compromise.

**Comment by Dieterbe** [comment]
grafana and raintank-metric now both have a nsq-msgp branch.
https://github.com/raintank/grafana/tree/nsq-msgp
https://github.com/raintank/raintank-metric/tree/nsq-msgp

it *almost* works.. for some reason no data showing up in devstack even though the nsq_metrics_to{kairos,elasticsearch} consumers seem to be decoding it fine..
to be continued..

**Comment by Dieterbe** [comment]
also curious what @woodsaj thanks.

**Comment by Dieterbe** [comment]
started up devstack today, added an endpoint and now it works fine.

i've noticed this is the past as well: sometimes when firing up the devstack and adding an endpoint everything looks fine (workers process the metrics fine, all looks good) but the graphs don't load data in grafana. but if you restart the stack and try the exact same thing, it works fine again.

first time i noticed it was with the nsq-schema changes, and now i noticed it again :/

**Comment by woodsaj** [comment]
This is great.  Lets go with MessagePack for now.  I do think that protobuf will be advantageous long term as it provides better interoperability and integration.

As per https://github.com/raintank/raintank-metric/issues/19, we should only define the model in the raintank-metric library, then import that into grafana.

**Comment by Dieterbe** [comment]
on it!

**Comment by Dieterbe** [comment]
implemented in nsq branch.
