### ISSUE TITLE
packaging.sh: 4: packaging.sh: Bad substitution

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#429]
just observed this in circleci:
```
cd rt-pkg && /bin/sh packaging.sh

packaging.sh: 4: packaging.sh: Bad substitution
```

don't see anything obviously buggy in the script.
you might want $DIR in double quotes throughout the script but i don't see what's wrong with line 4.

**Comment by woodsaj** [comment]
pretty sure that this is because the script is a bash script, but is called with 
```
/bin/sh packaging.sh
```

`/bin/sh` is a symbolic link to /bin/dash on Ubuntu.

should be called with
```
/bin/bash packaging.sh
```
