### ISSUE TITLE
endpoint display broken in current master

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#430]
current master in dev stack, after adding an endpoint:
![endpoint-display](https://cloud.githubusercontent.com/assets/20774/9464506/c2df2ce4-4b24-11e5-88d0-b41dd460ce7a.png)
note the status panel obviously, but also the header/logo upper left side, the dashboard icon there is wrong too.

**Comment by Dieterbe** [comment]
fwiw, no events/errors in js console, all http requests return in 200 or 304

**Comment by Dieterbe** [comment]
the header is broken on every page.
![also-broken](https://cloud.githubusercontent.com/assets/20774/9464570/47440fe0-4b25-11e5-9f7f-43f60410e491.png)

**Comment by mattttt** [comment]
Cannot reproduce across multiple browsers and havent gotten any other reports. Closing.
