### ISSUE TITLE
don't wait with "quota reached" message until ready to save endpoint

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#434]
new endpoint -> discover, configure -> add -> "quota reached"
should have told me that before i did all the work configuring the endpoint.

**Comment by nopzor1200** [comment]
Yeah that's true. 

I just ran into that trying to demo my account to Etsy, at a bar today.

I should be told that I'm out of quota when I try to add a new endpoint, not when I am finished configuring it.
