### ISSUE TITLE
api example should use a configurable url

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#435]
![api-example](https://cloud.githubusercontent.com/assets/20774/9521170/7492b8b2-4ccd-11e5-9ddf-037c255629ce.png)
would be nice if there was a config option for us to set the highlighted part to whatever we want so we could set it to `http://app.raintank.io`

**Comment by Dieterbe** [comment]
actually, it could also put in `your_key_above` and also put something real instead of the mydash stuff, like `/api/datasources` so that you have a command you can just copy paste and run and then fine modify it

oh while i'm at it, also link to http://docs.grafana.org/reference/http_api/ from there :)

**Comment by torkelo** [comment]
should this issue not be in upstream grafana? :) 

I like the improvements, should be pretty quickly done.

**Comment by Dieterbe** [comment]
yeah i know, should've gone there. but now that it's here, doesn't seem worth it to move it :p

**Comment by woodsaj** [comment]
if this is still an issue open an issue in github.com/grafana/grafana
