### ISSUE TITLE
monitor health: unknown -> very brief ok -> critical, when should have been unknown->critical

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#436]
http check every 60s, disable it. set content match to something absurd.
enable http check.
will transition from unknown to ok and be in ok for less than a minute it seems, then change to critical

**Comment by woodsaj** [comment]
How long did you leave the check disabled? 
When you re-enabled the check, the alerting jobs started checking points from 30seconds ago.

**Comment by Dieterbe** [comment]
i think like a minute or so. anyway i'll try to repro and see if it was PEBKAC or legit bug.

**Comment by Dieterbe** [comment]
this was my mistake. i had updated the content match too late and it was checking the earlier data where it didn't have the failing content match yet.
