### ISSUE TITLE
Event panel parameters

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#44]
Event panel should be able to accept the $endpoint and $collector variables as arguments (set in Grafana Templates). Should be able to accept single vals (ie. "foo") or Graphite-style globs (ie "{foo,bar,moo}")

Definitely open to accomplishing this some other way but this seemed logical. This will allow it to function with the same filters as the rest of the Dashboards.

**Comment by nopzor1200** [comment]
I think this'll be really useful once you wrap this, even with current limitations.

It'd be nice if this panel could:

1) Accept $endpoint and $collector variables as filters (ie. the original issue)

2) Respect height property set in panel

3) Show collector name, endpoint name, test type (ie. DNS,PING,HTTP,HTTPS), and test status ie. (OK,WARN,ERROR) in separate columns in the panel for each event

Bonus points:

1) accept filters for test type and test status

2) Anything that makes it easier/possible for @mattttt and @bulletfactory to play around with it and try to make it look good

**Comment by woodsaj** [comment]
merged pull request for storing the endpoint.slug in the DB and including it in the definition of a monitor (which gets sent to the collectors).  The collector has also been updated so that it will include a 'endpoint' field in events that contains the endpoint slug.

**Comment by woodsaj** [comment]
the events panel is functional and ready for some UI love.

The event payloads stored in Elasticsearch look like
```
  {
    "collector": "singapore",
    "collector_id": 4,
    "endpoint": "apple_com",
    "endpoint_id": 10,
    "event_type": "monitor_state",
    "id": "",
    "message": "100% packet loss.",
    "monitor_id": 29,
    "monitor_type": "ping",
    "org_id": 1,
    "severity": "ERROR",
    "source": "network_collector",
    "timestamp": 1431592275831
  },
```

any of these fields can be shown in the UI and be used in the filter.
eg to show ERRORs for http or https checks for the endpoint and collector selected in the templateVars

```
endpoint:$endpoint AND collector:$collector AND monitor_type:(http|https) AND severity:ERROR
```

https://portal.raintank.io/dashboard/db/endpoint-events

**Comment by nopzor1200** [comment]
Initial feedback is that this works pretty well. With the params its infinitely more usable than what it was before. Will do some showing and discussing and create a new ticket with anything further

**Comment by mattttt** [comment]
@woodsaj / @nopzor1200: My version of the frontend does not currently display  "source": "network_collector". This is something we'd like to show, right?

**Comment by mattttt** [comment]
Existing dev merged in Pull Request https://github.com/raintank/grafana/pull/170
