### ISSUE TITLE
Make endpoint list (endpoints.html) default page

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#442]
When loading app.raintank.io, make the default route endpoints.html instead of the home dashboard.

**Comment by mattttt** [comment]
If we want to hack up Grafana for the time being, we can make a couple changes in `/public/app/routes/all.js` and specify:

```
      .when('/', {
        templateUrl: 'plugins/raintank/features/partials/endpoint_new.html',
        controller : 'EndpointConfCtrl',
      })
      .when('/dashboard/', {
        templateUrl: 'app/partials/dashboard.html',
        controller : 'LoadDashboardCtrl',
        reloadOnSearch: false,
      })
```

and then change the side menu Dashboard link to go to `/dashboard/` instead of `/`

I tried making the changes within the raintank routes (hoping it would override the defaults), but it does not. 

I know this is a super hacky way to approach it, so what would be the better solution

**Comment by mattttt** [comment]
@woodsaj Can we at least redirect people to `https://app.raintank.io/endpoints` on login?

**Comment by woodsaj** [comment]
not really.  After login users are redirected to the last page they tried to load.  This is almost always "/".

**Comment by mattttt** [comment]
This has been temporarily addressed by creating the endpoint list panel and adding to the home Litmus dashboard.
