### ISSUE TITLE
Setting template variables via URL parameter doesn't consistently work

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#45]
Need to be able to set/override Template variables by passing URL params.

Currently trying to pass &var-endpoint=blah&var-collector=bar

Should this work? Am I running into problems with multi variable Templating?

Behavior seems really inconsistent. A lot of times the correct variable will show in the Template drop-down, but the value itself isn't selected. This causes the panels to have no data unless the endpoint is explicitly selected.

Also needs to account for multiple variables too (which can be a graphite style glob eg. "{foo,bar}"..)

**Comment by woodsaj** [comment]
SHA: e51d6511f406dd2e2acca20b6798dc5dff372963
I just fixed a problem where the template variable value was not being set correctly in the url.
The variable is the slug of the endpoint name.  but i was not generating the slug correctly. eg. the slug of www.raintank.io was being generated as www_raintank.io when it should have been www_raintank_io (notice the last period '.' was not replaced with an underscore '_')

**Comment by nopzor1200** [comment]
This seems to work consistently now
