### ISSUE TITLE
alert emails from dev point to prod

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#456]
emails from dev-hallo@ have a link to http://app.raintank.io
not sure if a bug in grafana or a mis configuration in dev?
@woodsaj @ctdk

**Comment by ctdk** [comment]
@Dieterbe it's a hard-coded value in the email.

**Comment by ctdk** [comment]
It's right here: https://github.com/raintank/grafana/blob/master/public/plugins/raintank/emails/alerting_notification.html#L46

@mattttt, do you know off the top of your head how to fix that? It seems like there's probably a config item for the hostname there.

**Comment by mattttt** [comment]
Neither atm - I dont believe there was a variable that related back to instance URL. That said, looking at some of the new email templates @torkelo created, I do see {{.AppUrl}}. It may have been there the whole time and not leveraged - and I can make that change & test it.

**Comment by woodsaj** [comment]
yes {{.AppUrl}} is available to all email templates.
