### ISSUE TITLE
sign up + "almost there" -> no email being sent?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#468]
https://github.com/raintank/raintank-docker/commit/d435d693516b039336e4177f8893c73294ed1349 enables easy email sending from dev stack (just replace user and pass)

i noticed that reset password and alert notification arrive fine to my personal email.
but when i go to sign up and go through the thing below, i don't get an email. tested with personal as well as gmail. is this expected? i was also surprised that after i hit continue i can just use the app, no email verification needed? @torkelo @mattttt 
![almost](https://cloud.githubusercontent.com/assets/20774/9878126/e3cb2e7a-5bc9-11e5-85a1-2bdd5f2862d5.png)

**Comment by woodsaj** [comment]
is the welcome_email_on_sign_up config item set to true in your config?

```
[emails]
welcome_email_on_sign_up = false

```

**Comment by Dieterbe** [comment]
ah oops.
https://github.com/raintank/raintank-docker/blob/master/grafana-dev/conf/custom.ini#L87
