### ISSUE TITLE
show litmus dashboards in dash search/list

### ISSUE THREAD

**Issue by woodsaj** [raintank/grafana#47]
litmus dashboards are served by a specialized dashboard controller that loads the dashboards directly from the server.  this is pretty much how the DashFromFile controller works except the path to the dashboards is different.

Because these dashboards are not stored in the DB, they do not show up in the dashboards search/list menu.

**Comment by nopzor1200** [comment]
Consensus here that this is likely the most important issue to resolve from a UI/UX standpoint for tinyalpha

**Comment by nopzor1200** [comment]
As a last resort (ie. interim solution) we can hard code a custom Litmus portion of the dashboard picker with links to Litmus

**Comment by torkelo** [comment]
will start work on this today, after that I think https://github.com/raintank/grafana/issues/70

**Comment by mattttt** [comment]
:thumbsup:

**Comment by torkelo** [comment]
implemented in https://github.com/grafana/grafana/issues/960 

```ini
[dashboards.json]
enabled = true
path = /var/lib/dashboards
```

json dashboards will be indexed and available in search and in dashlist panel. tags are taken from the dashboard json (as is title).  Index is updated every minute. 

The dashboards in search result or dashlist can be styled differently, the get a css class like `search-item-dash-json`

**Comment by nopzor1200** [comment]
Awesome! I see the raintank dashboards showing up now on staging in the picker and the search (under file/ instead of db/). Looks great and exactly what we need at least initially. Will open sep issue with further feedback as we have it.

**Comment by mattttt** [comment]
👍👍
