### ISSUE TITLE
Language change: Collector -> Probe

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#476]
From this point forward, Collectors are now to be referred to as Probes. This is a pretty substantial task in the backend, but not so much in the frontend. 

Starting a ticket to change this in order of priority:

- [ ] Change language in the HTML (everywhere)
- [ ] Change raintank-collector repo name in github
- [ ] Change Less files and CSS class names
- [ ] Change backend (@woodsaj)

**Comment by woodsaj** [comment]
this is a duplicate of:
https://github.com/raintank/grafana/issues/278  which has more information, and i have continued the discussion there.

**Comment by mattttt** [comment]
closing, in favor of other ticket.
