### ISSUE TITLE
Endpoint List- Dashboard Panel

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#477]
stub, but to get this working:

![screenshot_2015-09-18_08 40 36](https://cloud.githubusercontent.com/assets/2886187/10180233/6d0054bc-66d9-11e5-9fdb-9d827888a1b1.png)

**Comment by mattttt** [comment]
Started in: https://github.com/raintank/grafana/tree/endpoint-list-panel

**Comment by mattttt** [comment]
This is complete and in production. Next is to add the filters.

**Comment by nopzor1200** [comment]
Nice job on getting this refactored as a panel btw. I think the biggest use case is in the "Home dashboard" for the Litmus plugin. I think its important to remember that doing this opens up showing "time related" stuff on the panel!

**Comment by nopzor1200** [comment]
And should look at whether the panel should respect endpoint arguments, eg. all, or a specific one.
