### ISSUE TITLE
Make Endpoint List panel respect $endpoint variables

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#494]
Ref: https://github.com/raintank/grafana/tree/master/public/plugins/raintank/panels/raintankEndpointList

Would like to add something into this panel that will filter the list of endpoints if an $endpoint variable exists. For example: 
- If no $endpoints exist, the entire list is be shown. 
- If endpoint_one, then display only one in the list. 
- If $endpoint_one+$endpoint_two+endpoint_three, then display three endpoints in the list. 

All that said, I assume it's best to handle that in the same panel, but open to separate panels as well. 

(This is one thing I'm considering for consolidating the Litmus screens into the dashboard views.)

**Comment by woodsaj** [comment]
Currently on tags are supported as filters when calling the endpoint list command.  So we will need to extend this functionality to the other endpoint attributes (name, slug, id)

**Comment by woodsaj** [comment]
It should be noted, that this functionality will be pretty limited until templateVariable formatting becomes per panel.  At present, the format of the variables is per dashboard (regex, glob, lucene, etc..).  This means that you cant use the same template variable across panels that require a different format.  Graphite queries for example require the glob format, while this panel will require a url format.

https://github.com/grafana/grafana/issues/2918
