### ISSUE TITLE
alerting job messages not being acked to rabbitmq?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#496]
how to reproduce:
1) update & spin up dev stack
2) `env-load load`
3) open http://localhost:15672 -> both in main overview of queued messages, as well as individual queues the number of unacked = total messages. although the exchanges do say msg in rate = msg out rate, and alerting seems to work

**Comment by Dieterbe** [comment]
![huh](https://cloud.githubusercontent.com/assets/20774/10620106/4d9e85e8-7747-11e5-9312-be00ca34e50d.png)
actually it seems like, even though the rabbit queue is being fed constantly, the workers aren't really pulling many jobs out of it

**Comment by Dieterbe** [comment]
@woodsaj @ctdk any idea?

**Comment by ctdk** [comment]
@Dieterbe No ideas at the moment, but I'm in there anyway so I'll take a look.

**Comment by Dieterbe** [comment]
https://github.com/raintank/raintank-docker/issues/41 might have something to do with this, though if that was only it, at least some messages should be acked to rabbit.

**Comment by ctdk** [comment]
There aren't any un-acked messages in a litmus stack brought up with chef and not using env-load, fwiw.

**Comment by woodsaj** [comment]
looks like the problem could be due to https://github.com/raintank/grafana/blob/master/pkg/services/rabbitmq/consumer.go#L146

Msgs are being processes sequentially.  We probably need to refactor the code so that each message is processed in its own goroutine.
