### ISSUE TITLE
Importing raintank dashboards into grafana

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#501]
Once the raintank data source is in grafana, raintank dashboards still do not work 'out of the box'. The template variables and panels must be edited indivdually to use the new raintank data source instead of the default data source. 

This is a known issue, but I could not find it represented in our github anywhere. Really this should be a larger grafana issue (tying into the reservoir), but we'll start it here and move it. 

cc: @woodsaj, @torkelo

**Comment by woodsaj** [comment]
The only thing that i can think to resolve this is to prompt the user to select the datasource to use when importing.  But that is complicated as a single dashboard (and even a single panel) can use multiple datasources.

**Comment by Dieterbe** [comment]
maybe we should introduce some sort of convention for naming that maps to the names that we use in hosted litmus?
like tell people to configure raintank datasource with the name "raintank" (and if we will also expose ES, tell them to use the same name like raintank-es), that way if the datasources have the same name on the user side as in hosted litmus, wouldn't that solve it?

**Comment by woodsaj** [comment]
I think this will work.  We already name the datasource "raintank", so using that in each panel instead of the current "null" (which causes the default datasource to be used) would work for both the SaaS platform and anyone using an onprem deployment of grafana.

**Comment by mattttt** [comment]
Testing this now.

**Comment by mattttt** [comment]
This is working great, but found on a user interview today that the 4 singlestat panels didnt work on teh Summary dashboard. Will investigate.

**Comment by mattttt** [comment]
Summary panels were missing the explicit datasource for singlestats. Added, tested on dev-portal, seem to be functioning well.

**Comment by mattttt** [comment]
Keeping this open until pushed to production.

**Comment by mattttt** [comment]
This has been pushed into production and tested. Looks good. Closing.
