### ISSUE TITLE
CTA Panel: Safari Bug

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#505]
Looks like this in Safari:
![screenshot 2015-10-20 16 29 34](https://cloud.githubusercontent.com/assets/2886187/10668164/f9de51f0-78a8-11e5-80d3-85aa44dedf38.png)

Should look like this:
![screenshot 2015-10-22 10 39 53](https://cloud.githubusercontent.com/assets/2886187/10668220/3fc72ae8-78a9-11e5-8c06-6da962ce9609.png)

**Comment by mattttt** [comment]
Nick, do you have some time this weekend to address?

**Comment by nchristus** [comment]
@mattttt it was indeed a pesky flexbox issue.

Commit: https://github.com/raintank/grafana/commit/42cdb2fbc269d8aabd8e683212e10efb485c2c26#diff-9ab15f0deaedcc6a28d15afb931bf310L1714

![screen shot 2015-11-08 at 9 09 34 pm](https://cloud.githubusercontent.com/assets/136611/11025160/72677cc0-865d-11e5-9aff-316f9e79c6cb.png)

**Comment by mattttt** [comment]
Excellent, looking good! Testing now.

**Comment by mattttt** [comment]
Pushed to master. Closing.
