### ISSUE TITLE
Auto Discover converting all URLs to lowercase

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#510]
Reported by a very cool early access user:

`Noting one defect/possible enhancement I spotted – I added an HTTPS endpoint that had a case-sensitive URL, but it was failing error checks with a 401 error. It looked like somewhere between auto-discovery and the endpoint being created, the path was converted to lowercase and thus was failing. Fixing the case here allowed the checks to pass.
`

**Comment by woodsaj** [comment]
This issue is due to https://github.com/raintank/grafana/blob/master/pkg/services/endpointdiscovery/endpointdiscovery.go#L26
