### ISSUE TITLE
Helper text for New/Config Endpoint Checks

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#515]
In a very helpful user interview this afternoon, they accurately pointed out that the Content Match field doesnt tell you the things it supports. With that, I'd like to include some small helper text.

I now know that it'll support regexes. What else am I missing?

**Comment by woodsaj** [comment]
only regexp is supported.

eg.

"word"  - will match if "word" exists anywhere in the document
"word.*word" - will match if any line contains "word" twice.

**Comment by woodsaj** [comment]
For full details of capabilities refer to: https://golang.org/pkg/regexp/syntax/

**Comment by mattttt** [comment]
Added helper text, would like to look into some more intelligent form feedback like http://www.regexr.com/ or http://regexpal.com/

Im sure there's a library we can leverage to validate the regular expression is valid - and then perhaps down the road, extend it to test the regexp against the path specified on demand.

<img width="465" alt="screenshot 2015-11-03 09 45 48" src="https://cloud.githubusercontent.com/assets/2886187/10910844/b6f93650-820f-11e5-9a4f-7ee721288d46.png">

**Comment by mattttt** [comment]
In branch matt-UI-improvements

**Comment by nopzor1200** [comment]
Looks good. I Suggest minor improvement:

"Content Match checks to see if your string occurs in the first 100KB of the page download. You can also use a regex"

[Keeps "Content Match" capitalized similar to the UI element, rewords "match looks to match", and adds specificity around why it might not be working]

**Comment by Dieterbe** [comment]
btw there's several syntaxes for regex. we should link mention exactly which one we use, and link to docs (see AJ's link). in fact, why not mention a few simple examples to rule out some initial questions (i imagine people may want to know if things like `[:white:]` are supported, where backslashes are needed (in groups or not), etc) and perhaps also link to  https://regex-golang.appspot.com/assets/html/index.html
