### ISSUE TITLE
separate out raintank's metric package out of grafana into standalone

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#534]
pkg/metric

so that it's reusable to other apps and we don't need a fork of grafana.

**Comment by woodsaj** [comment]
@Dieterbe  as you have been working on updating the metrics lib, can we address this too.

**Comment by Dieterbe** [comment]
the reason of pkg/metric's existence is it can neatly switch over between regular statsd and dogstatsd tags.  but now that i've found a statsd client that looks like the highest performance - https://github.com/alexcesaro/statsd -  and it also offers optional datadog and influx tags. there's no real need for this package at all anymore, and we can use this statsd client directly.
( and anyway we don't use DD anymore and presumably other people who would run litmus won't either.  )
I will update everything in raintank-metric to use the new client directly, and then raintank/grafana and then we can just remove it this package.

**Comment by Dieterbe** [comment]
actually, an abstraction still makes sense for these reasons:
* it's nice to have variables representing gauges, timers etc for robustness (esp when used in multiple places),  instead of relying on string arguments and having a central overview
* it'll be nice if we also decide to abstract another library such as go-metrics

+ it saves me a bunch of time if i can just relocate the lib :) so that's what i'll do for now.
