### ISSUE TITLE
loading dashboard right after adding endpoint will never show the data

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#537]
1) create new endpoint
2) go to dashboard straight away
3) graphite data is not in our system yet so the endpoint/probe variables don't load
4) no matter how long you wait, and hitting refresh button, the endpoint/probe variables won't load, even after the data existsts (this is can be considered an upstream grafana issue I think?)
5) you have to reload the actual page for the dashboards to work. this is not obvious and could leave a bad first impression to new users.

not sure how to fix.
* make grafana reload variables on reload?
* populate metricDefs in ES as soon as we can (before having data). i thought we already had something that creates the metrics as early as we can. how does this work again.  but it seems like it's not fast enough if you load a dashboard immediately after creating the endpoint. (this manual user action takes me about 0.5~1s)

**Comment by nopzor1200** [comment]
I think that's what the "reload variables on dashboard reload" option is
for, right? That's what I thought but I could be wrong. It needs to be
enabled on all litmus dashboards
-r

On Wednesday, December 2, 2015, Dieter Plaetinck <notifications@github.com>
wrote:

> so it's sort of an upstream grafana issue, but it affects especially the
> litmus scenario.
>
> 1) create new endpoint
> 2) go to dashboard straight away
> 3) graphite data is not in our system yet so the endpoint/probe variables
> don't load
> 4) no matter how long you wait, and hitting refresh button, the
> endpoint/probe variables won't load, even after the data existsts (this is
> can be considered an upstream grafana issue I think?)
> 5) you have to reload the actual page for the dashboards to work. this is
> not obvious and could leave a bad first impression to new users.
>
> not sure how to fix.
>
>    - make grafana reload variables on reload?
>    - populate metricDefs in ES as soon as we can (before having data). i
>    thought we already had something that creates the metrics as early as we
>    can. how does this work again. but it seems like it's not fast enough if
>    you load a dashboard immediately after creating the endpoint. (this manual
>    user action takes me about 0.5~1s)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raintank/grafana/issues/537>.
>


-- 
Raj Dutt

co-founder/ceo, raintank
+1-917-664-1310
dutt@raintank.io

**Comment by mattttt** [comment]
This is also kinda related to Issue: https://github.com/raintank/customer-experience/issues/17

**Comment by woodsaj** [comment]
I think that it is unrealistic to expect there to be data immediately after creating a new endpoint.  I would rather disable the dashboard links for "X" seconds (probably 2x check frequency) after initial creation of the endpoint.
