### ISSUE TITLE
allow going to, say, http check configuration from the http dashboard

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#55]
when i'm on http dashboard looking at http perf of my blog, i would like an easier way to go to the config of this

**Comment by nopzor1200** [comment]
Agree it'd be useful to be able to get at the endpont.check configuration from a particular endpoint.check Dashboard. Maybe in the top nav.

**Comment by nopzor1200** [comment]
This is related to #57 
Personally I think both issues are about providing better context and nav in topnav.
Closing this issue out.
