### ISSUE TITLE
Litmus Endpoint Config: Grafana Save Menu Triggered w/ No Changes

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#558]
![save-issue](https://cloud.githubusercontent.com/assets/2886187/12895702/bf49a030-ce6b-11e5-9ed8-278cbdfc06fc.gif)

Not sure if this is @woodsaj or @torkelo expertise, but want to fix this in prod ASAP. 

I did some testing, and it's not related to the Destroy section; pulled it out entirely and it was still happening.

**Comment by mattttt** [comment]
Also did this in incognito without any browser extensions; still happened.

**Comment by woodsaj** [comment]
I am pretty sure this is due to the new timeout setting added.

**Comment by woodsaj** [comment]
This was fixed in github.com/raintank/worldping-app
