### ISSUE TITLE
endpoints in endpoint select box only show up when they have data

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#56]
i added an endpoint B, went to dashboard of pre existing endpoint A and then tried to use the drop down to elect B but if didnt show up, which was confusing

**Comment by nopzor1200** [comment]
Probably because there's a delay before those series are created. I believe the series for endpoint B will only be created after the initial set of tests have run. This is similar to how after you add an Endpoint it will show "No Data" until the check data starts coming in.

I'm not sure what can be done other than doing an initial set of tests immediately (which might be a good idea?)

Can you confirm @woodsaj ? Any other thoughts?

**Comment by woodsaj** [comment]
the template variables options are populated from graphite queries. so if there is no data in graphite, then the endpoint/collector wont show as an option.

Similarily, when you delete an endpoint we are not currently purging the data in graphite, so the endpoints will still show up in the template variable options.

Both of these issues need to be fixed, and i think the best way is to trigger the creation/deletion of our metricDefinitions stored in Elasticsearch (this is what graphite queries) when checks are added/removed.

**Comment by Dieterbe** [comment]
i like that, updating the defs in ES. we should watch out for races though (like a point arriving right after deleting the ES entry shouldn't re-add the def)

**Comment by bulletfactory** [comment]
Recently added endpoints still do not show up; going to a dashboard from a newly created endpoint still results in an invalid selection

**Comment by woodsaj** [comment]
This is a bit complicated, as the the meticNames are generated by the collector.  While we could initialize the metrics from within the grafana backend, it is not ideal.  

I think the best option is to have the collectors send `state_ok`, `state_warn`, `state_error` events as soon as a new monitor is added (currently these are not sent until the endpoint is first polled).  There would still be a delay between the endpoint being created and these metrics being stored in the TSDB, but it should be no more then a second or two.

**Comment by Dieterbe** [comment]
not sure about that, if an endpoint is down when it is added, that would mean we mark it temporarily as up (for example), i would rather have the dashboard show up with "no data"

**Comment by woodsaj** [comment]
that would not be the case. I would simply send metrics with null values.  This will cause the metrics to exist in graphite, but there would still be no data (which is expected as the checks have not run yet)

**Comment by Dieterbe** [comment]
ah right, that sounds good

**Comment by woodsaj** [comment]
opened issue for the collector to address this.
https://github.com/raintank/raintank-collector/issues/11
