### ISSUE TITLE
Litmus Event Panel Needs to work!!

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#562]
When passing the endpoint and the monitor_type explicitly to the event dashboard, it works beautifully. But if you navigate to the dashboard without anything pre selected, events are not shown.

Can we do a screenshare and work together to get this resolved and pushed to production?

**Comment by mattttt** [comment]
Alternately, if this is going to be a pain, we can/should also talk about how to convert this to a proper table panel.

**Comment by woodsaj** [comment]
rt-events is now a table panel using native elasticsearch datasource.  This is currently being tested in QA and if all looks good will be pushed to production today or tomorrow.

see https://github.com/raintank/grafana/pull/563

**Comment by mattttt** [comment]
Updated the colors, but cant do much other tweaking until the table panel adds additional functionality. That said, it works 100x better, and is great!
