### ISSUE TITLE
alert executors should drop outdated jobs

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#567]
right? is there any reason why we should still execute stale jobs? it's not like we show alert health over time or something. only last value is relevant. I thought we already implemented this a long time ago but i guess not.

**Comment by woodsaj** [comment]
dropping outdated jobs has always been the preference.  from memory it was you who wanted to be able to process them after the fact.

**Comment by Dieterbe** [comment]
i think you may be referencing a conversation around the ticker, where i indeed held that position initially (but i got convinced otherwise by you and raj)
either way i pushed the fix for this two days ago e0073d6be91c41210ca793730219352ada0970e3

**Comment by Dieterbe** [comment]
for the record, context here is alert jobs not processing properly -> big backlog of jobs in queue -> no need to process old ones, most recent state is more important
