### ISSUE TITLE
adjust time selection options

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#569]
the UI lets you choose options like 5years/2years/1year even though we only retain 5weeks worth of data. we should disable some of those options, and also make it so that you can't set a from manually that is too far back. maybe grafana should get a config option to limit how far back you can go and that would be used to limit the preselections as well as the manual configuration.

**Comment by woodsaj** [comment]
@Dieterbe this needs to be opened as an upstream issue.

**Comment by Dieterbe** [comment]
https://github.com/grafana/grafana/issues/4288
