### ISSUE TITLE
lower default maxdatapoints

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#570]
1 point for every pixel is often way too much.

![1month-20-probes](https://cloud.githubusercontent.com/assets/20774/13311545/6aa3f532-dbe3-11e5-9eca-88d79f0abe5f.png)

in fact, when you have many series (in this case 20) i find that after the waiting wheel is done spinning (e.g. data has been fetched), javascript/grafana can hang for a few seconds until it can render the data and have javascript work again (popups follow mouse etc)

**Comment by woodsaj** [comment]
@Dieterbe this needs to be opened upstream.

**Comment by torkelo** [comment]
Grafana sends maxDataPoints (1 point per pixel), so even with many series it should render within 100-300ms

**Comment by Dieterbe** [comment]
i'll doublecheck this is the case and open upstream.

**Comment by torkelo** [comment]
you can check with chrome dev tool if grafana sends a sensible number in the maxDataPoints param to graphite

**Comment by Dieterbe** [comment]
the good news:
* i have the problem only in firefox. chrome and luakit are much faster, near-instant even
* i no longer feel strongly about lowering default maxdatapoints. 1point per pixel often makes sense and is not necessarily "too much"

the bad news:
* the experience with firefox (only on linux? not sure?) is pretty bad, and i now have proof:
https://vimeo.com/158151263
see how the UI is blocked after i click refresh between 0:03 to 0:06, but only 100ms is spent getting the data from graphite. also from 0:37 to 0:40; so that's at 2 to 3 seconds of "UI hang overhead" which sucks imho.

can anyone reproduce this? settings were maxpoints 1900, 10 series, 1799 points returned.
(in devstack you can use https://github.com/raintank/raintank-metric/tree/master/fake_metrics_to_nsq to create the fake data).
you can also just do it litmus directly. any chart that shows a line for each probe will do. for me the UI hangs for multiple seconds after loading the data there too.

**Comment by torkelo** [comment]
@Dieterbe test firefox with 6 graphs each with 4 series, a total of 88 272 data points, renders in about half a second or so, hard to say, 

Are there any annotations? Annotation rendering can be slow. 

![firefox](https://cloud.githubusercontent.com/assets/10999/13598044/f7979584-e51b-11e5-8caf-6e3c2c10afc4.gif)

**Comment by torkelo** [comment]
ok, I can replicate it more with points, seems like points rendering is much slower than line rendering

**Comment by Dieterbe** [comment]
no annotations. if i change to lines, it's blazing fast (in firefox), but only for the test data.
in litmus, a graph with all 20 or so probes doesn't become any faster when i change from points it to lines.
sounds to me like the point renderer is very poorly written. how can it be so much slower than drawing lines.. if anything it should be faster i think.

**Comment by woodsaj** [comment]
Closing this out. If it is still an issue, open it in github.com/grafana/grafana
