### ISSUE TITLE
feedback link no longer works

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#64]
In tinyalpha the feedback link in the bottom is no longer persistent, and when i can catch it it no longer works.

**Comment by nopzor1200** [comment]
Could you take a look at this? It used to work and stopped working. I'm sure it's something small.

**Comment by woodsaj** [comment]
This is failing due to the 'take screenshot' feature.
```
Screenshots
We can take a screenshot of the page the user is viewing and attach it to the feedback they submit. The user always has the choice to opt-out.

Note We are using Niklas von Hertzen's excellent html2canvas library. So support for screenshots is limited to Firefox 3.5+, Google Chrome, Opera 12+, IE9+, Safari 6+.
```

Disabled this feature in the doorbell configuration page.
