### ISSUE TITLE
Endpoint Summary should categorize unconfigured checks

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#65]
In endpoint summary, when a check isn't configured we should show that more explicitely and allow the user to configure/enable that protocol. Currently we just show "no data"

**Comment by mattttt** [comment]
A couple ideas on how to handle this. I'm leaning toward Option 2: the tool tip approach - and with a hover link color change, I think it'll be effective. 

Option 1:

![screenshot 2015-05-11 19 31 40](https://cloud.githubusercontent.com/assets/2886187/7577404/c5e6b374-f815-11e4-86b6-1913f618c3a2.png)



Option 2: 

![screenshot 2015-05-11 19 44 21](https://cloud.githubusercontent.com/assets/2886187/7577441/2ce148be-f816-11e4-9b37-b7881ae51f53.png)

**Comment by Dieterbe** [comment]
i agree that i rather not have the "configure now" option clutter up that space that is used for the state information, it "breaks up the visual flow" and doesn't look tight.
if you click the "not enabled" you go straight to the menu where you can enable it, right?
or were you envisioning that we have to click the tooltip text?

**Comment by mattttt** [comment]
"if you click the "not enabled" you go straight to the menu where you can enable it, right?"
Yep!

**Comment by mattttt** [comment]
Played around with a number of different options, ultimately landing on a bit more verbose solution. I think it nicely falls to the background, and doesnt demand too much attention compared to the real checks.

![newendpointdemo2](https://cloud.githubusercontent.com/assets/2886187/7599440/0dc7c4f2-f8d0-11e4-8372-8148842839c7.gif)

The tooltips were attempted, but were distracting.

**Comment by mattttt** [comment]
@woodsaj This now needs a bit of love from you, and then I can finish it. 

https://github.com/raintank/grafana/blob/endpoint_config_changes/public/plugins/raintank/features/partials/endpoints_summary.html#L58-L90

1. I dont know the best way to do this, but we need a way to check whether monitoring is enabled for each check. You'lll see in that code snippet above, I attempted to read monitors['ping'].enabled, but it wasnt available on the controller for the page. After trying a few different things, just decided to let you tackle it.

2. We need to link the "Not enabled, configure now." directly to the relevant & expanded section on the Config tab. Unsure how to do that.

**Comment by woodsaj** [comment]
step 1 done.
step 2 is much harder.  It is not possible to pass variables between controllers.  So we would need to pass the section state (expanded/collapsed) as query string params, or use some kind of shared object store. 
Ill try implementing using LocalStorage, as grafana already has support for this (uses it for the sidemenu state)

**Comment by mattttt** [comment]
since we're not using variables or loops to build either page, wouldn't some simple anchor link work?

**Comment by woodsaj** [comment]
using anchor tags was tricky to get working, but has now been committed.  works really well.

**Comment by nopzor1200** [comment]
Awesome. I'm also a fan of option 2 it seems less cluttered.

It's important to realize that there's nothing "bad" about an unconfigured check... it's not like we want them to "complete their endpoint" or something like that. I think what we ended up with underscores that, which is great.

**Comment by mattttt** [comment]
This has already been implemented in endpoint_config_changes, with anthony's changes. Pull request coming soon.

**Comment by nopzor1200** [comment]
I thing this looks good in current staging; closing.
