### ISSUE TITLE
users resetting password

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#70]
(I don't think this is raintank specific but opening here)

There needs to be a way for users to reset their passwords in Grafana.

Currently this is impossible (I think). Only the admin can do this.

**Comment by nopzor1200** [comment]
I guess this is grafana#1456

**Comment by nopzor1200** [comment]
This is still something that we'd ideally like to have before beta (ie. before we start signing up users in earnest). I assume it's still a high priority for Grafana mainline users too. My understanding is there is no way for users in Grafana mainline to reset their password other than having their Org admin do it.

Thoughts on timeframe/priority?

**Comment by torkelo** [comment]
will bump this!

**Comment by nopzor1200** [comment]
That's great. Talking to Anthony he thinks that this will also help us send email notifications for alerting

**Comment by torkelo** [comment]
closed upstream now. Together with a general email + email templating feature

**Comment by torkelo** [comment]
New config options:

```
#################################### SMTP / Emailing ##########################
[smtp]
enabled = false
host = localhost:25
user =
password =
cert_file =
key_file =
skip_verify = false
from_address = admin@grafana.localhost

[emails]
welcome_email_on_sign_up = false
templates_pattern = emails/*.html
```

the templates_pattern will allow raintank to change this to a raintank specific folders to have its own templates. The templates contain the email Subject as well. The path pattern is relative to static_root_path. 

New emails can easily be sent using this command:
```go
bus.Dispath(&m.SendEmailCommand{
		To:       []string{user.Email},
		Template: "my_new_email.html",
		Data: map[string]interface{}{
			"Name": user.Login,
	         },
	})
```

**Comment by Dieterbe** [comment]
note that this doesn't work on app.raintank.io, i tried it 25min ago, the web ui says "An email with a reset link as been sent to the email address, you should receive it shortly." but i got no emails, and mailgun reports no emails have been sent today.

**Comment by woodsaj** [comment]
GCE blocks port 25 outbound.  need to use 2525 when connecting to mailgun.

**Comment by ctdk** [comment]
Boom.

**Comment by Dieterbe** [comment]
i like that the email comes from hello@
so that if anyone has an issue they can just reply and we'll see it. who gets hello@ anyway?

**Comment by mattttt** [comment]
@Dieterbe not at the moment, but I will have some sort of shared helpdesk system implemented pretty quickly. Im aiming for end of next week.

**Comment by Dieterbe** [comment]
@mattttt at the moment no-one is receiving hello@ email? we've been telling people to use that email address, it's also on the website :(
