### ISSUE TITLE
Managing (becoming) other organizations

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#71]
The Grafana system admin should (I think) have some way of becoming or switching to any Organization that they want to. 

This is necessary for supportability when a system admin is responsible for many Users across many Organizations.

**Comment by torkelo** [comment]
Updated the user admin page so the admin user can add and edit organization and roles for any user (including himself). To become an admin for another org, just go to your admin page and add yourself to that organization (then switch to that org)

**Comment by nopzor1200** [comment]
So we can now as admins add ourselves to any organization; I think this meets the needs for supporting users for public beta.

I consider it a plus that the client organization will be able to see that raintank has "joined" their org (we can/should "ask" before doing this)
