### ISSUE TITLE
New Endpoint Page Adjustments

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#72]
### Checklist for help from AWoods:

- Trigger Spinner on "Auto-Discover"
- Wire up New Endpoint page to New Endpoint button. 
- Change options in Frequency Select Box to "Every 10s, Every 30s..."
- New resting state & disabled state.
- Issue with Enabled button not being checked in both places. 
- Enabled button collapsing the box. 
- Collector select button showing results in a select Box. 
- Wire up Add Endpoint & Cancel buttons.

**Comment by mattttt** [comment]
We're so close here. The only blocker to pushing into Tiny Alpha:

- When I click "Add Endpoint", the endpoint is successfully added, but nothing happens on the page. 

Correct behavior will be to send the user to the newly created endpoint summary.

**Comment by woodsaj** [comment]
merged branch
