### ISSUE TITLE
wire up Collector tag dashboards

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#82]
The links to dashboards-by-Collector-tag are dead.

Please wire up multiselect links for the list of Collectors in that tag. 

We might use existing endpoint dashboard or create another dashboard for this. Still thinking about it. Important thing is that we can link to dashboard?var-collector= but with the Tag values instead of an individual Collector, and leverage the template multiselect now in Grafana.

**Comment by woodsaj** [comment]
This is not really possible as the rt-endpoint-summary dashboard does not allow multiSelect for the 'endpoint' variable.

**Comment by mattttt** [comment]
Then we'll adjust the front-end to remove those dashboard links for the moment.

**Comment by nopzor1200** [comment]
Sorry I typod this ticket. I meant Collector tags (ie. collector multivar). The endpoint dashboards have multivar enabled for Collectors. I'll correct the title/text

**Comment by woodsaj** [comment]
@nopzor1200, still not sure what you are after here.  Whether you are coming from the collector list page or the endpoint list page, we dont have a dashboard that allows multiselect of both endpoint and collector.  

If i want to show a dashboard listing/summarizing all endpoints in a particular tag, then i need to pass 
`endpoint={site_a, site_b, site_c}&collector=All`

If i want to show a dashboard listing/summarizing all collectors in a particular tag, then i need to pass
`endpoint=All&collector={collector1, collector2}`

in both these cases a dashboard that supports multiselect for both endpoint and collector is needed, but no such dashboard currently except for: https://portal.raintank.io/dashboard/raintank/statusboard

**Comment by nopzor1200** [comment]
Hey sorry for all the confusion. Let me repaste what I added to the base ticket:

---- 

We might use existing endpoint dashboard or create another dashboard for this. Still thinking about it. Important thing is that we can link to dashboard?var-collector= but with the Tag values instead of an individual Collector, and leverage the template multiselect now in Grafana.

---

If we use the existing endpoint dashboard I do understand we will need to enable multivar on endpoints which is currently disabled. In previous versions of the dashboard this was enabled through the dynamic row functionality (repeat a row for each endpoint)

So I think we're on the same page in that we can do this provided we have a dashboard that supports endpoints=All and collectors={a,b,c}, right? I just wanted to be sure that we could correctly do this on the frontend, no matter which dashboard we end up going with (eg. endpoints, statusboard, collector, or whatever). 

I meant to create such a dashboard right after I opened this ticket but got distracted

I'll be trying to play around with dashboards more today (including playing with #81), and trying to get others help in making these dashboards better.

(The whole point of this ticket was just to make sure that wiring up these dashboards to $dashboard could be easily wired up.)

**Comment by woodsaj** [comment]
gotcha.

I have already tested this and it works as expected.

I know Torkel has done a bunch of changes in upstream around multiSelect and repeat panels so i will merge that first. then add the dashboard links for tags.

**Comment by bulletfactory** [comment]
needs to be wired up with initial dashboard "Endpoint across Collectors"

**Comment by mattttt** [comment]
I believe this has been addressed in the dashboard Litmus Endpoint: Comparison, though it needs a better name. 

Both tags being selected and functioning on dev-portal:
![screenshot 2015-06-26 17 14 04](https://cloud.githubusercontent.com/assets/2886187/8388373/eb675dbc-1c26-11e5-8d83-e48cfd63661d.png)

**Comment by nopzor1200** [comment]
So yes, we can use this dashboard (or any dashboard we choose to in the future).

Just talked to @woodsaj , he can get it using a glob for now until we add support to pass in a Tag.

**Comment by nopzor1200** [comment]
We agreed to do a summary dashboard that showed a line for each collector but averaged across a group of endpoints. I will create such a dashboard and @woodsaj can easily link it up.

**Comment by nopzor1200** [comment]
Step 1 - Come up with final final dashboard name - endpoint=all collector=glob
Step 2 - Have awoods wire it up
Step 3 - Investigate being able to pass Tags
