### ISSUE TITLE
alert scheduling, modulo, modulo offset

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#83]
Torkel and I decided it makes a lot of sense for initial alerting implementation to just query the monitor table, since the up/down definition is now a rule that is very closely tied to the monitor definition, and will in fact be stored in the monitor table along with the other check parameters.  So no need to manage alerting rules in a separate alerting table.
For the alert scheduling, 3 parameters are very important:
* frequency should be in sync with data collection. i.e. if a check runs every 10 seconds, so should the alert/health-indicator-updator. this is easy, as there is a frequency column in the monitor table already
* when within each period should be the alert trigger? For a given customer all collectors will run at the same time right? And does that go for all checks for a given customer? it looks like it's not the case ( if that's what the monitor.offset column is), let me explain what I mean:
if I have dns check every 60 sec and http check every 10 sec, then i would say my customer id should be hashed and modulo'd by 60, let's say the result is 37, and then that module 10 is 7,
this means the minutely check runs at every minute and 37 seconds, while every 10-second runs at min:07, min:17, min:27,min:37 and so on. the advantage is that even for different frequencies, the point's timing still match up. I think this will become useful later in alerting logic that looks at different series for the same endpoint but where data which is at different resolutions. otherwise scenarios where the minutely check runs at 0:37 and the 10-secondly runs at 0:32 and 0:42 could be very ambiguous and hard to relate. (although admittedly this is not much more than some gut feeling)

anyway my point is in models/monitor.go i saw these 2 fields and i was wondering if modulo == frequency and modulooffset == seconds to wait at the start of each interval?
```
174   Modulo         int64   `form:"modulo"`
175   ModuloOffset   int64   `form:"modulo_offset"` 
```

i think the best approach would be just hashing customer id to a number, and then storing that number, so you can easily query for the appropriate scheduling offset like so:
```
select hashed_number % frequency as offset, frequency from monitor
```
(modulo is supported by both mysql and sqlite)
the advantage is we don't lock ourself into any timeframe.
let's say we later decide to support 10-minutely, then we can always easily retrieve the proper offset that also syncs up with higher-frequency periods.

anyway the alerting logic has to query the offset somehow

3) we should maintain a special offset variable that tells how long it takes from the collector data to make it into the system and the data to become available for querying, and then some extra time to be safe.
so that we can schedule the alert shortly after the data arriving into the system, but also not too late.
i presume one global variable should be enough to cover all customers and all collectors, where-ever they are? i can imagine later we may implement a service that taps into the stream and keeps tabs on the per-collector delays or continuously queries graphite-api  and adjusts this offset automatically.

**Comment by woodsaj** [comment]
The modulo/moduloOffset are used for distributing checks between multiple collector processes.
As the collectors are nodejs apps they are single threaded. To handle more checks we need to run multiple instances of them (either on the same server or separate servers).

The collector-ctrl uses modulo/modulOffset where modulo=number of collector instances and moduloOffset=instanceId

If there are 2 collector instances running, 1 of the instances would get the checks returned by querying with modulo=2&moduloOffset=0 and the other instance would get the checks returned by querying with modulo=2&moduloOffset=1

**Comment by Dieterbe** [comment]
aha ok, so is there currently any record/configuration stored anywhere on how the collector's checks are timed? this has got to be out there somewhere but i couldn't find it.
also what did you think of my timing proposal above?

**Comment by woodsaj** [comment]
the offset field is used for this.

https://github.com/raintank/raintank-collector/blob/master/serviceManager.js#L340

```
var wait = ((service.frequency + service.offset) - (seconds % service.frequency)) % service.frequency;
```

when a check is scheduled, the collector calculates the `wait` time before the check should next be run. After that the check is executed every `frequency` seconds.

so if the `frequency` is 60seconds and the `offset` is 34 (the offset will always be a value between 0 and `frequency`) and the current time is 1431505377 (Wed May 13 04:22:57 EDT 2015)

then the check will be scheduled to start running at

((60 + 34) - (1431505377 % 60)) % 60 = 37 seconds from now.

so the the check will first run at Wed May 13 04:23:34 2015 and then every 60seconds after that.

When the frequency is 60seconds, the check will essentially run at every `offset` seconds past the minute.


As for your timing proposal, i like it.  Running all of an endpoints checks at the same time makes a lot of sense. This could be easily done by setting the offset value to (endpoint_id % frequency).  We could also have all of the checks in an organisation run at the same time by setting the offset to (org_id % frequency) instead.

this would be a simple change

here: https://github.com/raintank/grafana/blob/master/pkg/services/sqlstore/monitor.go#L471
and here: https://github.com/raintank/grafana/blob/master/pkg/services/sqlstore/monitor.go#L694

**Comment by Dieterbe** [comment]
ah yes, everything within an org makes even more sense than per endpoint, so you can compare endpoints better. so rather than storing an offset per monitor, why don't we just store an offset base (a number like 42435245) per org, which can then modulo by whatever the interval is of each check.

in fact, i just realized we don't even have to do any hashing or random numbering. we could just use the org id as a base! it's cheap, it's robust, and it distributes perfectly.

like if my org id is 123, then a check that runs at freq 60s will get offset 123%60=3

**Comment by Dieterbe** [comment]
ok so now that i can fix monitor.offset to act as the timing offsetter as discussed on a per-org basis, and i now know that monitor columns frequency and offset are what control the timing, i just want to confirm the points will always be exact multiples of offset right?
meaning if offset is 37, then the timestamp of every point in the database will be divisible by 37 without a remainder? this is really important. thanks aj!

**Comment by woodsaj** [comment]
I thought that there were guarantees that the checks would always use the timestamp of when it should have run ie "now() % frequency" should always equal the offset, but i just looked at the code and it uses setInterval().  If the server is under high load, setInterval can slowly creep forward until checks are executing 1 second later then intended.

Ill open an issue for this so that we can guarantee that each metric's timestamp is as expected.

**Comment by Dieterbe** [comment]
thanks aj you da best

**Comment by Dieterbe** [comment]
right now i'm running the check at a hardcoded 30seconds after the ts%freq==mo match, to give the data 30s to propagate from collector into database. thoughts?

**Comment by Dieterbe** [comment]
the other day @nopzor1200 made the observation that some customers (hosting providers) might have many unrelated endpoints, so for now it seems safer to deduce offset from endpoint id, not from org id.

**Comment by woodsaj** [comment]
closing this out.

**Comment by Dieterbe** [comment]
we've only addressed 2 out of 3 though.
currently the "wait time before we're guaranteed the data is available for querying in the tsdb" is hardcoded to 30 seconds. this should be a parameter that can be configured and manually adjusted at runtime without restart/recompile (so maybe a setting in the db) in the short term, and automatically maintained in the longer term.

**Comment by nopzor1200** [comment]
This sounds like a good idea

**Comment by Dieterbe** [comment]
so I think solving this requires something similar to #266 : we need a way to track the "query-offset" parameter (int) somewhere where we can easily update it and qery it from the app, i suggest as a record in a table in mysql. @woodsaj @torkelo any thoughts on how to go about this? (in terms of sql schema, and hooking it into the app)

**Comment by Dieterbe** [comment]
ping @woodsaj @torkelo see above. thanks

**Comment by torkelo** [comment]
maybe a table in the sql store for the scheduler to keep track of this?

**Comment by Dieterbe** [comment]
this is done via 2ababebcd2d9adf9219f6b5c6d3e4042aa055709 and 4d6d93aff88f1f8c1b628840df184a3eb8a84a7f
