### ISSUE TITLE
Need better control over Input Length, Order and other elements of Endpoint Check Fields

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#84]
Currently the new & edit endpoint are programmatically getting all the fields from the backend, but I'm not able to see where I have individual control over input lengths and order. 

    <div class="editor-option rt-input-styles" style="padding-top: 15px; padding-bottom: 5px; width: auto;     height: auto;" ng-repeat="setting in monitor_types_by_name['ping'].settings">
    <raintank-setting definition="setting" target="currentSettingByVariable(monitors['ping'], setting.variable)">
    </div>

I was going to just try and break out the individual elements and recreate the forms manually, but that seemed silly. Im sure there's a more centralized way to achieve this.

We can also chat about additional features, but this is a good start.

**Comment by woodsaj** [comment]
yeah this is something that i have been thinking about.

The original idea behind dynamically creating the forms based on the monitorType definition was so that we could easily add new monitorTypes without having to update the forms.  However as the litmus product has evolved this is not really necessary.

The definitions currently look like this.
```
{
        "variable": "port",
        "description": "Port",
        "required": false,
        "data_type": "Number",
        "conditions": {},
        "default_value": "80"
      },
      {
        "variable": "method",
        "description": "Method",
        "required": false,
        "data_type": "Enum",
        "conditions": {
          "values": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "HEAD"
          ]
        },
        "default_value": "GET"
      },
```

If we still want to control the form based on these definitions, then it would be fairly easy to just add a 'size' attribute under 'conditions'

We can then use the condition when building the form elements in
https://github.com/raintank/grafana/blob/endpoint_config_changes/public/plugins/raintank/directives/all.js#L25

**Comment by mattttt** [comment]
great. if you want to add your own fields to the "conditions".  here is how.

1) connect to the db.  `sqlite3 data/grafana.db`

2) get a list of current conditions. `select monitor_type_setting.id,name, variable, data_type,  conditions from monitor_type_setting join monitor_type on monitor_type.id = monitor_type_setting.monitor_type_id;`

3) update the conditions as desired.  the first column is the id field. `update monitor_type_setting set conditions='{"size": 5}' where id=3;`   if the setting already has condtions, then add to them `update monitor_type_setting set conditions='{"values": ["GET", "POST","PUT","DELETE", "HEAD"], "size": 10}' where id=4`

**Comment by mattttt** [comment]
@nopzor1200 reminded me that I should put a mockup together and hand it off to @woodsaj and he'll make it work.

**Comment by nopzor1200** [comment]
yep, and said mockup/html/css could also include the 2-3 initial alerting UI components that are built into each check

**Comment by mattttt** [comment]
Playing with field order and length. Need to get a bit of better clarification about what I should be grouping together, but I think it's a good first start. 

![revised-endpoint-config](https://cloud.githubusercontent.com/assets/2886187/7732351/5ab38492-fef5-11e4-9d03-884579f646a9.png)

@nopzor1200 Perhaps we can chat about this a bit today/tomorrow?

**Comment by nopzor1200** [comment]
Starting to look good!

- I don't think that we should put the "With this is config, you'll know in X minutes if there's a problem"

- Some language about how we are going to alert (ie. I'd want to know if I'm going to get emailed every 10 seconds if its error state (no)). Maybe the text can be "When the ping health status changes, send a notificaton to the following emails:"

- I think it would be more user friendly to take a URL for the HTTP/HTTPS config (instead of separate port, hostname, path). This can still be stored as separate items on the backend but I think that offering a URL is more seamless to the user

**Comment by mattttt** [comment]
Another pass based on @nopzor1200 feedback above and in person.

@bulletfactory I could really use a design pass on this to make it actually look good. It's feeling unorganized to me, and I think im too close to the issue atm to see the solution:

![revised-endpoint-config-v234357](https://cloud.githubusercontent.com/assets/2886187/7734227/9aaf4ed4-ff02-11e4-80eb-886511b2553e.png)

**Comment by bulletfactory** [comment]
cleaned up some of the elements, shortened the page some and better standardized form width.
![config_tweaks](https://cloud.githubusercontent.com/assets/1950595/7753055/0bc5cb1c-ffb1-11e4-889d-b4e5d5382936.jpg)

**Comment by mattttt** [comment]
@woodsaj We'll be building out the front-end to match this, but having this control over the fields will require backend changes. 

Happy to chat about it via video chat tonight if you think any of this will be a problem.

**Comment by mattttt** [comment]
@nchristus To see the functionality of the radio button/select combo, see this Invsion prototype: http://invis.io/RQ31L4NMC
*Disregard the location of the fields in the invision, the image above is the correct order of the fields*

Tonight I'd focus on getting a single grouping to work (HTTP or HTTPS). If you have time, go ahead and do the rest - otherwise I can take your work on HTTP and extend it to the rest tomorrow morning. 

Things of note:
- All input labels & input boxes should be consistent sizes. In the image above, it looks like Frequency and Hostname are bigger, but disregard that. 
- The DNS Servers and Alerting boxes dont need that fancy tag/gmail interface right now - a textarea will be perfect. 
- The dropdowns for Dynamic Footprint and Static Footprint are an extension on the work you did last week. Just note that their location should be as in the screenshot before, not as in the invision.

**Comment by mattttt** [comment]
Starting to come together in mattttt_endpoint_list_13

@woodsaj Going to aim to just get the Ping section put together, and then can we convert it to a partial of some kind? Even if we have to do 2 partials (to cover differences in form layout across checks), I like not having to make changes in 4 spots for basic structure stuff.

**Comment by woodsaj** [comment]
The backend uses a single directive for all form fields.  The directive currently changes the input field layout based on the options in the monitorTypes definition.  This directive is used for all check types (ping, dns, http/s).  With the current approach, you can't have different styling based on the check type and option name. ie you can't have dns.servers render differently to ping.hostname (both are string types, rendered as <input type=text>).

Given the level of customization we want, we should just move away from the directive and define the styling in the endpoints_edit.html partial.  If you want to keep the code separate, then you can create new files an use the ngInclude directive to load them in.

```
<div ng-include="plugins/raintank/features/partials/pingForm.html"></div>
```

To bind your form elements use these as an example.
```
<input type="text" ng-model="currentSettingByVariable(monitors['ping'], 'hostname').value">

<input type="checkbox" ng-true-value="'true'" ng-false-value="'false'" ng-model="currentSettingByVariable(monitors['https'], 'validateCert').value">
```

**Comment by mattttt** [comment]
@woodsaj Since endpoint new and endpoint edit use the same form and style, can we introduce one more level of abstraction that both can include?

**Comment by woodsaj** [comment]
Yes, the new and edit use different partials, but they already share the same controller (javascript)

So you should just be able to create pingForm, DNSForm, HTTPForm, HTTPSForm partials that are used for both new and edit views.

**Comment by woodsaj** [comment]
Of if you want, you can just use 1 partial for all check types and include that in both the endpoint_new.html and endpoints_edit.html

**Comment by mattttt** [comment]
Having some issues getting the partials to work, but the styling is pretty much how we want it to be. Going to work with @woodsaj tonight as soon as he wakes up (sorry, @woodsaj, i know im needy) - and then roll it into endpoint_new. 

With those two changes in place, we can comment out the Health & Alerting and roll it out into TinyAlpha tonight.

**Comment by mattttt** [comment]
0.13 release blocking changes and tweaks covered in new issue: https://github.com/raintank/grafana/issues/136
