### ISSUE TITLE
Summarizing Total Individual Collectors selected and Total Tags selected

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#85]
Need to get the sum of individual collectors, tag collectors, and grand total available within endpointCollectorSelect.html, line 4. Dont know how to get that out of Angular, unfortunately.

**Comment by woodsaj** [comment]
```
{{model.collector_ids.length}} Individual Collectors, {{model.collector_tags.length}} Tags
```

**Comment by mattttt** [comment]
Thanks! Closing.
