### ISSUE TITLE
tracking important errors

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#91]
do we have any convention on how we will keep tabs on critical/important error events in grafana?
maybe log to a file and then use heka or logstash to shove them into ES?

**Comment by woodsaj** [comment]
You can use the existing events in Grafana.

https://github.com/raintank/grafana/blob/master/pkg/events/events.go

If enabled, these events will be pushed to a rabbitmq Topic Exchange with the routingKey set to `Priority.eventType`.  This is handled by eventpublisher.eventListener
https://github.com/raintank/grafana/blob/master/pkg/services/eventpublisher/eventpublisher.go#L135

So an event defined as

```
type OrgCreated struct {
	Timestamp time.Time `json:"timestamp"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
}
```

will use the routingKey `INFO.org.created`

The events package will need some updating as it hard codes the event.Priority to 'INFO'

**Comment by torkelo** [comment]
@woodsaj not sure the events bus is optimal for this, more meant for business/application events. But could I guess be used for logging events as well.

**Comment by Dieterbe** [comment]
so do we have consensus that this is the best approach? is it still the right approach when we consider regular grafana users who want to run grafana on their server and have a different way to track errors? they often use something like logstash, so in that case a different eventlistener would be needed that pushes to a logstash queue or something i suppose? or perhaps an event listener that writes events to a text file log? (not something for us to worry too much about now, but good to keep in the back of our mind)

**Comment by torkelo** [comment]
one solution is to have something external (like logstash), tail log files and push to ES

**Comment by torkelo** [comment]
but I guess  pushing directly to rabbit -> logstash -> ES has some advantages in that you can log more rich data (as json) and have that data indexed and searchable in ES, without going through logfile -> logstash parsing -> ES

**Comment by Dieterbe** [comment]
not sure how i should go about the actual log calls.
all the current stuff seems to use a session and sess.publishAfterCommit() but that seems overkill and i don't grok it yet.

FWIW my current idea is (not tested yet)

```
diff --git a/pkg/events/events.go b/pkg/events/events.go
index c3dcac3..bb3ea82 100644
--- a/pkg/events/events.go
+++ b/pkg/events/events.go
@@ -35,7 +35,6 @@ func ToOnWriteEvent(event interface{}) (*OnTheWireEvent, error) {
        eventType := reflect.TypeOf(event).Elem()
 
        wireEvent := OnTheWireEvent{
-               Priority:  PRIO_INFO,
                EventType: eventType.Name(),
                Payload:   event,
        }
@@ -47,6 +46,13 @@ func ToOnWriteEvent(event interface{}) (*OnTheWireEvent, error) {
                wireEvent.Timestamp = time.Now()
        }
 
+       baseField = reflect.Indirect(reflect.ValueOf(event)).FieldByName("Priority")
+       if baseField.IsValid() {
+               wireEvent.Priority = baseField.Interface().(Priority)
+       } else {
+               wireEvent.Priority = PRIO_INFO
+       }
+
        return &wireEvent, nil
 }
 
@@ -77,3 +83,9 @@ type UserUpdated struct {
        Login     string    `json:"login"`
        Email     string    `json:"email"`
 }
+
+type Error struct {
+       Timestamp time.Time `json:"timestamp"`
+       Title     string    `json:"title"`
+       Body      string    `json:"body"` // optional
+}
```

**Comment by torkelo** [comment]
bus Publish code does not use publishAfterCommit , publishAfterCommit is just a utility function in the sqlstore package.

**Comment by torkelo** [comment]
not sure I understand your comment "my current idea is"? just looks like code paste from the events.go

**Comment by Dieterbe** [comment]
no it's a diff that shows some additions, basically an error type and a way to override the priority

**Comment by Dieterbe** [comment]
k i'll use bus.Publish

**Comment by torkelo** [comment]
@Dieterbe but bus Publish is for business events, for logging use the log package

**Comment by torkelo** [comment]
if you want to pipe log messages to rabbitmq you could write a rabbitmq log writer

**Comment by Dieterbe** [comment]
hm not sure if i'll get to that before end of next week, but i guess that could fairly easily be done by one of you guys if needed. so i'll focus more on the specifics of alerting itself for now.

**Comment by torkelo** [comment]
@Dieterbe yea, I think that is probably best. Getting grafana logs to elasticsearch can be fixed later

**Comment by nopzor1200** [comment]
Can the messages generated by Litmus go into the same storage backend as the messages that are generated from the Collectors? (so they can be viewed in the events panel from elasticsearch)?

**Comment by Dieterbe** [comment]
i don't see why they couldn't, but one thing to keep in mind is decoupling the monitoring system from the system being monitored. if prod ES goes down for whatever reason then we'll want to look at events in a monitoring system which probably should not be the same ES instance.
(also, if you want to log events like `error: can't write to ES` than logging those to the same ES would only make it worse)

**Comment by nopzor1200** [comment]
@woodsaj to make a call on this

potentially loggly, potentially ELK...

but all in agreement that centralized logging for * is required

**Comment by Dieterbe** [comment]
have we made a decision on this? @woodsaj @ctdk

**Comment by woodsaj** [comment]
Given that we now have ELK set up, i think the best approach is to just log warnings and errors.  WE just need to ensure that the log messages contain all relevant data.

**Comment by Dieterbe** [comment]
yep. do we need to do a big code review to make sure we have the right log calls in all places or are we pretty confident we're in good shape? I'll review the alerting pkg to be sure of that, at least.

**Comment by ctdk** [comment]
We can do some processing and mutating of the logs as they come into logstash too. I'll have that set up soon.
