### ISSUE TITLE
track internal (gauge) metrics?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#92]
i want to track the number of items in the internal alerting dispatch queue (basically len(channel))
what would be the best way to do this? i know we have an internal fork of the go-metrics library but it only seems to support gauges.

**Comment by torkelo** [comment]
you mean it only supports counters?

**Comment by Dieterbe** [comment]
oops yes that's what i meant.
```
dieter@dieter-m6800 ~ ack -i gauge go/src/github.com/grafana/grafana | grep -v bosun
go/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/mattbaird/elastigo/lib/searchfacet.go:39:  , "langauge": { "terms": {"field": ["repository.language"],"size": "10" }}
dieter@dieter-m6800 ~ 
```

**Comment by Dieterbe** [comment]
we decided to implement statsd
