### ISSUE TITLE
how can the alerting logic know which graphite server / datasource endpoint to query?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#94]
```
mysql> select * from data_source;          
Empty set (0.00 sec)

mysql> 
```

i looked at the other tables, but nowhere do i see where the datasource is configured/defined.

**Comment by woodsaj** [comment]
In the graph/singlestat panels, if the datasource is null, then the default datasource is used.  The default datasource is set in the grafanaBootData, which is included in the html page rendered by the backend. (if you look at the page source, it is in the script tags at the bottom of the body)

if there are no datasources added by the Org that are marked as 'default' then we set the `raintank` dashboard to be the default.

https://github.com/raintank/grafana/blob/master/pkg/api/frontendsettings.go#L91

**Comment by torkelo** [comment]
@woodsaj 
Think you are misunderstanding the question. The alerting backend logic needs to know graphite server details. I guess @Dieterbe wants to know where the raintank graphite-api endpoint is configured?

**Comment by Dieterbe** [comment]
yeah, like where can the alerting code get the datasource details from?

**Comment by torkelo** [comment]
@Dieterbe seems like there is a setting for it
https://github.com/raintank/grafana/blob/master/pkg/api/graphite.go#L15

**Comment by woodsaj** [comment]
yeah, torkel is right, the graphite url is loaded through the config.  it is just a single config item that is the url of the graphite server.

**Comment by Dieterbe** [comment]
works like a charm!
