### ISSUE TITLE
Raintank Button Styles

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#96]
[This is an email from Nick - pasted here for transparency]

Hey dudes,

I cleaned up some of the button styles, reducing some repeated styles using a mixin. 

Commit:
https://github.com/raintank/grafana/commit/2813087c747faa9163bbd2aa1cf51fdb9a269edc

You can see the split/diff here:
https://github.com/raintank/grafana/commit/2813087c747faa9163bbd2aa1cf51fdb9a269edc?diff=split

I noticed that the button rules were doubled up (rt.less and /components/buttons.less), most likely the result of a merge. No big deal. 

A lil' info on the button mixin...

You can see the code here: 
https://github.com/raintank/grafana/commit/2813087c747faa9163bbd2aa1cf51fdb9a269edc#diff-583353f93a161d82216793c19142b134R7

It basically defines a reusable class with all of the style rules that were previously repeated a few times in that file. The idea is to consolidate code that was otherwise repeated and make it reusable and more maintainable.

You'll notice that the mixin takes some color arguments (background, border, color, highlight), which lets you set certain values when invoked.

I'd love it if one or both of you would pull down this branch and run it, giving it a quick look to make sure everything looks good.

Let me know if you have any questions.

Thanks,
Nick

[and in a quick folllowup]

I think what happened is that I had moved the button rules out of rt.less and you had refactored some of the color variables for the buttons, so our changes overlapped. The Github history/diff tools are a lifesaver and usually provide a good overview of what's going on.

The Less mixin helps enforce the DRY (don't repeat yourself) principle. A handful of those buttons shared the same base structure, with the only variation being the colors. The mixin lets us define those base styles once, and extend them w/ color arguments.

CSS mixins are rad :)

**Comment by bulletfactory** [comment]
merged
